Import libraries

In [10]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from tarnet import Tarnet
import sys
from pathlib import Path
project_root = Path("/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [11]:
%time train_df = pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Men/train_men.csv")
%time test_df =  pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Men/test_men.csv")
%time val_df = pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Men/val_men.csv")

CPU times: user 24.1 ms, sys: 6.15 ms, total: 30.3 ms
Wall time: 30.2 ms
CPU times: user 10.3 ms, sys: 5.05 ms, total: 15.4 ms
Wall time: 15.4 ms
CPU times: user 6.1 ms, sys: 926 μs, total: 7.03 ms
Wall time: 7.06 ms

In [12]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['spend']
treatment_feature = ['treatment']

In [13]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [14]:
print('X_train[:10]', X_train[:1].astype(float))

X_train[:10] [[-0.21435131  1.6331766   1.0667411   0.90252386 -1.1010233   1.07039981
   1.00043033  2.70003843 -0.88552759 -0.88616046]]

In [15]:
print('y_train[:10]', y_train[:1].astype(float))

y_train[:10] [[0.]]

In [16]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25567, 10]); y=torch.Size([25567, 1]); t=torch.Size([25567, 1])
Shape of val: x=torch.Size([4262, 10]); y=torch.Size([4262, 1]); t=torch.Size([4262, 1])
Shape of test: x=torch.Size([12784, 10]); y=torch.Size([12784, 1]); t=torch.Size([12784, 1])

In [17]:
epochs = 150
lr = 5.1e-5
wd = 1e-5
early_stop_metric = "qini"
ema = True
ema_alpha = 0.15
patience = 20
shared_dropout = 0.0
outcome_dropout = 0
shared_hidden = 200
outcome_hidden = 100
early_stop_start = 30
activation = torch.nn.ReLU
print (f" epochs = {epochs}")
print (f" learning rate = {lr}")
print (f" weight decay = {wd}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" shared hidden = {shared_hidden}")
print (f" outcome hidden = {outcome_hidden}")
print (f" early stop start = {early_stop_start}")
print (f" activation = {activation}")

 epochs = 150
 learning rate = 5.1e-05
 weight decay = 1e-05
 early stop = qini
 use ema = True
 ema alpha = 0.15
 patience = 20
 shared hidden = 200
 outcome hidden = 100
 early stop start = 30
 activation = <class 'torch.nn.modules.activation.ReLU'>

In [18]:
import pandas as pd
import numpy as np
import torch
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 5e-5, 5e-4, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-4, log=True)
    val_scores = []
    for SEED in seeds:
        seed_everything(SEED)

        tarnet = Tarnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=shared_hidden,
            outcome_hidden=outcome_hidden,
            outcome_dropout=outcome_dropout,
            shared_dropout=shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
            activation=activation
        )

        # Silence CFRNet epoch logs
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            tarnet.fit(train_loader, val_loader)

        x_val_device = x_men_val_t.to(device)
        y0_val_p, y1_val_p= tarnet.predict(x_val_device)
        uplift_val = (y1_val_p - y0_val_p).detach().cpu().numpy().flatten()
        y_val_true_np = y_men_val_t.detach().cpu().numpy().flatten()
        t_val_true_np = t_men_val_t.detach().cpu().numpy().flatten()

        current_val_auqc = auqc(y_val_true_np, t_val_true_np, uplift_val, bins=100, plot=False)
        val_scores.append(current_val_auqc)

    mean_val_auqc = float(np.mean(val_scores))
    std_val_auqc = float(np.std(val_scores, ddof=1)) if len(val_scores) > 1 else 0.0
    trial.set_user_attr("std_Val_AUQC", std_val_auqc)
    return mean_val_auqc

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

# 2. Persist search results in notebook variables
trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": t.params["lr"],
        "weight_decay": t.params["weight_decay"],
        "mean_Val_AUQC": float(t.value),
        "std_Val_AUQC": float(t.user_attrs.get("std_Val_AUQC", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_Val_AUQC", ascending=False).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "mean_Val_AUQC": float(study.best_value),
    "std_Val_AUQC": float(study.best_trial.user_attrs.get("std_Val_AUQC", np.nan))
})

  0%|          | 0/50 [00:00<?, ?it/s]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 0. Best value: 0.823009:   2%|▏         | 1/50 [01:18<1:04:13, 78.64s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 0. Best value: 0.823009:   4%|▍         | 2/50 [02:39<1:04:03, 80.07s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 0. Best value: 0.823009:   6%|▌         | 3/50 [03:52<1:00:10, 76.81s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 3. Best value: 0.828739:   8%|▊         | 4/50 [04:48<52:26, 68.41s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 3. Best value: 0.828739:  10%|█         | 5/50 [06:02<53:01, 70.69s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 3. Best value: 0.828739:  12%|█▏        | 6/50 [07:01<48:44, 66.48s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 3. Best value: 0.828739:  14%|█▍        | 7/50 [08:22<51:09, 71.39s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 3. Best value: 0.828739:  16%|█▌        | 8/50 [09:51<53:51, 76.95s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 3. Best value: 0.828739:  18%|█▊        | 9/50 [10:50<48:43, 71.30s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 3. Best value: 0.828739:  20%|██        | 10/50 [12:05<48:12, 72.32s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 10. Best value: 0.829246:  22%|██▏       | 11/50 [12:58<43:12, 66.48s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 10. Best value: 0.829246:  24%|██▍       | 12/50 [13:51<39:31, 62.41s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 12. Best value: 0.829277:  26%|██▌       | 13/50 [14:45<36:57, 59.94s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 12. Best value: 0.829277:  28%|██▊       | 14/50 [16:19<42:09, 70.27s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 12. Best value: 0.829277:  30%|███       | 15/50 [17:18<38:59, 66.85s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 15. Best value: 0.831389:  32%|███▏      | 16/50 [18:16<36:23, 64.21s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  34%|███▍      | 17/50 [19:19<35:04, 63.79s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  36%|███▌      | 18/50 [20:19<33:19, 62.49s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  38%|███▊      | 19/50 [21:22<32:28, 62.86s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  40%|████      | 20/50 [22:22<30:56, 61.89s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  42%|████▏     | 21/50 [23:49<33:32, 69.41s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  44%|████▍     | 22/50 [24:46<30:43, 65.85s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  46%|████▌     | 23/50 [25:50<29:18, 65.12s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  48%|████▊     | 24/50 [26:55<28:11, 65.06s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  50%|█████     | 25/50 [27:59<26:58, 64.75s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  52%|█████▏    | 26/50 [28:57<25:08, 62.87s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  54%|█████▍    | 27/50 [30:13<25:34, 66.72s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  56%|█████▌    | 28/50 [31:16<24:01, 65.52s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  58%|█████▊    | 29/50 [32:26<23:27, 67.03s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  60%|██████    | 30/50 [33:42<23:16, 69.80s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  62%|██████▏   | 31/50 [34:51<21:57, 69.35s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  64%|██████▍   | 32/50 [35:46<19:34, 65.24s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  66%|██████▌   | 33/50 [36:43<17:45, 62.70s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  68%|██████▊   | 34/50 [37:41<16:17, 61.12s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  70%|███████   | 35/50 [38:36<14:48, 59.24s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  72%|███████▏  | 36/50 [39:44<14:29, 62.10s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  74%|███████▍  | 37/50 [41:00<14:19, 66.09s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  76%|███████▌  | 38/50 [42:14<13:41, 68.43s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  78%|███████▊  | 39/50 [43:42<13:38, 74.38s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  80%|████████  | 40/50 [44:42<11:40, 70.03s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  82%|████████▏ | 41/50 [45:40<09:57, 66.38s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  84%|████████▍ | 42/50 [46:40<08:37, 64.63s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 16. Best value: 0.831515:  86%|████████▌ | 43/50 [47:46<07:35, 65.04s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 43. Best value: 0.83183:  88%|████████▊ | 44/50 [48:40<06:09, 61.62s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 43. Best value: 0.83183:  90%|█████████ | 45/50 [49:30<04:51, 58.32s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 43. Best value: 0.83183:  92%|█████████▏| 46/50 [50:25<03:48, 57.16s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 43. Best value: 0.83183:  94%|█████████▍| 47/50 [51:11<02:41, 53.85s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 43. Best value: 0.83183:  96%|█████████▌| 48/50 [52:00<01:44, 52.38s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 43. Best value: 0.83183:  98%|█████████▊| 49/50 [52:49<00:51, 51.42s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 43. Best value: 0.83183: 100%|██████████| 50/50 [53:42<00:00, 64.44s/it]

In [19]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_AUQC: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 43
Best mean_Val_AUQC: 0.831830
Best params: {'lr': 0.00039980937643540834, 'weight_decay': 7.357284640863698e-05}

Best config table:

       lr  weight_decay  mean_Val_AUQC  std_Val_AUQC
0  0.0004      0.000074        0.83183      0.019659

Top 10 trials:

   trial        lr  weight_decay  mean_Val_AUQC  std_Val_AUQC
0     43  0.000400      0.000074       0.831830      0.019659
1     47  0.000396      0.000060       0.831693      0.021333
2     16  0.000250      0.000066       0.831515      0.025423
3     15  0.000392      0.000064       0.831389      0.019771
4     22  0.000249      0.000077       0.830772      0.025687
5     32  0.000264      0.000062       0.830605      0.023340
6     48  0.000409      0.000082       0.829787      0.020569
7     31  0.000274      0.000048       0.829587      0.021189
8     27  0.000274      0.000049       0.829349      0.020868
9     12  0.000439      0.000099       0.829277      0.026221

In [21]:
import pandas as pd
import numpy as np
import torch

# 1. Cấu hình
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

print(f"🔄 Đang huấn luyện TARNet trên {len(seeds)} seeds khác nhau... Vui lòng đợi.")

# 2. Vòng lặp chạy (Chỉ xử lý, không in kết quả lẻ)
for SEED in seeds:
    seed_everything(SEED)
    
    # Khởi tạo lại mô hình
    tarnet = Tarnet(
        input_dim=x_men_train_t.shape[1], epochs=epochs, learning_rate=0.0004, 
        weight_decay=0.000074	, use_ema=ema, ema_alpha=ema_alpha, patience=patience,
        shared_hidden=shared_hidden, outcome_hidden=outcome_hidden,
        outcome_dropout=outcome_dropout, shared_dropout=shared_dropout,
        early_stop_metric=early_stop_metric, early_stop_start_epoch=early_stop_start,
        activation=activation
    )
    
    tarnet.fit(train_loader, val_loader)
    
    # Predict
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = tarnet.predict(x_men_test_t_on_device)
    
    uplift_pred = (y1_pred - y0_pred).cpu().numpy().flatten()
    y_true = y_men_test_t.cpu().numpy().flatten()
    t_true = t_men_test_t.cpu().numpy().flatten()
    
    # Tính toán
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()
    
    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  ✔️ Đã xong Seed {SEED}")

# 3. HIỂN THỊ KẾT QUẢ TỔNG HỢP (Print 1 lúc)
df_results = pd.DataFrame(all_runs)

print("\n" + "="*85)
print(f"{'CHI TIẾT TỪNG SEED':^85}")
print("="*85)
# Sử dụng to_string để in bảng đẹp mắt
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format, 'AUQC': '{:,.4f}'.format, 
    'Lift': '{:,.4f}'.format, 'KRCC': '{:,.4f}'.format, 'ATE_Err': '{:,.4f}'.format
}))

# 4. Tính toán Mean và Std
mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("="*85)
print(f"{'KẾT QUẢ TRUNG BÌNH (MEAN ± STD)':^85}")
print("-" * 85)
summary_data = []
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")

print("="*85)

🔄 Đang huấn luyện TARNet trên 5 seeds khác nhau... Vui lòng đợi.
Locked random seed: 412312
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/150 | Loss: 445.0355 | Val Loss: 498.5946 | Val Qini: 0.8095 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.8095 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 646.1893 | Val Loss: 498.0936 | Val Qini: 0.7597 (patience: 1/20)EMA Trend: 0.8020 | (patience: 1/20)
Epoch 3/150 | Loss: 302.0763 | Val Loss: 497.3437 | Val Qini: 0.6586 (patience: 2/20)EMA Trend: 0.7805 | (patience: 2/20)
Epoch 4/150 | Loss: 431.1613 | Val Loss: 496.3514 | Val Qini: 0.6493 (patience: 3/20)EMA Trend: 0.7608 | (patience: 3/20)
Epoch 5/150 | Loss: 363.7578 | Val Loss: 495.7518 | Val Qini: 0.6435 (patience: 4/20)EMA Trend: 0.7432 | (patience: 4/20)
Epoch 6/150 | Loss: 334.6230 | Val Loss: 495.7630 | Val Qini: 0.6836 (patience: 5/20)EMA Trend: 0.7343 | (patience: 5/20)
Epoch 7/150 | Loss: 509.1710 | Val Loss: 495.5839 | Val Qini: 0.7478 ✓ above trend but not peak (patience: 6/20)EMA Trend: 0.7363 | ✓ above trend but not peak (patience: 6/20)
Epoch 8/150 | Loss: 326.8683 | Val Loss: 495.5662 | Val Qini: 0.7757 ✓ above trend but not peak (patience: 7/20)EMA Trend: 0.7422 | ✓ above trend but not peak (patience: 7/20)
Epoch 9/150 | Loss: 422.0969 | Val Loss: 495.5883 | Val Qini: 0.8023 ✓ above trend but not peak (patience: 8/20)EMA Trend: 0.7512 | ✓ above trend but not peak (patience: 8/20)
Epoch 10/150 | Loss: 258.3153 | Val Loss: 495.5038 | Val Qini: 0.8104 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7601 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/150 | Loss: 463.3021 | Val Loss: 495.4496 | Val Qini: 0.8154 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7684 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/150 | Loss: 546.9562 | Val Loss: 495.4041 | Val Qini: 0.8230 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7766 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/150 | Loss: 258.9790 | Val Loss: 495.3508 | Val Qini: 0.8278 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7843 | ⭐ NEW BEST (peak ≥ trend)
Epoch 14/150 | Loss: 297.2726 | Val Loss: 495.3352 | Val Qini: 0.8317 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7914 | ⭐ NEW BEST (peak ≥ trend)
Epoch 15/150 | Loss: 480.6385 | Val Loss: 495.3080 | Val Qini: 0.8298 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.7971 | ✓ above trend but not peak (patience: 1/20)
Epoch 16/150 | Loss: 467.9841 | Val Loss: 495.2531 | Val Qini: 0.8273 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.8017 | ✓ above trend but not peak (patience: 2/20)
Epoch 17/150 | Loss: 446.6144 | Val Loss: 495.1750 | Val Qini: 0.8296 ✓ above trend but not peak (patience: 3/20)EMA Trend: 0.8059 | ✓ above trend but not peak (patience: 3/20)
Epoch 18/150 | Loss: 594.0167 | Val Loss: 495.0821 | Val Qini: 0.8283 ✓ above trend but not peak (patience: 4/20)EMA Trend: 0.8092 | ✓ above trend but not peak (patience: 4/20)
Epoch 19/150 | Loss: 227.4012 | Val Loss: 495.0052 | Val Qini: 0.8117 ✓ above trend but not peak (patience: 5/20)EMA Trend: 0.8096 | ✓ above trend but not peak (patience: 5/20)
Epoch 20/150 | Loss: 608.4906 | Val Loss: 495.0038 | Val Qini: 0.8017 (patience: 6/20)EMA Trend: 0.8084 | (patience: 6/20)
Epoch 21/150 | Loss: 467.5681 | Val Loss: 495.0003 | Val Qini: 0.7893 (patience: 7/20)EMA Trend: 0.8055 | (patience: 7/20)
Epoch 22/150 | Loss: 299.1367 | Val Loss: 494.9808 | Val Qini: 0.7726 (patience: 8/20)EMA Trend: 0.8006 | (patience: 8/20)
Epoch 23/150 | Loss: 403.2837 | Val Loss: 494.9224 | Val Qini: 0.7676 (patience: 9/20)EMA Trend: 0.7957 | (patience: 9/20)
Epoch 24/150 | Loss: 532.9399 | Val Loss: 494.8959 | Val Qini: 0.7507 (patience: 10/20)EMA Trend: 0.7889 | (patience: 10/20)
Epoch 25/150 | Loss: 475.6894 | Val Loss: 494.9104 | Val Qini: 0.7291 (patience: 11/20)EMA Trend: 0.7799 | (patience: 11/20)
Epoch 26/150 | Loss: 533.6005 | Val Loss: 494.8191 | Val Qini: 0.7230 (patience: 12/20)EMA Trend: 0.7714 | (patience: 12/20)
Epoch 27/150 | Loss: 209.3961 | Val Loss: 494.8163 | Val Qini: 0.7001 (patience: 13/20)EMA Trend: 0.7607 | (patience: 13/20)
Epoch 28/150 | Loss: 488.0869 | Val Loss: 494.8411 | Val Qini: 0.6903 (patience: 14/20)EMA Trend: 0.7501 | (patience: 14/20)
Epoch 29/150 | Loss: 517.8203 | Val Loss: 495.0062 | Val Qini: 0.6719 (patience: 15/20)EMA Trend: 0.7384 | (patience: 15/20)
Epoch 30/150 | Loss: 418.3247 | Val Loss: 495.0692 | Val Qini: 0.6576 (patience: 16/20)EMA Trend: 0.7263 | (patience: 16/20)
Epoch 31/150 | Loss: 361.9590 | Val Loss: 495.2805 | Val Qini: 0.6101 (patience: 17/20)EMA Trend: 0.7089 | (patience: 17/20)
Epoch 32/150 | Loss: 494.3869 | Val Loss: 495.3579 | Val Qini: 0.6034 (patience: 18/20)EMA Trend: 0.6930 | (patience: 18/20)
Epoch 33/150 | Loss: 388.0844 | Val Loss: 495.3531 | Val Qini: 0.6208 (patience: 19/20)EMA Trend: 0.6822 | (patience: 19/20)
Epoch 34/150 | Loss: 335.0956 | Val Loss: 495.4588 | Val Qini: 0.6029 (patience: 20/20)EMA Trend: 0.6703 | (patience: 20/20)

🛑 Early stopping triggered at epoch 34!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 14
   Best Raw Qini: 0.8317
   Final EMA Trend: 0.6703
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 412312
Locked random seed: 42
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/150 | Loss: 340.0048 | Val Loss: 498.4856 | Val Qini: 0.6135 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6135 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 605.8994 | Val Loss: 498.0941 | Val Qini: 0.6307 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6161 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Loss: 419.9873 | Val Loss: 497.4456 | Val Qini: 0.6612 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6228 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Loss: 477.1383 | Val Loss: 496.5052 | Val Qini: 0.6565 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.6279 | ✓ above trend but not peak (patience: 1/20)
Epoch 5/150 | Loss: 475.7929 | Val Loss: 495.7485 | Val Qini: 0.6651 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6335 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/150 | Loss: 176.0042 | Val Loss: 495.9857 | Val Qini: 0.7135 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6455 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/150 | Loss: 442.6050 | Val Loss: 495.9176 | Val Qini: 0.7497 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6611 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/150 | Loss: 343.7550 | Val Loss: 495.4659 | Val Qini: 0.7736 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6780 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/150 | Loss: 323.2067 | Val Loss: 495.4403 | Val Qini: 0.7906 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6949 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/150 | Loss: 489.4796 | Val Loss: 495.5569 | Val Qini: 0.8028 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7111 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/150 | Loss: 407.2268 | Val Loss: 495.4040 | Val Qini: 0.8185 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7272 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/150 | Loss: 435.3135 | Val Loss: 495.2387 | Val Qini: 0.8222 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7414 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/150 | Loss: 366.6642 | Val Loss: 495.0564 | Val Qini: 0.8351 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7555 | ⭐ NEW BEST (peak ≥ trend)
Epoch 14/150 | Loss: 338.5354 | Val Loss: 494.9501 | Val Qini: 0.8338 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.7672 | ✓ above trend but not peak (patience: 1/20)
Epoch 15/150 | Loss: 337.5753 | Val Loss: 494.8250 | Val Qini: 0.8383 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7779 | ⭐ NEW BEST (peak ≥ trend)
Epoch 16/150 | Loss: 548.9482 | Val Loss: 494.8203 | Val Qini: 0.8358 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.7866 | ✓ above trend but not peak (patience: 1/20)
Epoch 17/150 | Loss: 427.2821 | Val Loss: 494.8141 | Val Qini: 0.8327 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.7935 | ✓ above trend but not peak (patience: 2/20)
Epoch 18/150 | Loss: 552.3971 | Val Loss: 494.7965 | Val Qini: 0.8238 ✓ above trend but not peak (patience: 3/20)EMA Trend: 0.7980 | ✓ above trend but not peak (patience: 3/20)
Epoch 19/150 | Loss: 521.4705 | Val Loss: 494.7803 | Val Qini: 0.8110 ✓ above trend but not peak (patience: 4/20)EMA Trend: 0.8000 | ✓ above trend but not peak (patience: 4/20)
Epoch 20/150 | Loss: 283.6435 | Val Loss: 494.7399 | Val Qini: 0.7981 (patience: 5/20)EMA Trend: 0.7997 | (patience: 5/20)
Epoch 21/150 | Loss: 565.7147 | Val Loss: 494.6801 | Val Qini: 0.7859 (patience: 6/20)EMA Trend: 0.7976 | (patience: 6/20)
Epoch 22/150 | Loss: 515.8027 | Val Loss: 494.6284 | Val Qini: 0.7851 (patience: 7/20)EMA Trend: 0.7958 | (patience: 7/20)
Epoch 23/150 | Loss: 298.2923 | Val Loss: 494.6961 | Val Qini: 0.7642 (patience: 8/20)EMA Trend: 0.7910 | (patience: 8/20)
Epoch 24/150 | Loss: 438.3529 | Val Loss: 494.8337 | Val Qini: 0.6945 (patience: 9/20)EMA Trend: 0.7766 | (patience: 9/20)
Epoch 25/150 | Loss: 266.4776 | Val Loss: 494.9096 | Val Qini: 0.6588 (patience: 10/20)EMA Trend: 0.7589 | (patience: 10/20)
Epoch 26/150 | Loss: 449.8506 | Val Loss: 494.9538 | Val Qini: 0.6432 (patience: 11/20)EMA Trend: 0.7416 | (patience: 11/20)
Epoch 27/150 | Loss: 327.0276 | Val Loss: 494.9090 | Val Qini: 0.6406 (patience: 12/20)EMA Trend: 0.7264 | (patience: 12/20)
Epoch 28/150 | Loss: 496.7829 | Val Loss: 494.9534 | Val Qini: 0.6189 (patience: 13/20)EMA Trend: 0.7103 | (patience: 13/20)
Epoch 29/150 | Loss: 571.1577 | Val Loss: 495.0697 | Val Qini: 0.5717 (patience: 14/20)EMA Trend: 0.6895 | (patience: 14/20)
Epoch 30/150 | Loss: 358.4407 | Val Loss: 495.0423 | Val Qini: 0.5965 (patience: 15/20)EMA Trend: 0.6755 | (patience: 15/20)
Epoch 31/150 | Loss: 466.9650 | Val Loss: 495.0594 | Val Qini: 0.5923 (patience: 16/20)EMA Trend: 0.6631 | (patience: 16/20)
Epoch 32/150 | Loss: 280.0727 | Val Loss: 495.0857 | Val Qini: 0.5738 (patience: 17/20)EMA Trend: 0.6497 | (patience: 17/20)
Epoch 33/150 | Loss: 237.9912 | Val Loss: 495.2390 | Val Qini: 0.5352 (patience: 18/20)EMA Trend: 0.6325 | (patience: 18/20)
Epoch 34/150 | Loss: 559.6822 | Val Loss: 495.2695 | Val Qini: 0.5545 (patience: 19/20)EMA Trend: 0.6208 | (patience: 19/20)
Epoch 35/150 | Loss: 557.7994 | Val Loss: 495.1733 | Val Qini: 0.5882 (patience: 20/20)EMA Trend: 0.6159 | (patience: 20/20)

🛑 Early stopping triggered at epoch 35!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 15
   Best Raw Qini: 0.8383
   Final EMA Trend: 0.6159
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 42
Locked random seed: 1874
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/150 | Loss: 289.4987 | Val Loss: 498.5326 | Val Qini: 0.6886 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6886 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 433.2641 | Val Loss: 498.2672 | Val Qini: 0.6579 (patience: 1/20)EMA Trend: 0.6840 | (patience: 1/20)
Epoch 3/150 | Loss: 461.5742 | Val Loss: 497.8573 | Val Qini: 0.6743 (patience: 2/20)EMA Trend: 0.6825 | (patience: 2/20)
Epoch 4/150 | Loss: 340.0582 | Val Loss: 497.2379 | Val Qini: 0.6731 (patience: 3/20)EMA Trend: 0.6811 | (patience: 3/20)
Epoch 5/150 | Loss: 531.6432 | Val Loss: 496.5123 | Val Qini: 0.6485 (patience: 4/20)EMA Trend: 0.6762 | (patience: 4/20)
Epoch 6/150 | Loss: 575.5289 | Val Loss: 496.2365 | Val Qini: 0.6527 (patience: 5/20)EMA Trend: 0.6727 | (patience: 5/20)
Epoch 7/150 | Loss: 479.4737 | Val Loss: 496.2720 | Val Qini: 0.6887 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6751 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/150 | Loss: 337.7296 | Val Loss: 495.9472 | Val Qini: 0.7264 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6828 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/150 | Loss: 391.0697 | Val Loss: 495.7397 | Val Qini: 0.7488 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6927 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/150 | Loss: 474.5657 | Val Loss: 495.6802 | Val Qini: 0.7556 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7021 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/150 | Loss: 361.7889 | Val Loss: 495.6362 | Val Qini: 0.7736 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7128 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/150 | Loss: 550.6028 | Val Loss: 495.5528 | Val Qini: 0.7804 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7230 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/150 | Loss: 373.2375 | Val Loss: 495.4525 | Val Qini: 0.7854 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7323 | ⭐ NEW BEST (peak ≥ trend)
Epoch 14/150 | Loss: 532.2054 | Val Loss: 495.3833 | Val Qini: 0.7920 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7413 | ⭐ NEW BEST (peak ≥ trend)
Epoch 15/150 | Loss: 562.2829 | Val Loss: 495.3184 | Val Qini: 0.7988 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7499 | ⭐ NEW BEST (peak ≥ trend)
Epoch 16/150 | Loss: 464.9072 | Val Loss: 495.2809 | Val Qini: 0.7953 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.7567 | ✓ above trend but not peak (patience: 1/20)
Epoch 17/150 | Loss: 457.2638 | Val Loss: 495.2604 | Val Qini: 0.7968 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.7627 | ✓ above trend but not peak (patience: 2/20)
Epoch 18/150 | Loss: 385.1818 | Val Loss: 495.2363 | Val Qini: 0.7935 ✓ above trend but not peak (patience: 3/20)EMA Trend: 0.7674 | ✓ above trend but not peak (patience: 3/20)
Epoch 19/150 | Loss: 595.2858 | Val Loss: 495.2335 | Val Qini: 0.7858 ✓ above trend but not peak (patience: 4/20)EMA Trend: 0.7701 | ✓ above trend but not peak (patience: 4/20)
Epoch 20/150 | Loss: 434.7028 | Val Loss: 495.2044 | Val Qini: 0.7766 ✓ above trend but not peak (patience: 5/20)EMA Trend: 0.7711 | ✓ above trend but not peak (patience: 5/20)
Epoch 21/150 | Loss: 361.8547 | Val Loss: 495.1494 | Val Qini: 0.7691 (patience: 6/20)EMA Trend: 0.7708 | (patience: 6/20)
Epoch 22/150 | Loss: 430.7829 | Val Loss: 495.1195 | Val Qini: 0.7563 (patience: 7/20)EMA Trend: 0.7686 | (patience: 7/20)
Epoch 23/150 | Loss: 336.2979 | Val Loss: 495.1427 | Val Qini: 0.7303 (patience: 8/20)EMA Trend: 0.7629 | (patience: 8/20)
Epoch 24/150 | Loss: 448.3209 | Val Loss: 495.0645 | Val Qini: 0.7202 (patience: 9/20)EMA Trend: 0.7565 | (patience: 9/20)
Epoch 25/150 | Loss: 450.4343 | Val Loss: 495.1187 | Val Qini: 0.6819 (patience: 10/20)EMA Trend: 0.7453 | (patience: 10/20)
Epoch 26/150 | Loss: 560.5611 | Val Loss: 495.1053 | Val Qini: 0.6743 (patience: 11/20)EMA Trend: 0.7346 | (patience: 11/20)
Epoch 27/150 | Loss: 707.6649 | Val Loss: 495.0508 | Val Qini: 0.6770 (patience: 12/20)EMA Trend: 0.7260 | (patience: 12/20)
Epoch 28/150 | Loss: 622.5115 | Val Loss: 495.0735 | Val Qini: 0.6629 (patience: 13/20)EMA Trend: 0.7165 | (patience: 13/20)
Epoch 29/150 | Loss: 449.3841 | Val Loss: 495.0861 | Val Qini: 0.6495 (patience: 14/20)EMA Trend: 0.7065 | (patience: 14/20)
Epoch 30/150 | Loss: 451.9543 | Val Loss: 495.1653 | Val Qini: 0.6220 (patience: 15/20)EMA Trend: 0.6938 | (patience: 15/20)
Epoch 31/150 | Loss: 505.0049 | Val Loss: 495.2895 | Val Qini: 0.5970 (patience: 16/20)EMA Trend: 0.6793 | (patience: 16/20)
Epoch 32/150 | Loss: 523.4399 | Val Loss: 495.3471 | Val Qini: 0.5966 (patience: 17/20)EMA Trend: 0.6669 | (patience: 17/20)
Epoch 33/150 | Loss: 417.1750 | Val Loss: 495.4650 | Val Qini: 0.5686 (patience: 18/20)EMA Trend: 0.6521 | (patience: 18/20)
Epoch 34/150 | Loss: 477.4465 | Val Loss: 495.4920 | Val Qini: 0.5780 (patience: 19/20)EMA Trend: 0.6410 | (patience: 19/20)
Epoch 35/150 | Loss: 346.0010 | Val Loss: 495.5035 | Val Qini: 0.5844 (patience: 20/20)EMA Trend: 0.6325 | (patience: 20/20)

🛑 Early stopping triggered at epoch 35!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 15
   Best Raw Qini: 0.7988
   Final EMA Trend: 0.6325
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 1874
Locked random seed: 902745
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/150 | Loss: 532.7273 | Val Loss: 498.6263 | Val Qini: 0.3675 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.3675 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 239.1582 | Val Loss: 498.3773 | Val Qini: 0.3858 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.3702 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Loss: 554.1078 | Val Loss: 498.0029 | Val Qini: 0.6399 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.4107 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Loss: 534.3463 | Val Loss: 497.3944 | Val Qini: 0.6864 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.4520 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/150 | Loss: 351.3226 | Val Loss: 496.5796 | Val Qini: 0.6940 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.4883 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/150 | Loss: 296.6936 | Val Loss: 495.9606 | Val Qini: 0.7278 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5242 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/150 | Loss: 380.6453 | Val Loss: 495.6752 | Val Qini: 0.7789 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5624 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/150 | Loss: 602.7495 | Val Loss: 495.4374 | Val Qini: 0.8164 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6005 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/150 | Loss: 469.2533 | Val Loss: 495.3254 | Val Qini: 0.8434 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6370 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/150 | Loss: 600.3994 | Val Loss: 495.2628 | Val Qini: 0.8526 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6693 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/150 | Loss: 564.2651 | Val Loss: 495.1729 | Val Qini: 0.8504 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.6965 | ✓ above trend but not peak (patience: 1/20)
Epoch 12/150 | Loss: 388.3254 | Val Loss: 495.0378 | Val Qini: 0.8504 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.7196 | ✓ above trend but not peak (patience: 2/20)
Epoch 13/150 | Loss: 524.2151 | Val Loss: 494.9886 | Val Qini: 0.8566 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7401 | ⭐ NEW BEST (peak ≥ trend)
Epoch 14/150 | Loss: 386.3698 | Val Loss: 494.9891 | Val Qini: 0.8501 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.7566 | ✓ above trend but not peak (patience: 1/20)
Epoch 15/150 | Loss: 749.6788 | Val Loss: 494.9295 | Val Qini: 0.8533 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.7711 | ✓ above trend but not peak (patience: 2/20)
Epoch 16/150 | Loss: 598.9158 | Val Loss: 494.8826 | Val Qini: 0.8497 ✓ above trend but not peak (patience: 3/20)EMA Trend: 0.7829 | ✓ above trend but not peak (patience: 3/20)
Epoch 17/150 | Loss: 424.2806 | Val Loss: 494.8972 | Val Qini: 0.8465 ✓ above trend but not peak (patience: 4/20)EMA Trend: 0.7924 | ✓ above trend but not peak (patience: 4/20)
Epoch 18/150 | Loss: 625.4423 | Val Loss: 494.8922 | Val Qini: 0.8359 ✓ above trend but not peak (patience: 5/20)EMA Trend: 0.7990 | ✓ above trend but not peak (patience: 5/20)
Epoch 19/150 | Loss: 461.8454 | Val Loss: 494.8952 | Val Qini: 0.8300 ✓ above trend but not peak (patience: 6/20)EMA Trend: 0.8036 | ✓ above trend but not peak (patience: 6/20)
Epoch 20/150 | Loss: 566.1838 | Val Loss: 494.9182 | Val Qini: 0.8228 ✓ above trend but not peak (patience: 7/20)EMA Trend: 0.8065 | ✓ above trend but not peak (patience: 7/20)
Epoch 21/150 | Loss: 642.6755 | Val Loss: 494.9070 | Val Qini: 0.8110 ✓ above trend but not peak (patience: 8/20)EMA Trend: 0.8072 | ✓ above trend but not peak (patience: 8/20)
Epoch 22/150 | Loss: 429.8593 | Val Loss: 494.8582 | Val Qini: 0.7968 (patience: 9/20)EMA Trend: 0.8056 | (patience: 9/20)
Epoch 23/150 | Loss: 505.2513 | Val Loss: 494.8253 | Val Qini: 0.7919 (patience: 10/20)EMA Trend: 0.8035 | (patience: 10/20)