Import libraries

In [13]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from tarnet import Tarnet
import sys
from pathlib import Path
project_root = Path("/home/ducm/Benchmark-conversion-vs-revenue-uplift-modeling/Revenue/Tarnet/main_tarnet.ipynb")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [14]:
%time train_df = pd.read_csv(r"../../dataset/Hillstrom/Women/train_women.csv")
%time test_df =  pd.read_csv(r"../../dataset/Hillstrom/Women/test_women.csv")
%time val_df = pd.read_csv(r"../../dataset/Hillstrom/Women/val_women.csv")

CPU times: user 23.9 ms, sys: 6.99 ms, total: 30.9 ms
Wall time: 30.2 ms
CPU times: user 9.7 ms, sys: 7.02 ms, total: 16.7 ms
Wall time: 16.6 ms
CPU times: user 4.63 ms, sys: 0 ns, total: 4.63 ms
Wall time: 4.6 ms

In [15]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['spend']
treatment_feature = ['treatment']

In [16]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [17]:
# Cách làm đúng: Chỉ tính trên khách hàng có phát sinh giao dịch
revenue_only = y_train[y_train > 0]
if len(revenue_only) > 0:
    threshold = np.percentile(revenue_only, 99) # Lấy top 1% của những người mua hàng
    y_train_clipped = np.clip(y_train, 0, threshold)
    y_val = np.clip(y_val, 0, threshold)
    print(f"Ngưỡng clip thực tế: {threshold}")

Ngưỡng clip thực tế: 499.0

In [18]:
print('X_train[:10]', X_train[:1].astype(float))

X_train[:10] [[-0.78953321  1.6460815   1.41745802 -1.11692492  0.91314538  1.07643872
   0.9950542  -0.36894675 -0.88924565  1.13133938]]

In [19]:
print('y_train[:10]', y_train[:1].astype(float))

y_train[:10] [[0.]]

In [20]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25615, 10]); y=torch.Size([25615, 1]); t=torch.Size([25615, 1])
Shape of val: x=torch.Size([4270, 10]); y=torch.Size([4270, 1]); t=torch.Size([4270, 1])
Shape of test: x=torch.Size([12808, 10]); y=torch.Size([12808, 1]); t=torch.Size([12808, 1])

In [21]:
epochs = 150
lr = 5e-5
wd = 1e-5
early_stop_metric = "ema_qini"
ema = True
ema_alpha = 0.35
patience = 20
shared_dropout = 0      
outcome_dropout = 0.
shared_hidden = 200
outcome_hidden = 100
early_stop_start = 30
activation = torch.nn.ReLU
print (f" epochs = {epochs}")
print (f" learning rate = {lr}")
print (f" weight decay = {wd}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" shared hidden = {shared_hidden}")
print (f" outcome hidden = {outcome_hidden}")
print (f" early stop start = {early_stop_start}")
print (f" activation = {activation}")

 epochs = 150
 learning rate = 5e-05
 weight decay = 1e-05
 early stop = ema_qini
 use ema = True
 ema alpha = 0.35
 patience = 20
 shared hidden = 200
 outcome hidden = 100
 early stop start = 30
 activation = <class 'torch.nn.modules.activation.ReLU'>

In [22]:
import pandas as pd
import numpy as np
import torch
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 5e-5, 5e-4, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-4, log=True)
    val_scores = []
    for SEED in seeds:
        seed_everything(SEED)

        tarnet = Tarnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=shared_hidden,
            outcome_hidden=outcome_hidden,
            outcome_dropout=outcome_dropout,
            shared_dropout=shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
            activation=activation
        )

        # Silence CFRNet epoch logs
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            tarnet.fit(train_loader, val_loader)

        x_val_device = x_men_val_t.to(device)
        y0_val_p, y1_val_p= tarnet.predict(x_val_device)
        uplift_val = (y1_val_p - y0_val_p).detach().cpu().numpy().flatten()
        y_val_true_np = y_men_val_t.detach().cpu().numpy().flatten()
        t_val_true_np = t_men_val_t.detach().cpu().numpy().flatten()

        current_val_auqc = auqc(y_val_true_np, t_val_true_np, uplift_val, bins=100, plot=False)
        val_scores.append(current_val_auqc)

    mean_val_auqc = float(np.mean(val_scores))
    std_val_auqc = float(np.std(val_scores, ddof=1)) if len(val_scores) > 1 else 0.0
    trial.set_user_attr("std_Val_AUQC", std_val_auqc)
    return mean_val_auqc

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

# 2. Persist search results in notebook variables
trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": t.params["lr"],
        "weight_decay": t.params["weight_decay"],
        "mean_Val_AUQC": float(t.value),
        "std_Val_AUQC": float(t.user_attrs.get("std_Val_AUQC", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_Val_AUQC", ascending=False).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "mean_Val_AUQC": float(study.best_value),
    "std_Val_AUQC": float(study.best_trial.user_attrs.get("std_Val_AUQC", np.nan))
})

  0%|          | 0/50 [00:00<?, ?it/s]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 0. Best value: 1.15005:   2%|▏         | 1/50 [01:14<1:00:33, 74.16s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 1. Best value: 1.16307:   4%|▍         | 2/50 [02:30<1:00:16, 75.34s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 1. Best value: 1.16307:   6%|▌         | 3/50 [03:39<56:56, 72.68s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 1. Best value: 1.16307:   8%|▊         | 4/50 [04:49<54:49, 71.50s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 1. Best value: 1.16307:  10%|█         | 5/50 [06:02<53:53, 71.86s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 1. Best value: 1.16307:  12%|█▏        | 6/50 [07:11<51:59, 70.90s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 1. Best value: 1.16307:  14%|█▍        | 7/50 [08:27<52:06, 72.71s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 1. Best value: 1.16307:  16%|█▌        | 8/50 [09:39<50:38, 72.35s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 1. Best value: 1.16307:  18%|█▊        | 9/50 [10:49<49:07, 71.90s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 1. Best value: 1.16307:  20%|██        | 10/50 [12:04<48:27, 72.70s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 1. Best value: 1.16307:  22%|██▏       | 11/50 [13:15<46:56, 72.22s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 11. Best value: 1.17852:  24%|██▍       | 12/50 [14:32<46:41, 73.72s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 11. Best value: 1.17852:  26%|██▌       | 13/50 [15:50<46:16, 75.05s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  28%|██▊       | 14/50 [17:11<46:07, 76.88s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  30%|███       | 15/50 [18:21<43:34, 74.70s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  32%|███▏      | 16/50 [19:42<43:26, 76.66s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  34%|███▍      | 17/50 [20:54<41:16, 75.04s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  36%|███▌      | 18/50 [22:12<40:29, 75.91s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  38%|███▊      | 19/50 [23:35<40:25, 78.23s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  40%|████      | 20/50 [24:53<39:02, 78.09s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  42%|████▏     | 21/50 [26:07<37:06, 76.76s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  44%|████▍     | 22/50 [27:27<36:22, 77.93s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  46%|████▌     | 23/50 [28:49<35:31, 78.94s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  48%|████▊     | 24/50 [30:00<33:13, 76.66s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  50%|█████     | 25/50 [31:10<31:06, 74.64s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  52%|█████▏    | 26/50 [32:31<30:35, 76.50s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  54%|█████▍    | 27/50 [33:48<29:22, 76.61s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  56%|█████▌    | 28/50 [34:58<27:21, 74.63s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  58%|█████▊    | 29/50 [36:08<25:41, 73.41s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  60%|██████    | 30/50 [37:22<24:30, 73.50s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  62%|██████▏   | 31/50 [38:37<23:27, 74.09s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  64%|██████▍   | 32/50 [39:59<22:55, 76.40s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  66%|██████▌   | 33/50 [41:21<22:04, 77.93s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  68%|██████▊   | 34/50 [42:37<20:39, 77.45s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  70%|███████   | 35/50 [43:54<19:22, 77.49s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  72%|███████▏  | 36/50 [45:11<18:01, 77.22s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  74%|███████▍  | 37/50 [46:34<17:07, 79.04s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  76%|███████▌  | 38/50 [47:51<15:40, 78.35s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  78%|███████▊  | 39/50 [49:06<14:10, 77.35s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  80%|████████  | 40/50 [50:21<12:47, 76.70s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  82%|████████▏ | 41/50 [51:32<11:15, 75.02s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  84%|████████▍ | 42/50 [52:51<10:09, 76.15s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  86%|████████▌ | 43/50 [54:11<09:00, 77.14s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  88%|████████▊ | 44/50 [55:21<07:29, 74.97s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  90%|█████████ | 45/50 [56:35<06:14, 74.96s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  92%|█████████▏| 46/50 [57:51<05:00, 75.07s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  94%|█████████▍| 47/50 [59:06<03:45, 75.11s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  96%|█████████▌| 48/50 [1:00:28<02:34, 77.18s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371:  98%|█████████▊| 49/50 [1:01:46<01:17, 77.38s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 13. Best value: 1.18371: 100%|██████████| 50/50 [1:03:05<00:00, 75.72s/it]

In [23]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_AUQC: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 13
Best mean_Val_AUQC: 1.183715
Best params: {'lr': 8.82782155013677e-05, 'weight_decay': 1.039251434722866e-05}

Best config table:

         lr  weight_decay  mean_Val_AUQC  std_Val_AUQC
0  0.000088       0.00001       1.183715      0.173838

Top 10 trials:

   trial        lr  weight_decay  mean_Val_AUQC  std_Val_AUQC
0     13  0.000088      0.000010       1.183715      0.173838
1     48  0.000106      0.000035       1.181011      0.176720
2     45  0.000120      0.000011       1.179696      0.189316
3     49  0.000101      0.000035       1.179539      0.169756
4     32  0.000098      0.000014       1.179522      0.173581
5     41  0.000099      0.000016       1.178908      0.177279
6     37  0.000120      0.000012       1.178658      0.187856
7     11  0.000119      0.000013       1.178520      0.196301
8     15  0.000091      0.000015       1.177866      0.179136
9     22  0.000092      0.000017       1.177782      0.177926

In [27]:
import pandas as pd
import numpy as np
import torch

# 1. Evaluate selected config on test set (after tuning)
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

if 'best_cfg' not in globals():
    raise ValueError("best_cfg not found. Run grid-search cell first.")

best_lr = float(best_cfg['lr'])
best_wd = float(best_cfg['weight_decay'])

print("Đang đánh giá trên test với best config từ validation:")
print(f"  lr={best_lr:.1e}, weight_decay={best_wd:.1e}")
print(f"Số seed: {len(seeds)}")

# 2. Loop over seeds for robust test evaluation
for SEED in seeds:
    seed_everything(SEED)

    tarnet = Tarnet(
        input_dim=x_men_train_t.shape[1],
        epochs=epochs,
        learning_rate=best_lr,
        weight_decay=best_wd,
        use_ema=ema,
        ema_alpha=ema_alpha,
        patience=patience,
        shared_hidden=shared_hidden,
        outcome_hidden=outcome_hidden,
        outcome_dropout=outcome_dropout,
        shared_dropout=shared_dropout,
        early_stop_metric=early_stop_metric,
        early_stop_start_epoch=early_stop_start,
        activation=activation
    )

    tarnet.fit(train_loader, val_loader)

    # Test prediction
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = tarnet.predict(x_men_test_t_on_device)

    uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
    y_true = y_men_test_t.detach().cpu().numpy().flatten()
    t_true = t_men_test_t.detach().cpu().numpy().flatten()

    # ATE error
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()

    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  Done Seed {SEED}")

# 3. Aggregate final test metrics
df_results = pd.DataFrame(all_runs)

print("\n" + "=" * 85)
print(f"{'CHI TIẾT TỪNG SEED (TEST SET)':^85}")
print("=" * 85)
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format,
    'AUQC': '{:,.4f}'.format,
    'Lift': '{:,.4f}'.format,
    'KRCC': '{:,.4f}'.format,
    'ATE_Err': '{:,.4f}'.format
}))

mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("=" * 85)
print(f"{'KẾT QUẢ TRUNG BÌNH TEST (MEAN ± STD)':^85}")
print("-" * 85)
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")
print("=" * 85)

Đang đánh giá trên test với best config từ validation:
  lr=8.8e-05, weight_decay=1.0e-05
Số seed: 5
Locked random seed: 412312
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.35)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Loss: 0.0103 | Val Loss: 193.7392 | Val Qini: 0.5491 | EMA Qini: 0.5491 | Best EMA: 0.5491 ⭐ NEW BEST EMA
Epoch 2/150 | Loss: 468.6473 | Val Loss: 193.6911 | Val Qini: 0.6399 | EMA Qini: 0.5809 | Best EMA: 0.5809 ⭐ NEW BEST EMA
Epoch 3/150 | Loss: 0.0143 | Val Loss: 193.6376 | Val Qini: 0.7091 | EMA Qini: 0.6258 | Best EMA: 0.6258 ⭐ NEW BEST EMA
Epoch 4/150 | Loss: 0.0179 | Val Loss: 193.5815 | Val Qini: 0.8204 | EMA Qini: 0.6939 | Best EMA: 0.6939 ⭐ NEW BEST EMA
Epoch 5/150 | Loss: 0.0231 | Val Loss: 193.5197 | Val Qini: 0.8629 | EMA Qini: 0.7530 | Best EMA: 0.7530 ⭐ NEW BEST EMA
Epoch 6/150 | Loss: 0.0322 | Val Loss: 193.4518 | Val Qini: 0.8995 | EMA Qini: 0.8043 | Best EMA: 0.8043 ⭐ NEW BEST EMA
Epoch 7/150 | Loss: 0.0531 | Val Loss: 193.3782 | Val Qini: 0.9614 | EMA Qini: 0.8593 | Best EMA: 0.8593 ⭐ NEW BEST EMA
Epoch 8/150 | Loss: 0.0608 | Val Loss: 193.2995 | Val Qini: 1.0087 | EMA Qini: 0.9116 | Best EMA: 0.9116 ⭐ NEW BEST EMA
Epoch 9/150 | Loss: 0.1049 | Val Loss: 193.2159 | Val Qini: 1.0321 | EMA Qini: 0.9537 | Best EMA: 0.9537 ⭐ NEW BEST EMA
Epoch 10/150 | Loss: 0.1402 | Val Loss: 193.1320 | Val Qini: 1.0469 | EMA Qini: 0.9863 | Best EMA: 0.9863 ⭐ NEW BEST EMA
Epoch 11/150 | Loss: 0.1615 | Val Loss: 193.0468 | Val Qini: 1.0557 | EMA Qini: 1.0106 | Best EMA: 1.0106 ⭐ NEW BEST EMA
Epoch 12/150 | Loss: 0.2340 | Val Loss: 192.9613 | Val Qini: 1.0592 | EMA Qini: 1.0276 | Best EMA: 1.0276 ⭐ NEW BEST EMA
Epoch 13/150 | Loss: 0.3497 | Val Loss: 192.8799 | Val Qini: 1.0673 | EMA Qini: 1.0415 | Best EMA: 1.0415 ⭐ NEW BEST EMA
Epoch 14/150 | Loss: 0.5554 | Val Loss: 192.8104 | Val Qini: 1.0716 | EMA Qini: 1.0520 | Best EMA: 1.0520 ⭐ NEW BEST EMA
Epoch 15/150 | Loss: 0.5639 | Val Loss: 192.7550 | Val Qini: 1.0586 | EMA Qini: 1.0543 | Best EMA: 1.0543 ⭐ NEW BEST EMA
Epoch 16/150 | Loss: 0.8021 | Val Loss: 192.7122 | Val Qini: 1.0615 | EMA Qini: 1.0569 | Best EMA: 1.0569 ⭐ NEW BEST EMA
Epoch 17/150 | Loss: 0.7326 | Val Loss: 192.6887 | Val Qini: 1.0570 | EMA Qini: 1.0569 | Best EMA: 1.0569 ⭐ NEW BEST EMA
Epoch 18/150 | Loss: 0.9064 | Val Loss: 192.6853 | Val Qini: 1.0495 | EMA Qini: 1.0543 | Best EMA: 1.0569 (patience: 0/20)
Epoch 19/150 | Loss: 1.0694 | Val Loss: 192.6953 | Val Qini: 1.0327 | EMA Qini: 1.0468 | Best EMA: 1.0569 (patience: 0/20)
Epoch 20/150 | Loss: 1.1764 | Val Loss: 192.7136 | Val Qini: 1.0171 | EMA Qini: 1.0364 | Best EMA: 1.0569 (patience: 0/20)
Epoch 21/150 | Loss: 1.3607 | Val Loss: 192.7265 | Val Qini: 1.0119 | EMA Qini: 1.0278 | Best EMA: 1.0569 (patience: 0/20)
Epoch 22/150 | Loss: 1.3359 | Val Loss: 192.7168 | Val Qini: 0.9860 | EMA Qini: 1.0132 | Best EMA: 1.0569 (patience: 0/20)
Epoch 23/150 | Loss: 1.7677 | Val Loss: 192.7064 | Val Qini: 0.9574 | EMA Qini: 0.9937 | Best EMA: 1.0569 (patience: 0/20)
Epoch 24/150 | Loss: 1.0741 | Val Loss: 192.7029 | Val Qini: 0.9490 | EMA Qini: 0.9780 | Best EMA: 1.0569 (patience: 0/20)
Epoch 25/150 | Loss: 1.0113 | Val Loss: 192.7086 | Val Qini: 0.9250 | EMA Qini: 0.9595 | Best EMA: 1.0569 (patience: 0/20)
Epoch 26/150 | Loss: 1.0580 | Val Loss: 192.7110 | Val Qini: 0.9082 | EMA Qini: 0.9415 | Best EMA: 1.0569 (patience: 0/20)
Epoch 27/150 | Loss: 1.4109 | Val Loss: 192.7091 | Val Qini: 0.9033 | EMA Qini: 0.9281 | Best EMA: 1.0569 (patience: 0/20)
Epoch 28/150 | Loss: 1.4730 | Val Loss: 192.7170 | Val Qini: 0.8935 | EMA Qini: 0.9160 | Best EMA: 1.0569 (patience: 0/20)
Epoch 29/150 | Loss: 1.3991 | Val Loss: 192.7231 | Val Qini: 0.8736 | EMA Qini: 0.9012 | Best EMA: 1.0569 (patience: 0/20)
Epoch 30/150 | Loss: 1.3957 | Val Loss: 192.7233 | Val Qini: 0.8610 | EMA Qini: 0.8871 | Best EMA: 1.0569 (patience: 0/20)
Epoch 31/150 | Loss: 1.3462 | Val Loss: 192.7363 | Val Qini: 0.8415 | EMA Qini: 0.8712 | Best EMA: 1.0569 (patience: 1/20)
Epoch 32/150 | Loss: 1.2815 | Val Loss: 192.7493 | Val Qini: 0.8425 | EMA Qini: 0.8611 | Best EMA: 1.0569 (patience: 2/20)
Epoch 33/150 | Loss: 1.1749 | Val Loss: 192.7588 | Val Qini: 0.8207 | EMA Qini: 0.8470 | Best EMA: 1.0569 (patience: 3/20)
Epoch 34/150 | Loss: 1.2146 | Val Loss: 192.7634 | Val Qini: 0.8048 | EMA Qini: 0.8322 | Best EMA: 1.0569 (patience: 4/20)
Epoch 35/150 | Loss: 1.6176 | Val Loss: 192.7634 | Val Qini: 0.7968 | EMA Qini: 0.8198 | Best EMA: 1.0569 (patience: 5/20)
Epoch 36/150 | Loss: 1.9042 | Val Loss: 192.7674 | Val Qini: 0.7837 | EMA Qini: 0.8072 | Best EMA: 1.0569 (patience: 6/20)
Epoch 37/150 | Loss: 2.1273 | Val Loss: 192.7737 | Val Qini: 0.7669 | EMA Qini: 0.7931 | Best EMA: 1.0569 (patience: 7/20)
Epoch 38/150 | Loss: 1.2402 | Val Loss: 192.7792 | Val Qini: 0.7513 | EMA Qini: 0.7784 | Best EMA: 1.0569 (patience: 8/20)
Epoch 39/150 | Loss: 1.3899 | Val Loss: 192.7793 | Val Qini: 0.7106 | EMA Qini: 0.7547 | Best EMA: 1.0569 (patience: 9/20)
Epoch 40/150 | Loss: 1.5532 | Val Loss: 192.7882 | Val Qini: 0.6971 | EMA Qini: 0.7345 | Best EMA: 1.0569 (patience: 10/20)
Epoch 41/150 | Loss: 1.6286 | Val Loss: 192.8011 | Val Qini: 0.6957 | EMA Qini: 0.7209 | Best EMA: 1.0569 (patience: 11/20)
Epoch 42/150 | Loss: 2.2259 | Val Loss: 192.8161 | Val Qini: 0.6936 | EMA Qini: 0.7114 | Best EMA: 1.0569 (patience: 12/20)
Epoch 43/150 | Loss: 1.3946 | Val Loss: 192.8263 | Val Qini: 0.6908 | EMA Qini: 0.7042 | Best EMA: 1.0569 (patience: 13/20)
Epoch 44/150 | Loss: 1.1331 | Val Loss: 192.8314 | Val Qini: 0.6909 | EMA Qini: 0.6995 | Best EMA: 1.0569 (patience: 14/20)
Epoch 45/150 | Loss: 1.4920 | Val Loss: 192.8416 | Val Qini: 0.7058 | EMA Qini: 0.7017 | Best EMA: 1.0569 (patience: 15/20)
Epoch 46/150 | Loss: 1.4640 | Val Loss: 192.8487 | Val Qini: 0.7151 | EMA Qini: 0.7064 | Best EMA: 1.0569 (patience: 16/20)
Epoch 47/150 | Loss: 1.9820 | Val Loss: 192.8633 | Val Qini: 0.7232 | EMA Qini: 0.7123 | Best EMA: 1.0569 (patience: 17/20)
Epoch 48/150 | Loss: 1.4009 | Val Loss: 192.8807 | Val Qini: 0.7254 | EMA Qini: 0.7169 | Best EMA: 1.0569 (patience: 18/20)
Epoch 49/150 | Loss: 288.9691 | Val Loss: 192.9029 | Val Qini: 0.7355 | EMA Qini: 0.7234 | Best EMA: 1.0569 (patience: 19/20)
Epoch 50/150 | Loss: 2.1849 | Val Loss: 192.9489 | Val Qini: 0.7345 | EMA Qini: 0.7273 | Best EMA: 1.0569 (patience: 20/20)

🛑 Early stopping triggered at epoch 50!
   No improvement in EMA Qini for 20 epochs

✅ Training completed! Restored model to epoch 17
   Best EMA Qini: 1.0569
   Raw Qini at best EMA epoch: 1.0570
   Strategy: Selected epoch with highest smoothed (EMA) Qini
  Done Seed 412312
Locked random seed: 42
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.35)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Loss: 0.0073 | Val Loss: 193.6430 | Val Qini: 1.3019 | EMA Qini: 1.3019 | Best EMA: 1.3019 ⭐ NEW BEST EMA
Epoch 2/150 | Loss: 0.0104 | Val Loss: 193.6078 | Val Qini: 1.3390 | EMA Qini: 1.3149 | Best EMA: 1.3149 ⭐ NEW BEST EMA
Epoch 3/150 | Loss: 0.0132 | Val Loss: 193.5697 | Val Qini: 1.3797 | EMA Qini: 1.3376 | Best EMA: 1.3376 ⭐ NEW BEST EMA
Epoch 4/150 | Loss: 0.0181 | Val Loss: 193.5283 | Val Qini: 1.3710 | EMA Qini: 1.3493 | Best EMA: 1.3493 ⭐ NEW BEST EMA
Epoch 5/150 | Loss: 0.0257 | Val Loss: 193.4808 | Val Qini: 1.3566 | EMA Qini: 1.3518 | Best EMA: 1.3518 ⭐ NEW BEST EMA
Epoch 6/150 | Loss: 275.8134 | Val Loss: 193.4254 | Val Qini: 1.3623 | EMA Qini: 1.3555 | Best EMA: 1.3555 ⭐ NEW BEST EMA
Epoch 7/150 | Loss: 0.0541 | Val Loss: 193.3590 | Val Qini: 1.3354 | EMA Qini: 1.3485 | Best EMA: 1.3555 (patience: 0/20)
Epoch 8/150 | Loss: 0.0672 | Val Loss: 193.2886 | Val Qini: 1.2993 | EMA Qini: 1.3313 | Best EMA: 1.3555 (patience: 0/20)
Epoch 9/150 | Loss: 0.0902 | Val Loss: 193.2123 | Val Qini: 1.2900 | EMA Qini: 1.3168 | Best EMA: 1.3555 (patience: 0/20)
Epoch 10/150 | Loss: 0.1014 | Val Loss: 193.1325 | Val Qini: 1.2737 | EMA Qini: 1.3017 | Best EMA: 1.3555 (patience: 0/20)
Epoch 11/150 | Loss: 93.5415 | Val Loss: 193.0439 | Val Qini: 1.2762 | EMA Qini: 1.2928 | Best EMA: 1.3555 (patience: 0/20)
Epoch 12/150 | Loss: 0.2086 | Val Loss: 192.9424 | Val Qini: 1.2676 | EMA Qini: 1.2840 | Best EMA: 1.3555 (patience: 0/20)
Epoch 13/150 | Loss: 0.3702 | Val Loss: 192.8486 | Val Qini: 1.2479 | EMA Qini: 1.2714 | Best EMA: 1.3555 (patience: 0/20)
Epoch 14/150 | Loss: 0.5071 | Val Loss: 192.7656 | Val Qini: 1.2259 | EMA Qini: 1.2555 | Best EMA: 1.3555 (patience: 0/20)
Epoch 15/150 | Loss: 0.6280 | Val Loss: 192.7015 | Val Qini: 1.1925 | EMA Qini: 1.2334 | Best EMA: 1.3555 (patience: 0/20)
Epoch 16/150 | Loss: 0.8979 | Val Loss: 192.6568 | Val Qini: 1.1871 | EMA Qini: 1.2172 | Best EMA: 1.3555 (patience: 0/20)
Epoch 17/150 | Loss: 1.0757 | Val Loss: 192.6378 | Val Qini: 1.1845 | EMA Qini: 1.2058 | Best EMA: 1.3555 (patience: 0/20)
Epoch 18/150 | Loss: 0.9823 | Val Loss: 192.6322 | Val Qini: 1.1773 | EMA Qini: 1.1958 | Best EMA: 1.3555 (patience: 0/20)
Epoch 19/150 | Loss: 1.1619 | Val Loss: 192.6385 | Val Qini: 1.1665 | EMA Qini: 1.1856 | Best EMA: 1.3555 (patience: 0/20)
Epoch 20/150 | Loss: 1.3824 | Val Loss: 192.6382 | Val Qini: 1.1836 | EMA Qini: 1.1849 | Best EMA: 1.3555 (patience: 0/20)
Epoch 21/150 | Loss: 1.7222 | Val Loss: 192.6424 | Val Qini: 1.1902 | EMA Qini: 1.1867 | Best EMA: 1.3555 (patience: 0/20)
Epoch 22/150 | Loss: 1.9104 | Val Loss: 192.6433 | Val Qini: 1.1805 | EMA Qini: 1.1845 | Best EMA: 1.3555 (patience: 0/20)
Epoch 23/150 | Loss: 1.4124 | Val Loss: 192.6325 | Val Qini: 1.1838 | EMA Qini: 1.1843 | Best EMA: 1.3555 (patience: 0/20)
Epoch 24/150 | Loss: 1.6945 | Val Loss: 192.6304 | Val Qini: 1.1836 | EMA Qini: 1.1840 | Best EMA: 1.3555 (patience: 0/20)
Epoch 25/150 | Loss: 1.9549 | Val Loss: 192.6219 | Val Qini: 1.2021 | EMA Qini: 1.1903 | Best EMA: 1.3555 (patience: 0/20)
Epoch 26/150 | Loss: 1.2076 | Val Loss: 192.6196 | Val Qini: 1.1859 | EMA Qini: 1.1888 | Best EMA: 1.3555 (patience: 0/20)
Epoch 27/150 | Loss: 1.0860 | Val Loss: 192.6211 | Val Qini: 1.1779 | EMA Qini: 1.1850 | Best EMA: 1.3555 (patience: 0/20)
Epoch 28/150 | Loss: 1.1868 | Val Loss: 192.6176 | Val Qini: 1.1632 | EMA Qini: 1.1774 | Best EMA: 1.3555 (patience: 0/20)
Epoch 29/150 | Loss: 2325.1997 | Val Loss: 192.6152 | Val Qini: 1.1690 | EMA Qini: 1.1744 | Best EMA: 1.3555 (patience: 0/20)
Epoch 30/150 | Loss: 1.5140 | Val Loss: 192.6290 | Val Qini: 1.1680 | EMA Qini: 1.1722 | Best EMA: 1.3555 (patience: 0/20)
Epoch 31/150 | Loss: 1.7564 | Val Loss: 192.6387 | Val Qini: 1.1663 | EMA Qini: 1.1701 | Best EMA: 1.3555 (patience: 1/20)
Epoch 32/150 | Loss: 949.6469 | Val Loss: 192.6386 | Val Qini: 1.1448 | EMA Qini: 1.1613 | Best EMA: 1.3555 (patience: 2/20)
Epoch 33/150 | Loss: 1.7437 | Val Loss: 192.6492 | Val Qini: 1.1411 | EMA Qini: 1.1542 | Best EMA: 1.3555 (patience: 3/20)
Epoch 34/150 | Loss: 1.4323 | Val Loss: 192.6493 | Val Qini: 1.1267 | EMA Qini: 1.1446 | Best EMA: 1.3555 (patience: 4/20)
Epoch 35/150 | Loss: 1.5683 | Val Loss: 192.6502 | Val Qini: 1.0988 | EMA Qini: 1.1286 | Best EMA: 1.3555 (patience: 5/20)
Epoch 36/150 | Loss: 1.7128 | Val Loss: 192.6491 | Val Qini: 1.0695 | EMA Qini: 1.1079 | Best EMA: 1.3555 (patience: 6/20)
Epoch 37/150 | Loss: 1.5855 | Val Loss: 192.6573 | Val Qini: 1.0639 | EMA Qini: 1.0925 | Best EMA: 1.3555 (patience: 7/20)
Epoch 38/150 | Loss: 1.3955 | Val Loss: 192.6618 | Val Qini: 1.0627 | EMA Qini: 1.0821 | Best EMA: 1.3555 (patience: 8/20)
Epoch 39/150 | Loss: 1.6973 | Val Loss: 192.6616 | Val Qini: 1.0532 | EMA Qini: 1.0720 | Best EMA: 1.3555 (patience: 9/20)
Epoch 40/150 | Loss: 1.8241 | Val Loss: 192.6679 | Val Qini: 1.0525 | EMA Qini: 1.0652 | Best EMA: 1.3555 (patience: 10/20)
Epoch 41/150 | Loss: 2.1029 | Val Loss: 192.6787 | Val Qini: 1.0583 | EMA Qini: 1.0628 | Best EMA: 1.3555 (patience: 11/20)
Epoch 42/150 | Loss: 2.3980 | Val Loss: 192.6757 | Val Qini: 1.0612 | EMA Qini: 1.0622 | Best EMA: 1.3555 (patience: 12/20)
Epoch 43/150 | Loss: 1.8409 | Val Loss: 192.6779 | Val Qini: 1.0451 | EMA Qini: 1.0562 | Best EMA: 1.3555 (patience: 13/20)
Epoch 44/150 | Loss: 2293.3447 | Val Loss: 192.6770 | Val Qini: 1.0610 | EMA Qini: 1.0579 | Best EMA: 1.3555 (patience: 14/20)
Epoch 45/150 | Loss: 291.8775 | Val Loss: 192.6892 | Val Qini: 1.0912 | EMA Qini: 1.0695 | Best EMA: 1.3555 (patience: 15/20)
Epoch 46/150 | Loss: 1.3012 | Val Loss: 192.7039 | Val Qini: 1.0921 | EMA Qini: 1.0774 | Best EMA: 1.3555 (patience: 16/20)
Epoch 47/150 | Loss: 1.1243 | Val Loss: 192.7079 | Val Qini: 1.0874 | EMA Qini: 1.0809 | Best EMA: 1.3555 (patience: 17/20)
Epoch 48/150 | Loss: 188.2429 | Val Loss: 192.7130 | Val Qini: 1.0925 | EMA Qini: 1.0850 | Best EMA: 1.3555 (patience: 18/20)
Epoch 49/150 | Loss: 1.7861 | Val Loss: 192.7321 | Val Qini: 1.0940 | EMA Qini: 1.0881 | Best EMA: 1.3555 (patience: 19/20)
Epoch 50/150 | Loss: 1.1091 | Val Loss: 192.7517 | Val Qini: 1.1093 | EMA Qini: 1.0955 | Best EMA: 1.3555 (patience: 20/20)

🛑 Early stopping triggered at epoch 50!
   No improvement in EMA Qini for 20 epochs

✅ Training completed! Restored model to epoch 6
   Best EMA Qini: 1.3555
   Raw Qini at best EMA epoch: 1.3623
   Strategy: Selected epoch with highest smoothed (EMA) Qini
  Done Seed 42
Locked random seed: 1874
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.35)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Loss: 0.0121 | Val Loss: 193.7266 | Val Qini: 1.0060 | EMA Qini: 1.0060 | Best EMA: 1.0060 ⭐ NEW BEST EMA
Epoch 2/150 | Loss: 0.0116 | Val Loss: 193.6893 | Val Qini: 1.0831 | EMA Qini: 1.0330 | Best EMA: 1.0330 ⭐ NEW BEST EMA
Epoch 3/150 | Loss: 0.0132 | Val Loss: 193.6533 | Val Qini: 1.1697 | EMA Qini: 1.0808 | Best EMA: 1.0808 ⭐ NEW BEST EMA
Epoch 4/150 | Loss: 0.0158 | Val Loss: 193.6168 | Val Qini: 1.2090 | EMA Qini: 1.1257 | Best EMA: 1.1257 ⭐ NEW BEST EMA
Epoch 5/150 | Loss: 0.0187 | Val Loss: 193.5770 | Val Qini: 1.2467 | EMA Qini: 1.1680 | Best EMA: 1.1680 ⭐ NEW BEST EMA
Epoch 6/150 | Loss: 0.0221 | Val Loss: 193.5332 | Val Qini: 1.2947 | EMA Qini: 1.2124 | Best EMA: 1.2124 ⭐ NEW BEST EMA
Epoch 7/150 | Loss: 0.0278 | Val Loss: 193.4844 | Val Qini: 1.2662 | EMA Qini: 1.2312 | Best EMA: 1.2312 ⭐ NEW BEST EMA
Epoch 8/150 | Loss: 0.0425 | Val Loss: 193.4295 | Val Qini: 1.1854 | EMA Qini: 1.2152 | Best EMA: 1.2312 (patience: 0/20)
Epoch 9/150 | Loss: 0.0540 | Val Loss: 193.3691 | Val Qini: 1.1403 | EMA Qini: 1.1890 | Best EMA: 1.2312 (patience: 0/20)
Epoch 10/150 | Loss: 1290.3397 | Val Loss: 193.3006 | Val Qini: 1.0946 | EMA Qini: 1.1559 | Best EMA: 1.2312 (patience: 0/20)
Epoch 11/150 | Loss: 0.1074 | Val Loss: 193.2188 | Val Qini: 1.0424 | EMA Qini: 1.1162 | Best EMA: 1.2312 (patience: 0/20)
Epoch 12/150 | Loss: 0.1594 | Val Loss: 193.1384 | Val Qini: 0.9778 | EMA Qini: 1.0678 | Best EMA: 1.2312 (patience: 0/20)
Epoch 13/150 | Loss: 0.2083 | Val Loss: 193.0595 | Val Qini: 0.9311 | EMA Qini: 1.0200 | Best EMA: 1.2312 (patience: 0/20)
Epoch 14/150 | Loss: 0.2392 | Val Loss: 192.9839 | Val Qini: 0.9054 | EMA Qini: 0.9798 | Best EMA: 1.2312 (patience: 0/20)
Epoch 15/150 | Loss: 0.4095 | Val Loss: 192.9105 | Val Qini: 0.8885 | EMA Qini: 0.9479 | Best EMA: 1.2312 (patience: 0/20)
Epoch 16/150 | Loss: 0.3829 | Val Loss: 192.8419 | Val Qini: 0.8846 | EMA Qini: 0.9257 | Best EMA: 1.2312 (patience: 0/20)
Epoch 17/150 | Loss: 0.5537 | Val Loss: 192.7819 | Val Qini: 0.8880 | EMA Qini: 0.9125 | Best EMA: 1.2312 (patience: 0/20)
Epoch 18/150 | Loss: 0.8458 | Val Loss: 192.7345 | Val Qini: 0.8800 | EMA Qini: 0.9011 | Best EMA: 1.2312 (patience: 0/20)
Epoch 19/150 | Loss: 1.0589 | Val Loss: 192.7070 | Val Qini: 0.8736 | EMA Qini: 0.8915 | Best EMA: 1.2312 (patience: 0/20)
Epoch 20/150 | Loss: 1.0885 | Val Loss: 192.6942 | Val Qini: 0.8726 | EMA Qini: 0.8849 | Best EMA: 1.2312 (patience: 0/20)
Epoch 21/150 | Loss: 1.2239 | Val Loss: 192.6886 | Val Qini: 0.8610 | EMA Qini: 0.8765 | Best EMA: 1.2312 (patience: 0/20)
Epoch 22/150 | Loss: 1.3542 | Val Loss: 192.6827 | Val Qini: 0.8706 | EMA Qini: 0.8745 | Best EMA: 1.2312 (patience: 0/20)
Epoch 23/150 | Loss: 1.2259 | Val Loss: 192.6800 | Val Qini: 0.8505 | EMA Qini: 0.8661 | Best EMA: 1.2312 (patience: 0/20)
Epoch 24/150 | Loss: 1.5403 | Val Loss: 192.6838 | Val Qini: 0.8349 | EMA Qini: 0.8552 | Best EMA: 1.2312 (patience: 0/20)
Epoch 25/150 | Loss: 1.5853 | Val Loss: 192.6786 | Val Qini: 0.8625 | EMA Qini: 0.8577 | Best EMA: 1.2312 (patience: 0/20)
Epoch 26/150 | Loss: 1.8885 | Val Loss: 192.6727 | Val Qini: 0.8740 | EMA Qini: 0.8634 | Best EMA: 1.2312 (patience: 0/20)
Epoch 27/150 | Loss: 1.3710 | Val Loss: 192.6630 | Val Qini: 0.9037 | EMA Qini: 0.8775 | Best EMA: 1.2312 (patience: 0/20)
Epoch 28/150 | Loss: 1.1787 | Val Loss: 192.6510 | Val Qini: 0.9377 | EMA Qini: 0.8986 | Best EMA: 1.2312 (patience: 0/20)
Epoch 29/150 | Loss: 1.2920 | Val Loss: 192.6430 | Val Qini: 0.9531 | EMA Qini: 0.9177 | Best EMA: 1.2312 (patience: 0/20)
Epoch 30/150 | Loss: 0.9397 | Val Loss: 192.6402 | Val Qini: 0.9622 | EMA Qini: 0.9332 | Best EMA: 1.2312 (patience: 0/20)
Epoch 31/150 | Loss: 5388.7388 | Val Loss: 192.6348 | Val Qini: 0.9521 | EMA Qini: 0.9398 | Best EMA: 1.2312 (patience: 1/20)
Epoch 32/150 | Loss: 1.2372 | Val Loss: 192.6406 | Val Qini: 0.9491 | EMA Qini: 0.9431 | Best EMA: 1.2312 (patience: 2/20)
Epoch 33/150 | Loss: 1.3138 | Val Loss: 192.6467 | Val Qini: 0.9577 | EMA Qini: 0.9482 | Best EMA: 1.2312 (patience: 3/20)
Epoch 34/150 | Loss: 1.7784 | Val Loss: 192.6430 | Val Qini: 0.9515 | EMA Qini: 0.9494 | Best EMA: 1.2312 (patience: 4/20)
Epoch 35/150 | Loss: 1.3676 | Val Loss: 192.6352 | Val Qini: 0.9570 | EMA Qini: 0.9521 | Best EMA: 1.2312 (patience: 5/20)
Epoch 36/150 | Loss: 1.5252 | Val Loss: 192.6303 | Val Qini: 0.9687 | EMA Qini: 0.9579 | Best EMA: 1.2312 (patience: 6/20)
Epoch 37/150 | Loss: 1.1953 | Val Loss: 192.6336 | Val Qini: 0.9953 | EMA Qini: 0.9710 | Best EMA: 1.2312 (patience: 7/20)
Epoch 38/150 | Loss: 2100.6814 | Val Loss: 192.6414 | Val Qini: 0.9935 | EMA Qini: 0.9788 | Best EMA: 1.2312 (patience: 8/20)
Epoch 39/150 | Loss: 1.6352 | Val Loss: 192.6541 | Val Qini: 0.9920 | EMA Qini: 0.9835 | Best EMA: 1.2312 (patience: 9/20)
Epoch 40/150 | Loss: 1.7412 | Val Loss: 192.6638 | Val Qini: 0.9963 | EMA Qini: 0.9880 | Best EMA: 1.2312 (patience: 10/20)
Epoch 41/150 | Loss: 1.8787 | Val Loss: 192.6716 | Val Qini: 1.0037 | EMA Qini: 0.9935 | Best EMA: 1.2312 (patience: 11/20)
Epoch 42/150 | Loss: 1.6462 | Val Loss: 192.6652 | Val Qini: 1.0015 | EMA Qini: 0.9963 | Best EMA: 1.2312 (patience: 12/20)
Epoch 43/150 | Loss: 1.8195 | Val Loss: 192.6589 | Val Qini: 1.0109 | EMA Qini: 1.0014 | Best EMA: 1.2312 (patience: 13/20)
Epoch 44/150 | Loss: 1.2651 | Val Loss: 192.6618 | Val Qini: 1.0092 | EMA Qini: 1.0041 | Best EMA: 1.2312 (patience: 14/20)
Epoch 45/150 | Loss: 1.6331 | Val Loss: 192.6603 | Val Qini: 0.9971 | EMA Qini: 1.0016 | Best EMA: 1.2312 (patience: 15/20)
Epoch 46/150 | Loss: 3236.0874 | Val Loss: 192.6659 | Val Qini: 1.0110 | EMA Qini: 1.0049 | Best EMA: 1.2312 (patience: 16/20)
Epoch 47/150 | Loss: 1.4693 | Val Loss: 192.6746 | Val Qini: 1.0172 | EMA Qini: 1.0092 | Best EMA: 1.2312 (patience: 17/20)
Epoch 48/150 | Loss: 1.5944 | Val Loss: 192.6848 | Val Qini: 1.0162 | EMA Qini: 1.0117 | Best EMA: 1.2312 (patience: 18/20)
Epoch 49/150 | Loss: 1.7799 | Val Loss: 192.6872 | Val Qini: 1.0101 | EMA Qini: 1.0111 | Best EMA: 1.2312 (patience: 19/20)
Epoch 50/150 | Loss: 1.0452 | Val Loss: 192.6921 | Val Qini: 1.0081 | EMA Qini: 1.0101 | Best EMA: 1.2312 (patience: 20/20)

🛑 Early stopping triggered at epoch 50!
   No improvement in EMA Qini for 20 epochs

✅ Training completed! Restored model to epoch 7
   Best EMA Qini: 1.2312
   Raw Qini at best EMA epoch: 1.2662