Import libraries

In [38]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from dragonnet import Dragonnet
import sys
from pathlib import Path
project_root = Path("/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [39]:
%time train_df = pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Women/train_women.csv")
%time test_df =  pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Women/test_women.csv")
%time val_df = pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Women/val_women.csv")

CPU times: user 24.4 ms, sys: 8.02 ms, total: 32.5 ms
Wall time: 32 ms
CPU times: user 11.5 ms, sys: 4.01 ms, total: 15.5 ms
Wall time: 15.4 ms
CPU times: user 4.14 ms, sys: 1 ms, total: 5.14 ms
Wall time: 5.1 ms

In [40]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['conversion']
treatment_feature = ['treatment']

In [41]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [42]:
print('X_train[:10]', X_train[:1].astype(float))

X_train[:10] [[-0.78953321  1.6460815   1.41745802 -1.11692492  0.91314538  1.07643872
   0.9950542  -0.36894675 -0.88924565  1.13133938]]

In [43]:
print('y_train[:10]', y_train[:1].astype(float))

y_train[:10] [[0.]]

In [44]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25615, 10]); y=torch.Size([25615, 1]); t=torch.Size([25615, 1])
Shape of val: x=torch.Size([4270, 10]); y=torch.Size([4270, 1]); t=torch.Size([4270, 1])
Shape of test: x=torch.Size([12808, 10]); y=torch.Size([12808, 1]); t=torch.Size([12808, 1])

In [45]:
epochs = 150
lr = 5.5e-5
wd = 1e-5
alpha = 1
beta= 1
early_stop_metric = "qini"
ema = True
ema_alpha = 0.15
patience = 20
shared_dropout = 0
outcome_dropout = 0.0
shared_hidden = 200
outcome_hidden = 100
early_stop_start = 30
activation = torch.nn.ReLU
print (f" epochs = {epochs}")
print (f" learning rate = {lr}")
print (f" weight decay = {wd}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" shared hidden = {shared_hidden}")
print (f" outcome hidden = {outcome_hidden}")
print (f" early stop start = {early_stop_start}")
print (f" activation = {activation}")

 epochs = 150
 learning rate = 5.5e-05
 weight decay = 1e-05
 early stop = qini
 use ema = True
 ema alpha = 0.15
 patience = 20
 shared hidden = 200
 outcome hidden = 100
 early stop start = 30
 activation = <class 'torch.nn.modules.activation.ReLU'>

In [46]:
import pandas as pd
import numpy as np
import torch
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 5e-5, 5e-4, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-4, log=True)
    grid_alpha = trial.suggest_categorical("alpha", [0.1, 0.5, 1.0])
    grid_beta = trial.suggest_categorical("beta", [0.1, 0.5, 1.0])

    val_scores = []
    for SEED in seeds:
        seed_everything(SEED)

        dragonnet = Dragonnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            alpha=grid_alpha,
            beta=grid_beta,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=shared_hidden,
            outcome_hidden=outcome_hidden,
            outcome_droupout=outcome_dropout,
            shared_dropout=shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
            activation=activation
        )

        # Silence Dragonnet epoch logs
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            dragonnet.fit(train_loader, val_loader)

        x_val_device = x_men_val_t.to(device)
        y0_val_p, y1_val_p, _, _ = dragonnet.predict(x_val_device)
        uplift_val = (y1_val_p - y0_val_p).detach().cpu().numpy().flatten()
        y_val_true_np = y_men_val_t.detach().cpu().numpy().flatten()
        t_val_true_np = t_men_val_t.detach().cpu().numpy().flatten()

        current_val_auqc = auqc(y_val_true_np, t_val_true_np, uplift_val, bins=100, plot=False)
        val_scores.append(current_val_auqc)

    mean_val_auqc = float(np.mean(val_scores))
    std_val_auqc = float(np.std(val_scores, ddof=1)) if len(val_scores) > 1 else 0.0
    trial.set_user_attr("std_Val_AUQC", std_val_auqc)
    return mean_val_auqc

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

# 2. Persist search results in notebook variables
trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": t.params["lr"],
        "weight_decay": t.params["weight_decay"],
        "alpha": t.params["alpha"],
        "beta": t.params["beta"],
        "mean_Val_AUQC": float(t.value),
        "std_Val_AUQC": float(t.user_attrs.get("std_Val_AUQC", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_Val_AUQC", ascending=False).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "alpha": float(best_params["alpha"]),
    "beta": float(best_params["beta"]),
    "mean_Val_AUQC": float(study.best_value),
    "std_Val_AUQC": float(study.best_trial.user_attrs.get("std_Val_AUQC", np.nan))
})

  0%|          | 0/50 [00:00<?, ?it/s]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 0. Best value: 0.856193:   2%|▏         | 1/50 [00:49<40:31, 49.63s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 1. Best value: 0.856406:   4%|▍         | 2/50 [01:36<38:33, 48.19s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 0.863687:   6%|▌         | 3/50 [02:23<37:13, 47.52s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 0.863687:   8%|▊         | 4/50 [03:09<36:05, 47.07s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 0.863687:  10%|█         | 5/50 [04:06<37:53, 50.52s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 0.863687:  12%|█▏        | 6/50 [04:59<37:38, 51.33s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 0.863687:  14%|█▍        | 7/50 [05:47<35:56, 50.16s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 0.863687:  16%|█▌        | 8/50 [06:34<34:24, 49.16s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 0.863687:  18%|█▊        | 9/50 [07:21<33:07, 48.47s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 0.863687:  20%|██        | 10/50 [08:10<32:31, 48.79s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 0.863687:  22%|██▏       | 11/50 [09:03<32:25, 49.88s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 0.863687:  24%|██▍       | 12/50 [09:52<31:31, 49.77s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 12. Best value: 0.867887:  26%|██▌       | 13/50 [10:40<30:25, 49.34s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 12. Best value: 0.867887:  28%|██▊       | 14/50 [11:34<30:26, 50.74s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 12. Best value: 0.867887:  30%|███       | 15/50 [12:42<32:36, 55.91s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 12. Best value: 0.867887:  32%|███▏      | 16/50 [13:32<30:36, 54.00s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 12. Best value: 0.867887:  34%|███▍      | 17/50 [14:21<28:56, 52.63s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 12. Best value: 0.867887:  36%|███▌      | 18/50 [15:11<27:36, 51.76s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 12. Best value: 0.867887:  38%|███▊      | 19/50 [16:05<27:05, 52.43s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 19. Best value: 0.868733:  40%|████      | 20/50 [16:55<25:52, 51.74s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 19. Best value: 0.868733:  42%|████▏     | 21/50 [17:44<24:38, 50.97s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 19. Best value: 0.868733:  44%|████▍     | 22/50 [18:34<23:33, 50.47s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  46%|████▌     | 23/50 [19:23<22:35, 50.22s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  48%|████▊     | 24/50 [20:14<21:51, 50.44s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  50%|█████     | 25/50 [21:04<20:59, 50.38s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  52%|█████▏    | 26/50 [21:57<20:23, 50.97s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  54%|█████▍    | 27/50 [22:46<19:22, 50.52s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  56%|█████▌    | 28/50 [23:40<18:55, 51.61s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  58%|█████▊    | 29/50 [24:30<17:49, 50.95s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  60%|██████    | 30/50 [25:19<16:50, 50.53s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  62%|██████▏   | 31/50 [26:10<16:01, 50.62s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  64%|██████▍   | 32/50 [27:01<15:10, 50.59s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  66%|██████▌   | 33/50 [27:51<14:16, 50.38s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  68%|██████▊   | 34/50 [28:41<13:24, 50.26s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  70%|███████   | 35/50 [29:31<12:34, 50.29s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  72%|███████▏  | 36/50 [30:23<11:53, 50.94s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  74%|███████▍  | 37/50 [31:14<10:59, 50.74s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  76%|███████▌  | 38/50 [32:04<10:08, 50.75s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  78%|███████▊  | 39/50 [32:55<09:19, 50.83s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  80%|████████  | 40/50 [33:45<08:24, 50.49s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  82%|████████▏ | 41/50 [34:34<07:28, 49.85s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  84%|████████▍ | 42/50 [35:23<06:37, 49.69s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  86%|████████▌ | 43/50 [36:12<05:46, 49.53s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  88%|████████▊ | 44/50 [37:01<04:56, 49.48s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  90%|█████████ | 45/50 [37:51<04:07, 49.45s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  92%|█████████▏| 46/50 [38:46<03:24, 51.08s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  94%|█████████▍| 47/50 [39:36<02:32, 50.99s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  96%|█████████▌| 48/50 [40:27<01:41, 50.72s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 22. Best value: 0.870023:  98%|█████████▊| 49/50 [41:17<00:50, 50.66s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 49. Best value: 0.87023: 100%|██████████| 50/50 [42:09<00:00, 50.58s/it]

In [50]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_AUQC: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 49
Best mean_Val_AUQC: 0.870230
Best params: {'lr': 0.00024260106038418808, 'weight_decay': 1.539684304296834e-05, 'alpha': 0.5, 'beta': 1.0}

Best config table:

         lr  weight_decay  alpha  beta  mean_Val_AUQC  std_Val_AUQC
0  0.000243      0.000015    0.5   1.0        0.87023      0.070152

Top 10 trials:

   trial        lr  weight_decay  alpha  beta  mean_Val_AUQC  std_Val_AUQC
0     49  0.000243      0.000015    0.5   1.0       0.870230      0.070152
1     22  0.000276      0.000015    0.1   1.0       0.870023      0.069164
2     43  0.000277      0.000019    0.1   1.0       0.869389      0.069659
3     19  0.000246      0.000015    0.1   1.0       0.868733      0.069016
4     12  0.000256      0.000059    0.1   1.0       0.867887      0.073311
5     41  0.000309      0.000012    0.1   1.0       0.866218      0.074604
6     32  0.000260      0.000014    0.1   1.0       0.866048      0.063918
7     33  0.000305      0.000012    0.1   1.0       0.865899      0.073997
8     31  0.000257      0.000014    0.1   1.0       0.865247      0.064728
9     24  0.000257      0.000016    0.1   1.0       0.865159      0.064300

Per-seed test results:

     Seed      AUUC      AUQC      Lift      KRCC   ATE_Err
0  412312  0.848680  0.854274  0.006596  0.094056  0.015931
1      42  0.561338  0.557980  0.003907  0.038982  0.017221
2    1874  0.642258  0.640964  0.005246  0.113203  0.574409
3  902745  0.744389  0.740547  0.005710  0.118488  0.131346
4       1  0.900796  0.906985  0.006835  0.197447  0.017788

Test metrics mean ± std:

          AUUC      AUQC      Lift      KRCC   ATE_Err
mean  0.739492  0.740150  0.005659  0.112435  0.151339
std   0.140675  0.144812  0.001173  0.057003  0.241633

In [51]:
import pandas as pd
import numpy as np
import torch

# 1. Evaluate selected config on test set (after tuning)
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

if 'best_cfg' not in globals():
    raise ValueError("best_cfg not found. Run grid-search cell first.")

best_lr = float(best_cfg['lr'])
best_wd = float(best_cfg['weight_decay'])
best_alpha = float(best_cfg['alpha'])
best_beta = float(best_cfg['beta'])

print("Đang đánh giá trên test với best config từ validation:")
print(f"  lr={best_lr:.1e}, weight_decay={best_wd:.1e}, alpha={best_alpha:.1f}, beta={best_beta:.1f}")
print(f"Số seed: {len(seeds)}")

# 2. Loop over seeds for robust test evaluation
for SEED in seeds:
    seed_everything(SEED)

    dragonnet = Dragonnet(
        input_dim=x_men_train_t.shape[1],
        epochs=epochs,
        learning_rate=best_lr,
        alpha=best_alpha,
        beta=best_beta,
        weight_decay=best_wd,
        use_ema=ema,
        ema_alpha=ema_alpha,
        patience=patience,
        shared_hidden=shared_hidden,
        outcome_hidden=outcome_hidden,
        outcome_droupout=outcome_dropout,
        shared_dropout=shared_dropout,
        early_stop_metric=early_stop_metric,
        early_stop_start_epoch=early_stop_start,
        activation=activation
    )

    dragonnet.fit(train_loader, val_loader)

    # Test prediction
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred, _, _ = dragonnet.predict(x_men_test_t_on_device)

    uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
    y_true = y_men_test_t.detach().cpu().numpy().flatten()
    t_true = t_men_test_t.detach().cpu().numpy().flatten()

    # ATE error
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()

    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  Done Seed {SEED}")

# 3. Aggregate final test metrics
df_results = pd.DataFrame(all_runs)

print("\n" + "=" * 85)
print(f"{'CHI TIẾT TỪNG SEED (TEST SET)':^85}")
print("=" * 85)
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format,
    'AUQC': '{:,.4f}'.format,
    'Lift': '{:,.4f}'.format,
    'KRCC': '{:,.4f}'.format,
    'ATE_Err': '{:,.4f}'.format
}))

mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("=" * 85)
print(f"{'KẾT QUẢ TRUNG BÌNH TEST (MEAN ± STD)':^85}")
print("-" * 85)
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")
print("=" * 85)

Đang đánh giá trên test với best config từ validation:
  lr=2.4e-04, weight_decay=1.5e-05, alpha=0.5, beta=1.0
Số seed: 5
Locked random seed: 412312
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/150 | Base Loss: 1.6785 | Tarreg Loss: 1.852010 | Total Loss: 3.5305 | Val Loss: 1.6733 | Raw Qini: 0.8176 | EMA Trend: 0.8176 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Base Loss: 1.6868 | Tarreg Loss: 1.403322 | Total Loss: 3.0901 | Val Loss: 1.6429 | Raw Qini: 0.6735 | EMA Trend: 0.7960 | (patience: 1/20)
Epoch 3/150 | Base Loss: 1.6107 | Tarreg Loss: 1.788515 | Total Loss: 3.3992 | Val Loss: 1.6071 | Raw Qini: 0.6526 | EMA Trend: 0.7745 | (patience: 2/20)
Epoch 4/150 | Base Loss: 1.5549 | Tarreg Loss: 1.835159 | Total Loss: 3.3900 | Val Loss: 1.5586 | Raw Qini: 0.5974 | EMA Trend: 0.7479 | (patience: 3/20)
Epoch 5/150 | Base Loss: 1.5143 | Tarreg Loss: 1.517481 | Total Loss: 3.0318 | Val Loss: 1.4859 | Raw Qini: 0.7137 | EMA Trend: 0.7428 | (patience: 4/20)
Epoch 6/150 | Base Loss: 1.3570 | Tarreg Loss: 1.672257 | Total Loss: 3.0292 | Val Loss: 1.3795 | Raw Qini: 0.7605 | EMA Trend: 0.7455 | ✓ above trend but not peak (patience: 5/20)
Epoch 7/150 | Base Loss: 1.2477 | Tarreg Loss: 1.564575 | Total Loss: 2.8123 | Val Loss: 1.2174 | Raw Qini: 0.7879 | EMA Trend: 0.7518 | ✓ above trend but not peak (patience: 6/20)
Epoch 8/150 | Base Loss: 1.1664 | Tarreg Loss: 1.551132 | Total Loss: 2.7176 | Val Loss: 0.9984 | Raw Qini: 0.7519 | EMA Trend: 0.7518 | ✓ above trend but not peak (patience: 7/20)
Epoch 9/150 | Base Loss: 0.7889 | Tarreg Loss: 1.499820 | Total Loss: 2.2888 | Val Loss: 0.7598 | Raw Qini: 0.4281 | EMA Trend: 0.7033 | (patience: 8/20)
Epoch 10/150 | Base Loss: 0.6044 | Tarreg Loss: 1.484662 | Total Loss: 2.0890 | Val Loss: 0.5832 | Raw Qini: 0.3396 | EMA Trend: 0.6487 | (patience: 9/20)
Epoch 11/150 | Base Loss: 0.7251 | Tarreg Loss: 1.578258 | Total Loss: 2.3033 | Val Loss: 0.5062 | Raw Qini: 0.2952 | EMA Trend: 0.5957 | (patience: 10/20)
Epoch 12/150 | Base Loss: 0.4214 | Tarreg Loss: 1.395596 | Total Loss: 1.8170 | Val Loss: 0.4873 | Raw Qini: 0.2909 | EMA Trend: 0.5500 | (patience: 11/20)
Epoch 13/150 | Base Loss: 0.4149 | Tarreg Loss: 1.406893 | Total Loss: 1.8218 | Val Loss: 0.4885 | Raw Qini: 0.2891 | EMA Trend: 0.5109 | (patience: 12/20)
Epoch 14/150 | Base Loss: 0.4363 | Tarreg Loss: 1.399407 | Total Loss: 1.8357 | Val Loss: 0.4994 | Raw Qini: 0.2907 | EMA Trend: 0.4778 | (patience: 13/20)
Epoch 15/150 | Base Loss: 0.4582 | Tarreg Loss: 1.374822 | Total Loss: 1.8331 | Val Loss: 0.5140 | Raw Qini: 0.2934 | EMA Trend: 0.4502 | (patience: 14/20)
Epoch 16/150 | Base Loss: 0.4578 | Tarreg Loss: 1.324414 | Total Loss: 1.7822 | Val Loss: 0.5345 | Raw Qini: 0.2878 | EMA Trend: 0.4258 | (patience: 15/20)
Epoch 17/150 | Base Loss: 0.4963 | Tarreg Loss: 1.349118 | Total Loss: 1.8454 | Val Loss: 0.5531 | Raw Qini: 0.2881 | EMA Trend: 0.4052 | (patience: 16/20)
Epoch 18/150 | Base Loss: 0.4969 | Tarreg Loss: 1.258596 | Total Loss: 1.7555 | Val Loss: 0.5576 | Raw Qini: 0.2854 | EMA Trend: 0.3872 | (patience: 17/20)
Epoch 19/150 | Base Loss: 0.7777 | Tarreg Loss: 1.484754 | Total Loss: 2.2625 | Val Loss: 0.5642 | Raw Qini: 0.2811 | EMA Trend: 0.3713 | (patience: 18/20)
Epoch 20/150 | Base Loss: 0.5376 | Tarreg Loss: 1.289563 | Total Loss: 1.8271 | Val Loss: 0.5836 | Raw Qini: 0.2750 | EMA Trend: 0.3568 | (patience: 19/20)
Epoch 21/150 | Base Loss: 0.5389 | Tarreg Loss: 1.184417 | Total Loss: 1.7233 | Val Loss: 0.5766 | Raw Qini: 0.2684 | EMA Trend: 0.3436 | (patience: 20/20)
Epoch 22/150 | Base Loss: 0.5026 | Tarreg Loss: 1.235608 | Total Loss: 1.7382 | Val Loss: 0.5655 | Raw Qini: 0.2685 | EMA Trend: 0.3323 | (patience: 21/20)
Epoch 23/150 | Base Loss: 0.5111 | Tarreg Loss: 1.227835 | Total Loss: 1.7390 | Val Loss: 0.5568 | Raw Qini: 0.2582 | EMA Trend: 0.3212 | (patience: 22/20)
Epoch 24/150 | Base Loss: 0.4891 | Tarreg Loss: 1.261566 | Total Loss: 1.7506 | Val Loss: 0.5417 | Raw Qini: 0.2562 | EMA Trend: 0.3114 | (patience: 23/20)
Epoch 25/150 | Base Loss: 0.4648 | Tarreg Loss: 1.221591 | Total Loss: 1.6864 | Val Loss: 0.5296 | Raw Qini: 0.2590 | EMA Trend: 0.3036 | (patience: 24/20)
Epoch 26/150 | Base Loss: 0.6796 | Tarreg Loss: 1.435976 | Total Loss: 2.1156 | Val Loss: 0.5298 | Raw Qini: 0.2517 | EMA Trend: 0.2958 | (patience: 25/20)
Epoch 27/150 | Base Loss: 0.4676 | Tarreg Loss: 1.115082 | Total Loss: 1.5827 | Val Loss: 0.5426 | Raw Qini: 0.2456 | EMA Trend: 0.2883 | (patience: 26/20)
Epoch 28/150 | Base Loss: 0.4845 | Tarreg Loss: 1.177221 | Total Loss: 1.6617 | Val Loss: 0.5446 | Raw Qini: 0.2422 | EMA Trend: 0.2814 | (patience: 27/20)
Epoch 29/150 | Base Loss: 0.5067 | Tarreg Loss: 1.179948 | Total Loss: 1.6866 | Val Loss: 0.5410 | Raw Qini: 0.2415 | EMA Trend: 0.2754 | (patience: 28/20)
Epoch 30/150 | Base Loss: 0.5097 | Tarreg Loss: 1.142409 | Total Loss: 1.6521 | Val Loss: 0.5403 | Raw Qini: 0.2299 | EMA Trend: 0.2686 | (patience: 29/20)
Epoch 31/150 | Base Loss: 0.4886 | Tarreg Loss: 1.174246 | Total Loss: 1.6629 | Val Loss: 0.5343 | Raw Qini: 0.2257 | EMA Trend: 0.2621 | (patience: 30/20)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 1
   Best Raw Qini: 0.8176
   Final EMA Trend: 0.2621
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 412312
Locked random seed: 42
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Base Loss: 1.7721 | Tarreg Loss: 1.238386 | Total Loss: 3.0105 | Val Loss: 1.7800 | Raw Qini: 0.5876 | EMA Trend: 0.5876 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Base Loss: 1.7317 | Tarreg Loss: 1.091770 | Total Loss: 2.8235 | Val Loss: 1.7366 | Raw Qini: 0.8350 | EMA Trend: 0.6247 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Base Loss: 1.6934 | Tarreg Loss: 0.990272 | Total Loss: 2.6837 | Val Loss: 1.6791 | Raw Qini: 0.9707 | EMA Trend: 0.6766 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Base Loss: 1.6282 | Tarreg Loss: 1.252940 | Total Loss: 2.8811 | Val Loss: 1.6056 | Raw Qini: 0.9367 | EMA Trend: 0.7156 | ✓ above trend but not peak (patience: 1/20)
Epoch 5/150 | Base Loss: 1.4680 | Tarreg Loss: 1.097519 | Total Loss: 2.5655 | Val Loss: 1.4997 | Raw Qini: 0.9274 | EMA Trend: 0.7474 | ✓ above trend but not peak (patience: 2/20)
Epoch 6/150 | Base Loss: 1.4053 | Tarreg Loss: 0.796928 | Total Loss: 2.2023 | Val Loss: 1.3416 | Raw Qini: 0.9246 | EMA Trend: 0.7740 | ✓ above trend but not peak (patience: 3/20)
Epoch 7/150 | Base Loss: 1.2199 | Tarreg Loss: 0.781542 | Total Loss: 2.0015 | Val Loss: 1.1276 | Raw Qini: 0.9282 | EMA Trend: 0.7971 | ✓ above trend but not peak (patience: 4/20)
Epoch 8/150 | Base Loss: 0.8739 | Tarreg Loss: 0.767761 | Total Loss: 1.6417 | Val Loss: 0.8724 | Raw Qini: 0.8921 | EMA Trend: 0.8113 | ✓ above trend but not peak (patience: 5/20)
Epoch 9/150 | Base Loss: 0.6652 | Tarreg Loss: 0.751337 | Total Loss: 1.4165 | Val Loss: 0.6301 | Raw Qini: 0.4213 | EMA Trend: 0.7528 | (patience: 6/20)
Epoch 10/150 | Base Loss: 0.4654 | Tarreg Loss: 0.717499 | Total Loss: 1.1829 | Val Loss: 0.4871 | Raw Qini: 0.2843 | EMA Trend: 0.6826 | (patience: 7/20)
Epoch 11/150 | Base Loss: 0.3864 | Tarreg Loss: 0.709185 | Total Loss: 1.0956 | Val Loss: 0.4426 | Raw Qini: 0.2876 | EMA Trend: 0.6233 | (patience: 8/20)
Epoch 12/150 | Base Loss: 0.3628 | Tarreg Loss: 0.689249 | Total Loss: 1.0521 | Val Loss: 0.4413 | Raw Qini: 0.3343 | EMA Trend: 0.5800 | (patience: 9/20)
Epoch 13/150 | Base Loss: 0.3488 | Tarreg Loss: 0.655075 | Total Loss: 1.0038 | Val Loss: 0.4476 | Raw Qini: 0.8342 | EMA Trend: 0.6181 | ✓ above trend but not peak (patience: 10/20)
Epoch 14/150 | Base Loss: 0.3618 | Tarreg Loss: 0.691860 | Total Loss: 1.0536 | Val Loss: 0.4501 | Raw Qini: 0.7437 | EMA Trend: 0.6369 | ✓ above trend but not peak (patience: 11/20)
Epoch 15/150 | Base Loss: 0.3545 | Tarreg Loss: 0.664575 | Total Loss: 1.0191 | Val Loss: 0.4515 | Raw Qini: 0.7254 | EMA Trend: 0.6502 | ✓ above trend but not peak (patience: 12/20)
Epoch 16/150 | Base Loss: 0.3554 | Tarreg Loss: 0.650973 | Total Loss: 1.0064 | Val Loss: 0.4491 | Raw Qini: 0.7095 | EMA Trend: 0.6591 | ✓ above trend but not peak (patience: 13/20)
Epoch 17/150 | Base Loss: 0.3546 | Tarreg Loss: 0.629928 | Total Loss: 0.9846 | Val Loss: 0.4476 | Raw Qini: 0.6989 | EMA Trend: 0.6651 | ✓ above trend but not peak (patience: 14/20)
Epoch 18/150 | Base Loss: 0.3600 | Tarreg Loss: 0.621283 | Total Loss: 0.9813 | Val Loss: 0.4472 | Raw Qini: 0.6853 | EMA Trend: 0.6681 | ✓ above trend but not peak (patience: 15/20)
Epoch 19/150 | Base Loss: 0.3610 | Tarreg Loss: 0.602043 | Total Loss: 0.9630 | Val Loss: 0.4483 | Raw Qini: 0.6794 | EMA Trend: 0.6698 | ✓ above trend but not peak (patience: 16/20)
Epoch 20/150 | Base Loss: 0.3645 | Tarreg Loss: 0.608024 | Total Loss: 0.9725 | Val Loss: 0.4498 | Raw Qini: 0.6680 | EMA Trend: 0.6695 | (patience: 17/20)
Epoch 21/150 | Base Loss: 0.3708 | Tarreg Loss: 0.588239 | Total Loss: 0.9590 | Val Loss: 0.4510 | Raw Qini: 0.6683 | EMA Trend: 0.6693 | (patience: 18/20)
Epoch 22/150 | Base Loss: 0.3788 | Tarreg Loss: 0.589127 | Total Loss: 0.9680 | Val Loss: 0.4508 | Raw Qini: 0.6631 | EMA Trend: 0.6684 | (patience: 19/20)
Epoch 23/150 | Base Loss: 0.9064 | Tarreg Loss: 0.537463 | Total Loss: 1.4438 | Val Loss: 0.4493 | Raw Qini: 0.6633 | EMA Trend: 0.6676 | (patience: 20/20)
Epoch 24/150 | Base Loss: 0.3749 | Tarreg Loss: 0.571220 | Total Loss: 0.9461 | Val Loss: 0.4475 | Raw Qini: 0.6822 | EMA Trend: 0.6698 | ✓ above trend but not peak (patience: 21/20)
Epoch 25/150 | Base Loss: 1.2184 | Tarreg Loss: 0.521109 | Total Loss: 1.7395 | Val Loss: 0.4472 | Raw Qini: 0.6874 | EMA Trend: 0.6725 | ✓ above trend but not peak (patience: 22/20)
Epoch 26/150 | Base Loss: 0.3885 | Tarreg Loss: 0.588014 | Total Loss: 0.9765 | Val Loss: 0.4460 | Raw Qini: 0.6706 | EMA Trend: 0.6722 | (patience: 23/20)
Epoch 27/150 | Base Loss: 0.3797 | Tarreg Loss: 0.555729 | Total Loss: 0.9354 | Val Loss: 0.4448 | Raw Qini: 0.6623 | EMA Trend: 0.6707 | (patience: 24/20)
Epoch 28/150 | Base Loss: 0.3797 | Tarreg Loss: 0.563434 | Total Loss: 0.9431 | Val Loss: 0.4423 | Raw Qini: 0.6503 | EMA Trend: 0.6676 | (patience: 25/20)
Epoch 29/150 | Base Loss: 0.3746 | Tarreg Loss: 0.558531 | Total Loss: 0.9331 | Val Loss: 0.4416 | Raw Qini: 0.6397 | EMA Trend: 0.6634 | (patience: 26/20)
Epoch 30/150 | Base Loss: 0.3759 | Tarreg Loss: 0.546116 | Total Loss: 0.9220 | Val Loss: 0.4403 | Raw Qini: 0.6379 | EMA Trend: 0.6596 | (patience: 27/20)
Epoch 31/150 | Base Loss: 0.3663 | Tarreg Loss: 0.522951 | Total Loss: 0.8893 | Val Loss: 0.4403 | Raw Qini: 0.6366 | EMA Trend: 0.6562 | (patience: 28/20)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 3
   Best Raw Qini: 0.9707
   Final EMA Trend: 0.6562
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 42
Locked random seed: 1874
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Base Loss: 1.7633 | Tarreg Loss: 9.318486 | Total Loss: 11.0818 | Val Loss: 1.7713 | Raw Qini: 0.6071 | EMA Trend: 0.6071 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Base Loss: 1.7656 | Tarreg Loss: 9.596092 | Total Loss: 11.3617 | Val Loss: 1.7694 | Raw Qini: 0.6810 | EMA Trend: 0.6182 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Base Loss: 1.7568 | Tarreg Loss: 9.803747 | Total Loss: 11.5606 | Val Loss: 1.7703 | Raw Qini: 0.7130 | EMA Trend: 0.6324 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Base Loss: 1.7758 | Tarreg Loss: 9.213513 | Total Loss: 10.9893 | Val Loss: 1.7730 | Raw Qini: 0.7554 | EMA Trend: 0.6509 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/150 | Base Loss: 1.7712 | Tarreg Loss: 9.441312 | Total Loss: 11.2125 | Val Loss: 1.7763 | Raw Qini: 0.7839 | EMA Trend: 0.6708 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/150 | Base Loss: 1.7974 | Tarreg Loss: 8.396999 | Total Loss: 10.1944 | Val Loss: 1.7774 | Raw Qini: 0.7898 | EMA Trend: 0.6887 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/150 | Base Loss: 1.7789 | Tarreg Loss: 8.519593 | Total Loss: 10.2985 | Val Loss: 1.7832 | Raw Qini: 0.7892 | EMA Trend: 0.7038 | ✓ above trend but not peak (patience: 1/20)
Epoch 8/150 | Base Loss: 1.7322 | Tarreg Loss: 9.442786 | Total Loss: 11.1750 | Val Loss: 1.7611 | Raw Qini: 0.7965 | EMA Trend: 0.7177 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/150 | Base Loss: 1.6489 | Tarreg Loss: 7.961391 | Total Loss: 9.6103 | Val Loss: 1.6780 | Raw Qini: 0.7967 | EMA Trend: 0.7295 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/150 | Base Loss: 1.5528 | Tarreg Loss: 7.768844 | Total Loss: 9.3216 | Val Loss: 1.5612 | Raw Qini: 0.8016 | EMA Trend: 0.7403 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/150 | Base Loss: 1.4419 | Tarreg Loss: 7.654796 | Total Loss: 9.0967 | Val Loss: 1.4363 | Raw Qini: 0.8064 | EMA Trend: 0.7503 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/150 | Base Loss: 1.3313 | Tarreg Loss: 6.948899 | Total Loss: 8.2802 | Val Loss: 1.3313 | Raw Qini: 0.8086 | EMA Trend: 0.7590 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/150 | Base Loss: 1.2441 | Tarreg Loss: 6.652110 | Total Loss: 7.8962 | Val Loss: 1.2673 | Raw Qini: 0.8216 | EMA Trend: 0.7684 | ⭐ NEW BEST (peak ≥ trend)
Epoch 14/150 | Base Loss: 1.2393 | Tarreg Loss: 7.585404 | Total Loss: 8.8247 | Val Loss: 1.2613 | Raw Qini: 0.8092 | EMA Trend: 0.7745 | ✓ above trend but not peak (patience: 1/20)
Epoch 15/150 | Base Loss: 1.2432 | Tarreg Loss: 7.582588 | Total Loss: 8.8258 | Val Loss: 1.2677 | Raw Qini: 0.7895 | EMA Trend: 0.7768 | ✓ above trend but not peak (patience: 2/20)
Epoch 16/150 | Base Loss: 1.2526 | Tarreg Loss: 7.411064 | Total Loss: 8.6637 | Val Loss: 1.2798 | Raw Qini: 0.7828 | EMA Trend: 0.7777 | ✓ above trend but not peak (patience: 3/20)
Epoch 17/150 | Base Loss: 1.2490 | Tarreg Loss: 7.108039 | Total Loss: 8.3571 | Val Loss: 1.2841 | Raw Qini: 0.7836 | EMA Trend: 0.7786 | ✓ above trend but not peak (patience: 4/20)
Epoch 18/150 | Base Loss: 1.2562 | Tarreg Loss: 7.289257 | Total Loss: 8.5454 | Val Loss: 1.2889 | Raw Qini: 0.7805 | EMA Trend: 0.7789 | ✓ above trend but not peak (patience: 5/20)
Epoch 19/150 | Base Loss: 1.2570 | Tarreg Loss: 6.764055 | Total Loss: 8.0210 | Val Loss: 1.2937 | Raw Qini: 0.7702 | EMA Trend: 0.7776 | (patience: 6/20)
Epoch 20/150 | Base Loss: 1.2589 | Tarreg Loss: 7.231718 | Total Loss: 8.4906 | Val Loss: 1.3002 | Raw Qini: 0.7701 | EMA Trend: 0.7764 | (patience: 7/20)
Epoch 21/150 | Base Loss: 1.2493 | Tarreg Loss: 6.785640 | Total Loss: 8.0349 | Val Loss: 1.2944 | Raw Qini: 0.7639 | EMA Trend: 0.7746 | (patience: 8/20)
Epoch 22/150 | Base Loss: 1.2608 | Tarreg Loss: 7.374928 | Total Loss: 8.6358 | Val Loss: 1.3049 | Raw Qini: 0.7715 | EMA Trend: 0.7741 | (patience: 9/20)
Epoch 23/150 | Base Loss: 1.2029 | Tarreg Loss: 7.101046 | Total Loss: 8.3039 | Val Loss: 1.2966 | Raw Qini: 0.7710 | EMA Trend: 0.7736 | (patience: 10/20)
Epoch 24/150 | Base Loss: 1.2575 | Tarreg Loss: 6.883860 | Total Loss: 8.1413 | Val Loss: 1.3096 | Raw Qini: 0.7711 | EMA Trend: 0.7733 | (patience: 11/20)
Epoch 25/150 | Base Loss: 1.1939 | Tarreg Loss: 7.572546 | Total Loss: 8.7665 | Val Loss: 1.3004 | Raw Qini: 0.7596 | EMA Trend: 0.7712 | (patience: 12/20)
Epoch 26/150 | Base Loss: 1.2549 | Tarreg Loss: 6.808653 | Total Loss: 8.0636 | Val Loss: 1.2966 | Raw Qini: 0.7585 | EMA Trend: 0.7693 | (patience: 13/20)
Epoch 27/150 | Base Loss: 1.2582 | Tarreg Loss: 6.926498 | Total Loss: 8.1847 | Val Loss: 1.2969 | Raw Qini: 0.7630 | EMA Trend: 0.7683 | (patience: 14/20)
Epoch 28/150 | Base Loss: 1.2495 | Tarreg Loss: 7.361198 | Total Loss: 8.6107 | Val Loss: 1.2799 | Raw Qini: 0.7542 | EMA Trend: 0.7662 | (patience: 15/20)
Epoch 29/150 | Base Loss: 1.2351 | Tarreg Loss: 6.950535 | Total Loss: 8.1857 | Val Loss: 1.2640 | Raw Qini: 0.7471 | EMA Trend: 0.7634 | (patience: 16/20)
Epoch 30/150 | Base Loss: 1.2267 | Tarreg Loss: 7.197351 | Total Loss: 8.4240 | Val Loss: 1.2609 | Raw Qini: 0.7417 | EMA Trend: 0.7601 | (patience: 17/20)
Epoch 31/150 | Base Loss: 1.1495 | Tarreg Loss: 7.307678 | Total Loss: 8.4572 | Val Loss: 1.2579 | Raw Qini: 0.7315 | EMA Trend: 0.7558 | (patience: 18/20)
Epoch 32/150 | Base Loss: 1.2486 | Tarreg Loss: 6.460907 | Total Loss: 7.7095 | Val Loss: 1.2908 | Raw Qini: 0.7478 | EMA Trend: 0.7546 | (patience: 19/20)
Epoch 33/150 | Base Loss: 1.2807 | Tarreg Loss: 6.589859 | Total Loss: 7.8705 | Val Loss: 1.2992 | Raw Qini: 0.7501 | EMA Trend: 0.7539 | (patience: 20/20)

🛑 Early stopping triggered at epoch 33!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 13
   Best Raw Qini: 0.8216
   Final EMA Trend: 0.7539
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 1874
Locked random seed: 902745
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Base Loss: 1.7784 | Tarreg Loss: 3.986679 | Total Loss: 5.7651 | Val Loss: 1.7819 | Raw Qini: 0.1581 | EMA Trend: 0.1581 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Base Loss: 1.7520 | Tarreg Loss: 3.518201 | Total Loss: 5.2702 | Val Loss: 1.7460 | Raw Qini: 0.2141 | EMA Trend: 0.1665 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Base Loss: 1.7179 | Tarreg Loss: 3.359754 | Total Loss: 5.0777 | Val Loss: 1.7038 | Raw Qini: 0.3285 | EMA Trend: 0.1908 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Base Loss: 1.6775 | Tarreg Loss: 3.063706 | Total Loss: 4.7413 | Val Loss: 1.6543 | Raw Qini: 0.5866 | EMA Trend: 0.2501 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/150 | Base Loss: 1.6020 | Tarreg Loss: 3.443401 | Total Loss: 5.0454 | Val Loss: 1.5897 | Raw Qini: 0.7837 | EMA Trend: 0.3302 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/150 | Base Loss: 1.5048 | Tarreg Loss: 3.046003 | Total Loss: 4.5509 | Val Loss: 1.4888 | Raw Qini: 0.8457 | EMA Trend: 0.4075 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/150 | Base Loss: 1.3811 | Tarreg Loss: 3.080636 | Total Loss: 4.4617 | Val Loss: 1.3423 | Raw Qini: 0.8729 | EMA Trend: 0.4773 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/150 | Base Loss: 1.1851 | Tarreg Loss: 3.121511 | Total Loss: 4.3066 | Val Loss: 1.1483 | Raw Qini: 0.8863 | EMA Trend: 0.5386 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/150 | Base Loss: 0.9543 | Tarreg Loss: 3.158221 | Total Loss: 4.1125 | Val Loss: 0.9371 | Raw Qini: 0.9179 | EMA Trend: 0.5955 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/150 | Base Loss: 0.7729 | Tarreg Loss: 2.798334 | Total Loss: 3.5713 | Val Loss: 0.7874 | Raw Qini: 0.3948 | EMA Trend: 0.5654 | (patience: 1/20)
Epoch 11/150 | Base Loss: 0.7335 | Tarreg Loss: 2.541462 | Total Loss: 3.2750 | Val Loss: 0.7580 | Raw Qini: 0.2289 | EMA Trend: 0.5149 | (patience: 2/20)
Epoch 12/150 | Base Loss: 0.8542 | Tarreg Loss: 2.667397 | Total Loss: 3.5216 | Val Loss: 0.7910 | Raw Qini: 0.2066 | EMA Trend: 0.4687 | (patience: 3/20)
Epoch 13/150 | Base Loss: 0.7919 | Tarreg Loss: 2.450082 | Total Loss: 3.2420 | Val Loss: 0.8366 | Raw Qini: 0.2176 | EMA Trend: 0.4310 | (patience: 4/20)
Epoch 14/150 | Base Loss: 0.8055 | Tarreg Loss: 2.568070 | Total Loss: 3.3736 | Val Loss: 0.8647 | Raw Qini: 0.2217 | EMA Trend: 0.3996 | (patience: 5/20)
Epoch 15/150 | Base Loss: 0.8231 | Tarreg Loss: 2.459727 | Total Loss: 3.2828 | Val Loss: 0.8611 | Raw Qini: 0.2225 | EMA Trend: 0.3731 | (patience: 6/20)
Epoch 16/150 | Base Loss: 0.8094 | Tarreg Loss: 2.517797 | Total Loss: 3.3272 | Val Loss: 0.8391 | Raw Qini: 0.2293 | EMA Trend: 0.3515 | (patience: 7/20)
Epoch 17/150 | Base Loss: 0.7560 | Tarreg Loss: 2.563062 | Total Loss: 3.3191 | Val Loss: 0.8065 | Raw Qini: 0.2223 | EMA Trend: 0.3321 | (patience: 8/20)
Epoch 18/150 | Base Loss: 0.8180 | Tarreg Loss: 2.650015 | Total Loss: 3.4681 | Val Loss: 0.7973 | Raw Qini: 0.2188 | EMA Trend: 0.3151 | (patience: 9/20)
Epoch 19/150 | Base Loss: 0.7744 | Tarreg Loss: 2.630757 | Total Loss: 3.4052 | Val Loss: 0.8096 | Raw Qini: 0.2091 | EMA Trend: 0.2992 | (patience: 10/20)
Epoch 20/150 | Base Loss: 0.7678 | Tarreg Loss: 2.452250 | Total Loss: 3.2200 | Val Loss: 0.8079 | Raw Qini: 0.2023 | EMA Trend: 0.2847 | (patience: 11/20)
Epoch 21/150 | Base Loss: 0.7836 | Tarreg Loss: 2.309647 | Total Loss: 3.0932 | Val Loss: 0.8216 | Raw Qini: 0.2012 | EMA Trend: 0.2722 | (patience: 12/20)
Epoch 22/150 | Base Loss: 0.7898 | Tarreg Loss: 2.701539 | Total Loss: 3.4913 | Val Loss: 0.8209 | Raw Qini: 0.1860 | EMA Trend: 0.2592 | (patience: 13/20)
Epoch 23/150 | Base Loss: 0.7558 | Tarreg Loss: 2.482651 | Total Loss: 3.2384 | Val Loss: 0.8003 | Raw Qini: 0.1804 | EMA Trend: 0.2474 | (patience: 14/20)
Epoch 24/150 | Base Loss: 0.7399 | Tarreg Loss: 2.425352 | Total Loss: 3.1653 | Val Loss: 0.7919 | Raw Qini: 0.1767 | EMA Trend: 0.2368 | (patience: 15/20)
Epoch 25/150 | Base Loss: 0.7424 | Tarreg Loss: 2.146033 | Total Loss: 2.8885 | Val Loss: 0.7959 | Raw Qini: 0.1794 | EMA Trend: 0.2282 | (patience: 16/20)
Epoch 26/150 | Base Loss: 0.7314 | Tarreg Loss: 2.542754 | Total Loss: 3.2741 | Val Loss: 0.7910 | Raw Qini: 0.1713 | EMA Trend: 0.2196 | (patience: 17/20)
Epoch 27/150 | Base Loss: 0.7341 | Tarreg Loss: 2.414217 | Total Loss: 3.1483 | Val Loss: 0.7816 | Raw Qini: 0.1757 | EMA Trend: 0.2131 | (patience: 18/20)
Epoch 28/150 | Base Loss: 0.8390 | Tarreg Loss: 2.597207 | Total Loss: 3.4362 | Val Loss: 0.8001 | Raw Qini: 0.1721 | EMA Trend: 0.2069 | (patience: 19/20)
Epoch 29/150 | Base Loss: 0.7845 | Tarreg Loss: 2.422005 | Total Loss: 3.2065 | Val Loss: 0.8189 | Raw Qini: 0.1768 | EMA Trend: 0.2024 | (patience: 20/20)
Epoch 30/150 | Base Loss: 0.7690 | Tarreg Loss: 2.312966 | Total Loss: 3.0819 | Val Loss: 0.8097 | Raw Qini: 0.1816 | EMA Trend: 0.1993 | (patience: 21/20)
Epoch 31/150 | Base Loss: 0.7524 | Tarreg Loss: 2.291623 | Total Loss: 3.0440 | Val Loss: 0.7985 | Raw Qini: 0.1950 | EMA Trend: 0.1986 | (patience: 22/20)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 9
   Best Raw Qini: 0.9179
   Final EMA Trend: 0.1986
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 902745
Locked random seed: 1
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Base Loss: 1.6412 | Tarreg Loss: 0.774779 | Total Loss: 2.4160 | Val Loss: 1.6333 | Raw Qini: 0.6741 | EMA Trend: 0.6741 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Base Loss: 1.6179 | Tarreg Loss: 0.649550 | Total Loss: 2.2674 | Val Loss: 1.5964 | Raw Qini: 0.8234 | EMA Trend: 0.6965 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Base Loss: 1.5611 | Tarreg Loss: 0.680170 | Total Loss: 2.2412 | Val Loss: 1.5450 | Raw Qini: 0.7708 | EMA Trend: 0.7076 | ✓ above trend but not peak (patience: 1/20)
Epoch 4/150 | Base Loss: 1.4647 | Tarreg Loss: 0.968955 | Total Loss: 2.4337 | Val Loss: 1.4711 | Raw Qini: 0.6648 | EMA Trend: 0.7012 | (patience: 2/20)
Epoch 5/150 | Base Loss: 1.4396 | Tarreg Loss: 0.549255 | Total Loss: 1.9889 | Val Loss: 1.3671 | Raw Qini: 0.6001 | EMA Trend: 0.6860 | (patience: 3/20)
Epoch 6/150 | Base Loss: 1.2348 | Tarreg Loss: 0.647608 | Total Loss: 1.8824 | Val Loss: 1.2230 | Raw Qini: 0.6374 | EMA Trend: 0.6787 | (patience: 4/20)
Epoch 7/150 | Base Loss: 1.0854 | Tarreg Loss: 0.555510 | Total Loss: 1.6409 | Val Loss: 1.0279 | Raw Qini: 0.6306 | EMA Trend: 0.6715 | (patience: 5/20)
Epoch 8/150 | Base Loss: 0.8300 | Tarreg Loss: 0.596438 | Total Loss: 1.4265 | Val Loss: 0.7982 | Raw Qini: 0.2533 | EMA Trend: 0.6088 | (patience: 6/20)
Epoch 9/150 | Base Loss: 0.5813 | Tarreg Loss: 0.526878 | Total Loss: 1.1082 | Val Loss: 0.5927 | Raw Qini: 0.2788 | EMA Trend: 0.5593 | (patience: 7/20)
Epoch 10/150 | Base Loss: 0.4469 | Tarreg Loss: 0.547343 | Total Loss: 0.9942 | Val Loss: 0.4810 | Raw Qini: 0.3138 | EMA Trend: 0.5225 | (patience: 8/20)
Epoch 11/150 | Base Loss: 0.3753 | Tarreg Loss: 0.493767 | Total Loss: 0.8690 | Val Loss: 0.4458 | Raw Qini: 0.3151 | EMA Trend: 0.4914 | (patience: 9/20)
Epoch 12/150 | Base Loss: 0.3658 | Tarreg Loss: 0.520543 | Total Loss: 0.8864 | Val Loss: 0.4425 | Raw Qini: 0.3145 | EMA Trend: 0.4648 | (patience: 10/20)
Epoch 13/150 | Base Loss: 0.3577 | Tarreg Loss: 0.515839 | Total Loss: 0.8735 | Val Loss: 0.4450 | Raw Qini: 0.3187 | EMA Trend: 0.4429 | (patience: 11/20)
Epoch 14/150 | Base Loss: 0.3555 | Tarreg Loss: 0.517081 | Total Loss: 0.8726 | Val Loss: 0.4461 | Raw Qini: 0.3159 | EMA Trend: 0.4239 | (patience: 12/20)
Epoch 15/150 | Base Loss: 0.3586 | Tarreg Loss: 0.509270 | Total Loss: 0.8679 | Val Loss: 0.4457 | Raw Qini: 0.3050 | EMA Trend: 0.4060 | (patience: 13/20)
Epoch 16/150 | Base Loss: 1.0241 | Tarreg Loss: 0.471464 | Total Loss: 1.4956 | Val Loss: 0.4442 | Raw Qini: 0.3044 | EMA Trend: 0.3908 | (patience: 14/20)
Epoch 17/150 | Base Loss: 0.3601 | Tarreg Loss: 0.481326 | Total Loss: 0.8415 | Val Loss: 0.4428 | Raw Qini: 0.3122 | EMA Trend: 0.3790 | (patience: 15/20)
Epoch 18/150 | Base Loss: 0.3715 | Tarreg Loss: 0.474611 | Total Loss: 0.8461 | Val Loss: 0.4432 | Raw Qini: 0.3089 | EMA Trend: 0.3685 | (patience: 16/20)
Epoch 19/150 | Base Loss: 0.3742 | Tarreg Loss: 0.494692 | Total Loss: 0.8689 | Val Loss: 0.4445 | Raw Qini: 0.3104 | EMA Trend: 0.3598 | (patience: 17/20)
Epoch 20/150 | Base Loss: 0.3842 | Tarreg Loss: 0.463138 | Total Loss: 0.8473 | Val Loss: 0.4452 | Raw Qini: 0.3118 | EMA Trend: 0.3526 | (patience: 18/20)
Epoch 21/150 | Base Loss: 0.3794 | Tarreg Loss: 0.436246 | Total Loss: 0.8156 | Val Loss: 0.4455 | Raw Qini: 0.3162 | EMA Trend: 0.3471 | (patience: 19/20)
Epoch 22/150 | Base Loss: 2.4203 | Tarreg Loss: 0.381771 | Total Loss: 2.8021 | Val Loss: 0.4466 | Raw Qini: 0.3130 | EMA Trend: 0.3420 | (patience: 20/20)
Epoch 23/150 | Base Loss: 0.3898 | Tarreg Loss: 0.457603 | Total Loss: 0.8474 | Val Loss: 0.4478 | Raw Qini: 0.2792 | EMA Trend: 0.3326 | (patience: 21/20)
Epoch 24/150 | Base Loss: 0.3909 | Tarreg Loss: 0.432324 | Total Loss: 0.8232 | Val Loss: 0.4463 | Raw Qini: 0.2723 | EMA Trend: 0.3236 | (patience: 22/20)
Epoch 25/150 | Base Loss: 0.3789 | Tarreg Loss: 0.429684 | Total Loss: 0.8085 | Val Loss: 0.4441 | Raw Qini: 0.2702 | EMA Trend: 0.3156 | (patience: 23/20)
Epoch 26/150 | Base Loss: 0.3857 | Tarreg Loss: 0.416063 | Total Loss: 0.8018 | Val Loss: 0.4414 | Raw Qini: 0.2734 | EMA Trend: 0.3092 | (patience: 24/20)
Epoch 27/150 | Base Loss: 0.3727 | Tarreg Loss: 0.426433 | Total Loss: 0.7991 | Val Loss: 0.4393 | Raw Qini: 0.2791 | EMA Trend: 0.3047 | (patience: 25/20)
Epoch 28/150 | Base Loss: 0.3723 | Tarreg Loss: 0.413787 | Total Loss: 0.7861 | Val Loss: 0.4383 | Raw Qini: 0.2820 | EMA Trend: 0.3013 | (patience: 26/20)
Epoch 29/150 | Base Loss: 0.3702 | Tarreg Loss: 0.402290 | Total Loss: 0.7725 | Val Loss: 0.4380 | Raw Qini: 0.2801 | EMA Trend: 0.2981 | (patience: 27/20)
Epoch 30/150 | Base Loss: 0.8038 | Tarreg Loss: 0.543099 | Total Loss: 1.3469 | Val Loss: 0.4387 | Raw Qini: 0.2763 | EMA Trend: 0.2949 | (patience: 28/20)
Epoch 31/150 | Base Loss: 0.3835 | Tarreg Loss: 0.402404 | Total Loss: 0.7859 | Val Loss: 0.4427 | Raw Qini: 0.2648 | EMA Trend: 0.2903 | (patience: 29/20)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 2
   Best Raw Qini: 0.8234
   Final EMA Trend: 0.2903
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 1

=====================================================================================
                            CHI TIẾT TỪNG SEED (TEST SET)
=====================================================================================
  Seed   AUUC   AUQC   Lift   KRCC ATE_Err
412312 0.8487 0.8543 0.0066 0.0941  0.0159
    42 0.5613 0.5580 0.0039 0.0390  0.0172
  1874 0.6423 0.6410 0.0052 0.1132  0.5744
902745 0.7444 0.7405 0.0057 0.1185  0.1313
     1 0.9008 0.9070 0.0068 0.1974  0.0178
=====================================================================================
                        KẾT QUẢ TRUNG BÌNH TEST (MEAN ± STD)
-------------------------------------------------------------------------------------
AUUC      : 0.7395 ± 0.1407
AUQC      : 0.7401 ± 0.1448
Lift      : 0.0057 ± 0.0012
KRCC      : 0.1124 ± 0.0570
ATE_Err   : 0.1513 ± 0.2416
=====================================================================================

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/Dragonnet/dragonnet.py:329: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)