Import libraries

In [1]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from dragonnet import Dragonnet
import sys
from pathlib import Path
project_root = Path("/home/ducm/Benchmark-conversion-vs-revenue-uplift-modeling/Revenue/Tarnet/main_tarnet.ipynb")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [2]:
%time train_df = pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Women/train_women.csv")
%time test_df =  pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Women/test_women.csv")
%time val_df = pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Women/val_women.csv")

CPU times: user 27.1 ms, sys: 8 ms, total: 35.1 ms
Wall time: 38.7 ms
CPU times: user 12 ms, sys: 4.92 ms, total: 16.9 ms
Wall time: 18.6 ms
CPU times: user 3.88 ms, sys: 2.82 ms, total: 6.7 ms
Wall time: 7.63 ms

In [3]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['spend']
treatment_feature = ['treatment']

In [4]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [5]:
print('X_train[:10]', X_train[:1].astype(float))

X_train[:10] [[-0.78953321  1.6460815   1.41745802 -1.11692492  0.91314538  1.07643872
   0.9950542  -0.36894675 -0.88924565  1.13133938]]

In [6]:
print('y_train[:10]', y_train[:1].astype(float))

y_train[:10] [[0.]]

In [7]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25615, 10]); y=torch.Size([25615, 1]); t=torch.Size([25615, 1])
Shape of val: x=torch.Size([4270, 10]); y=torch.Size([4270, 1]); t=torch.Size([4270, 1])
Shape of test: x=torch.Size([12808, 10]); y=torch.Size([12808, 1]); t=torch.Size([12808, 1])

In [8]:
epochs = 150
lr = 5e-5
wd = 1e-5
alpha = 0.1
beta = 0.1
early_stop_metric = "qini"
ema = True
ema_alpha = 0.15
patience = 20
shared_dropout = 0
outcome_dropout = 0.0
shared_hidden = 200
outcome_hidden = 100
early_stop_start = 30
activation = torch.nn.ReLU
print (f" epochs = {epochs}")
print (f" learning rate = {lr}")
print (f" weight decay = {wd}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" shared hidden = {shared_hidden}")
print (f" outcome hidden = {outcome_hidden}")
print (f" early stop start = {early_stop_start}")

 epochs = 150
 learning rate = 5e-05
 weight decay = 1e-05
 early stop = qini
 use ema = True
 ema alpha = 0.15
 patience = 20
 shared hidden = 200
 outcome hidden = 100
 early stop start = 30

In [9]:
import pandas as pd
import numpy as np
import torch
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 5e-5, 5e-4, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-4, log=True)
    grid_alpha = trial.suggest_categorical("alpha", [0.1, 0.5, 1.0])
    grid_beta = trial.suggest_categorical("beta", [0.1, 0.5, 1.0])

    val_scores = []
    for SEED in seeds:
        seed_everything(SEED)

        dragonnet = Dragonnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            alpha=grid_alpha,
            beta=grid_beta,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=shared_hidden,
            outcome_hidden=outcome_hidden,
            outcome_droupout=outcome_dropout,
            shared_dropout=shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
            activation=activation
        )

        # Silence Dragonnet epoch logs
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            dragonnet.fit(train_loader, val_loader)

        x_val_device = x_men_val_t.to(device)
        y0_val_p, y1_val_p, _, _ = dragonnet.predict(x_val_device)
        uplift_val = (y1_val_p - y0_val_p).detach().cpu().numpy().flatten()
        y_val_true_np = y_men_val_t.detach().cpu().numpy().flatten()
        t_val_true_np = t_men_val_t.detach().cpu().numpy().flatten()

        current_val_auqc = auqc(y_val_true_np, t_val_true_np, uplift_val, bins=100, plot=False)
        val_scores.append(current_val_auqc)

    mean_val_auqc = float(np.mean(val_scores))
    std_val_auqc = float(np.std(val_scores, ddof=1)) if len(val_scores) > 1 else 0.0
    trial.set_user_attr("std_Val_AUQC", std_val_auqc)
    return mean_val_auqc

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

# 2. Persist search results in notebook variables
trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": t.params["lr"],
        "weight_decay": t.params["weight_decay"],
        "alpha": t.params["alpha"],
        "beta": t.params["beta"],
        "mean_Val_AUQC": float(t.value),
        "std_Val_AUQC": float(t.user_attrs.get("std_Val_AUQC", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_Val_AUQC", ascending=False).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "alpha": float(best_params["alpha"]),
    "beta": float(best_params["beta"]),
    "mean_Val_AUQC": float(study.best_value),
    "std_Val_AUQC": float(study.best_trial.user_attrs.get("std_Val_AUQC", np.nan))
})

/home/ducvu0904/miniconda3/envs/ai/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
  0%|          | 0/50 [00:00<?, ?it/s]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 0. Best value: 1.21155:   2%|▏         | 1/50 [01:09<57:05, 69.91s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 1. Best value: 1.21976:   4%|▍         | 2/50 [02:10<51:28, 64.34s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 1. Best value: 1.21976:   6%|▌         | 3/50 [03:09<48:29, 61.89s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 3. Best value: 1.22066:   8%|▊         | 4/50 [04:12<47:55, 62.50s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 4. Best value: 1.22087:  10%|█         | 5/50 [05:38<53:03, 70.74s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 5. Best value: 1.23371:  12%|█▏        | 6/50 [06:36<48:53, 66.67s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  14%|█▍        | 7/50 [07:37<46:25, 64.78s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  16%|█▌        | 8/50 [08:37<44:16, 63.26s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  18%|█▊        | 9/50 [09:32<41:29, 60.72s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  20%|██        | 10/50 [10:35<40:50, 61.26s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  22%|██▏       | 11/50 [11:56<43:43, 67.27s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  24%|██▍       | 12/50 [12:53<40:40, 64.21s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  26%|██▌       | 13/50 [14:06<41:15, 66.91s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  28%|██▊       | 14/50 [15:07<39:02, 65.07s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  30%|███       | 15/50 [16:42<43:18, 74.24s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  32%|███▏      | 16/50 [17:43<39:41, 70.03s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  34%|███▍      | 17/50 [18:52<38:23, 69.81s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  36%|███▌      | 18/50 [19:50<35:21, 66.28s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  38%|███▊      | 19/50 [20:59<34:41, 67.14s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  40%|████      | 20/50 [21:59<32:26, 64.88s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  42%|████▏     | 21/50 [22:55<30:03, 62.19s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  44%|████▍     | 22/50 [23:54<28:40, 61.44s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  46%|████▌     | 23/50 [24:54<27:23, 60.86s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  48%|████▊     | 24/50 [25:58<26:45, 61.76s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  50%|█████     | 25/50 [27:02<26:00, 62.40s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  52%|█████▏    | 26/50 [28:02<24:42, 61.77s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  54%|█████▍    | 27/50 [28:58<23:02, 60.12s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  56%|█████▌    | 28/50 [30:00<22:10, 60.47s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  58%|█████▊    | 29/50 [31:03<21:30, 61.44s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  60%|██████    | 30/50 [32:06<20:37, 61.88s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  62%|██████▏   | 31/50 [33:07<19:31, 61.63s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  64%|██████▍   | 32/50 [34:06<18:14, 60.79s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  66%|██████▌   | 33/50 [35:08<17:22, 61.30s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  68%|██████▊   | 34/50 [36:09<16:15, 60.97s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  70%|███████   | 35/50 [37:12<15:24, 61.65s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  72%|███████▏  | 36/50 [38:10<14:06, 60.47s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  74%|███████▍  | 37/50 [39:24<14:01, 64.72s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  76%|███████▌  | 38/50 [40:24<12:37, 63.16s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  78%|███████▊  | 39/50 [41:23<11:20, 61.86s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  80%|████████  | 40/50 [42:20<10:05, 60.53s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 1.24345:  82%|████████▏ | 41/50 [43:22<09:07, 60.88s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 41. Best value: 1.24957:  84%|████████▍ | 42/50 [44:23<08:07, 60.92s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 41. Best value: 1.24957:  86%|████████▌ | 43/50 [45:21<07:00, 60.00s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 41. Best value: 1.24957:  88%|████████▊ | 44/50 [46:21<05:59, 60.00s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 41. Best value: 1.24957:  90%|█████████ | 45/50 [47:16<04:53, 58.72s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 41. Best value: 1.24957:  92%|█████████▏| 46/50 [48:14<03:53, 58.36s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 41. Best value: 1.24957:  94%|█████████▍| 47/50 [49:13<02:56, 58.72s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 41. Best value: 1.24957:  96%|█████████▌| 48/50 [50:12<01:57, 58.56s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 41. Best value: 1.24957:  98%|█████████▊| 49/50 [51:13<00:59, 59.50s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 41. Best value: 1.24957: 100%|██████████| 50/50 [52:14<00:00, 62.69s/it]

In [10]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_AUQC: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 41
Best mean_Val_AUQC: 1.249571
Best params: {'lr': 0.00020739654007856528, 'weight_decay': 1.8037651472881755e-05, 'alpha': 0.5, 'beta': 0.5}

Best config table:

         lr  weight_decay  alpha  beta  mean_Val_AUQC  std_Val_AUQC
0  0.000207      0.000018    0.5   0.5       1.249571      0.102022

Top 10 trials:

   trial        lr  weight_decay  alpha  beta  mean_Val_AUQC  std_Val_AUQC
0     41  0.000207      0.000018    0.5   0.5       1.249571      0.102022
1     44  0.000200      0.000022    0.5   0.5       1.248457      0.100393
2     45  0.000205      0.000021    0.5   0.5       1.248221      0.104632
3     48  0.000275      0.000021    0.5   0.5       1.247192      0.111795
4      6  0.000184      0.000032    0.5   0.5       1.243448      0.094391
5     13  0.000217      0.000030    0.5   0.5       1.242827      0.102609
6     32  0.000169      0.000034    0.5   0.5       1.240855      0.094192
7     42  0.000193      0.000019    0.5   0.5       1.240567      0.093979
8     25  0.000255      0.000027    0.5   0.5       1.239930      0.092955
9     17  0.000214      0.000015    0.5   0.5       1.238195      0.115519

In [11]:
import pandas as pd
import numpy as np
import torch

# 1. Evaluate selected config on test set (after tuning)
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

if 'best_cfg' not in globals():
    raise ValueError("best_cfg not found. Run grid-search cell first.")

best_lr = float(best_cfg['lr'])
best_wd = float(best_cfg['weight_decay'])
best_alpha = float(best_cfg['alpha'])
best_beta = float(best_cfg['beta'])

print("Đang đánh giá trên test với best config từ validation:")
print(f"  lr={best_lr:.1e}, weight_decay={best_wd:.1e}, alpha={best_alpha:.1f}, beta={best_beta:.1f}")
print(f"Số seed: {len(seeds)}")

# 2. Loop over seeds for robust test evaluation
for SEED in seeds:
    seed_everything(SEED)

    dragonnet = Dragonnet(
        input_dim=x_men_train_t.shape[1],
        epochs=epochs,
        learning_rate=best_lr,
        alpha=best_alpha,
        beta=best_beta,
        weight_decay=best_wd,
        use_ema=ema,
        ema_alpha=ema_alpha,
        patience=patience,
        shared_hidden=shared_hidden,
        outcome_hidden=outcome_hidden,
        outcome_droupout=outcome_dropout,
        shared_dropout=shared_dropout,
        early_stop_metric=early_stop_metric,
        early_stop_start_epoch=early_stop_start,
        activation=activation
    )

    dragonnet.fit(train_loader, val_loader)

    # Test prediction
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred, _, _ = dragonnet.predict(x_men_test_t_on_device)

    uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
    y_true = y_men_test_t.detach().cpu().numpy().flatten()
    t_true = t_men_test_t.detach().cpu().numpy().flatten()

    # ATE error
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()

    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  Done Seed {SEED}")

# 3. Aggregate final test metrics
df_results = pd.DataFrame(all_runs)

print("\n" + "=" * 85)
print(f"{'CHI TIẾT TỪNG SEED (TEST SET)':^85}")
print("=" * 85)
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format,
    'AUQC': '{:,.4f}'.format,
    'Lift': '{:,.4f}'.format,
    'KRCC': '{:,.4f}'.format,
    'ATE_Err': '{:,.4f}'.format
}))

mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("=" * 85)
print(f"{'KẾT QUẢ TRUNG BÌNH TEST (MEAN ± STD)':^85}")
print("-" * 85)
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")
print("=" * 85)

Đang đánh giá trên test với best config từ validation:
  lr=2.1e-04, weight_decay=1.8e-05, alpha=0.5, beta=0.5
Số seed: 5
Locked random seed: 412312
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/150 | Base Loss: 0.3501 | Tarreg Loss: 0.763453 | Total Loss: 1.1136 | Val Loss: 194.1391 | Raw Qini: 1.3494 | EMA Trend: 1.3494 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Base Loss: 0.3365 | Tarreg Loss: 0.707950 | Total Loss: 1.0445 | Val Loss: 194.0579 | Raw Qini: 1.1924 | EMA Trend: 1.3259 | (patience: 1/20)
Epoch 3/150 | Base Loss: 0.3614 | Tarreg Loss: 0.773683 | Total Loss: 1.1351 | Val Loss: 193.9573 | Raw Qini: 1.1626 | EMA Trend: 1.3014 | (patience: 2/20)
Epoch 4/150 | Base Loss: 0.4026 | Tarreg Loss: 0.908499 | Total Loss: 1.3111 | Val Loss: 193.8406 | Raw Qini: 1.1530 | EMA Trend: 1.2791 | (patience: 3/20)
Epoch 5/150 | Base Loss: 0.3889 | Tarreg Loss: 0.680720 | Total Loss: 1.0696 | Val Loss: 193.6999 | Raw Qini: 1.1407 | EMA Trend: 1.2584 | (patience: 4/20)
Epoch 6/150 | Base Loss: 0.5568 | Tarreg Loss: 0.963083 | Total Loss: 1.5199 | Val Loss: 193.5417 | Raw Qini: 1.1627 | EMA Trend: 1.2440 | (patience: 5/20)
Epoch 7/150 | Base Loss: 0.5967 | Tarreg Loss: 0.732616 | Total Loss: 1.3293 | Val Loss: 193.3749 | Raw Qini: 1.1448 | EMA Trend: 1.2291 | (patience: 6/20)
Epoch 8/150 | Base Loss: 250.9926 | Tarreg Loss: 78.656204 | Total Loss: 329.6488 | Val Loss: 193.2126 | Raw Qini: 1.1311 | EMA Trend: 1.2144 | (patience: 7/20)
Epoch 9/150 | Base Loss: 1.2749 | Tarreg Loss: 0.970104 | Total Loss: 2.2450 | Val Loss: 193.1304 | Raw Qini: 1.1167 | EMA Trend: 1.1998 | (patience: 8/20)
Epoch 10/150 | Base Loss: 1.6336 | Tarreg Loss: 0.650668 | Total Loss: 2.2843 | Val Loss: 193.2114 | Raw Qini: 1.0885 | EMA Trend: 1.1831 | (patience: 9/20)
Epoch 11/150 | Base Loss: 6428.1411 | Tarreg Loss: 2378.391602 | Total Loss: 8806.5332 | Val Loss: 193.3579 | Raw Qini: 1.1018 | EMA Trend: 1.1709 | (patience: 10/20)
Epoch 12/150 | Base Loss: 3.8155 | Tarreg Loss: 0.812918 | Total Loss: 4.6284 | Val Loss: 193.4637 | Raw Qini: 1.1048 | EMA Trend: 1.1610 | (patience: 11/20)
Epoch 13/150 | Base Loss: 3.3679 | Tarreg Loss: 0.721700 | Total Loss: 4.0896 | Val Loss: 193.3324 | Raw Qini: 1.0924 | EMA Trend: 1.1507 | (patience: 12/20)
Epoch 14/150 | Base Loss: 1.8377 | Tarreg Loss: 1.081894 | Total Loss: 2.9196 | Val Loss: 193.2332 | Raw Qini: 1.0893 | EMA Trend: 1.1415 | (patience: 13/20)
Epoch 15/150 | Base Loss: 2.2331 | Tarreg Loss: 0.681238 | Total Loss: 2.9143 | Val Loss: 193.1942 | Raw Qini: 1.0619 | EMA Trend: 1.1295 | (patience: 14/20)
Epoch 16/150 | Base Loss: 2.2746 | Tarreg Loss: 0.423904 | Total Loss: 2.6985 | Val Loss: 193.2001 | Raw Qini: 1.0612 | EMA Trend: 1.1193 | (patience: 15/20)
Epoch 17/150 | Base Loss: 1.5823 | Tarreg Loss: 0.834557 | Total Loss: 2.4169 | Val Loss: 193.2110 | Raw Qini: 1.0453 | EMA Trend: 1.1082 | (patience: 16/20)
Epoch 18/150 | Base Loss: 2.0273 | Tarreg Loss: 1.038460 | Total Loss: 3.0658 | Val Loss: 193.2481 | Raw Qini: 1.0245 | EMA Trend: 1.0956 | (patience: 17/20)
Epoch 19/150 | Base Loss: 3073.4041 | Tarreg Loss: 934.411682 | Total Loss: 4007.8157 | Val Loss: 193.3173 | Raw Qini: 1.0082 | EMA Trend: 1.0825 | (patience: 18/20)
Epoch 20/150 | Base Loss: 2.6694 | Tarreg Loss: 0.992817 | Total Loss: 3.6622 | Val Loss: 193.4194 | Raw Qini: 1.0173 | EMA Trend: 1.0727 | (patience: 19/20)
Epoch 21/150 | Base Loss: 2.4080 | Tarreg Loss: 0.692644 | Total Loss: 3.1006 | Val Loss: 193.4604 | Raw Qini: 1.0037 | EMA Trend: 1.0624 | (patience: 20/20)
Epoch 22/150 | Base Loss: 4.3350 | Tarreg Loss: 0.848137 | Total Loss: 5.1831 | Val Loss: 193.4005 | Raw Qini: 1.0129 | EMA Trend: 1.0550 | (patience: 21/20)
Epoch 23/150 | Base Loss: 2.0155 | Tarreg Loss: 0.895756 | Total Loss: 2.9112 | Val Loss: 193.3730 | Raw Qini: 1.0135 | EMA Trend: 1.0487 | (patience: 22/20)
Epoch 24/150 | Base Loss: 2.6061 | Tarreg Loss: 1.056823 | Total Loss: 3.6629 | Val Loss: 193.3773 | Raw Qini: 0.9958 | EMA Trend: 1.0408 | (patience: 23/20)
Epoch 25/150 | Base Loss: 2.3333 | Tarreg Loss: 0.766008 | Total Loss: 3.0993 | Val Loss: 193.4041 | Raw Qini: 1.0113 | EMA Trend: 1.0364 | (patience: 24/20)
Epoch 26/150 | Base Loss: 1806.9988 | Tarreg Loss: 613.037292 | Total Loss: 2420.0361 | Val Loss: 193.4523 | Raw Qini: 1.0491 | EMA Trend: 1.0383 | ✓ above trend but not peak (patience: 25/20)
Epoch 27/150 | Base Loss: 3.2148 | Tarreg Loss: 0.589834 | Total Loss: 3.8046 | Val Loss: 193.5725 | Raw Qini: 1.0575 | EMA Trend: 1.0412 | ✓ above trend but not peak (patience: 26/20)
Epoch 28/150 | Base Loss: 2.0086 | Tarreg Loss: 0.669761 | Total Loss: 2.6784 | Val Loss: 193.6105 | Raw Qini: 1.0569 | EMA Trend: 1.0435 | ✓ above trend but not peak (patience: 27/20)
Epoch 29/150 | Base Loss: 2.9854 | Tarreg Loss: 0.702990 | Total Loss: 3.6884 | Val Loss: 193.6310 | Raw Qini: 1.0191 | EMA Trend: 1.0399 | (patience: 28/20)
Epoch 30/150 | Base Loss: 2.5487 | Tarreg Loss: 0.888963 | Total Loss: 3.4377 | Val Loss: 193.6288 | Raw Qini: 1.0352 | EMA Trend: 1.0392 | (patience: 29/20)
Epoch 31/150 | Base Loss: 2.7364 | Tarreg Loss: 0.648489 | Total Loss: 3.3849 | Val Loss: 193.6201 | Raw Qini: 1.0602 | EMA Trend: 1.0423 | ✓ above trend but not peak (patience: 30/20)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 1
   Best Raw Qini: 1.3494
   Final EMA Trend: 1.0423
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 412312
Locked random seed: 42
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Base Loss: 0.3714 | Tarreg Loss: 0.447824 | Total Loss: 0.8192 | Val Loss: 193.8441 | Raw Qini: 0.2947 | EMA Trend: 0.2947 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Base Loss: 0.3884 | Tarreg Loss: 0.442558 | Total Loss: 0.8310 | Val Loss: 193.7732 | Raw Qini: 0.2381 | EMA Trend: 0.2862 | (patience: 1/20)
Epoch 3/150 | Base Loss: 0.4131 | Tarreg Loss: 0.436588 | Total Loss: 0.8497 | Val Loss: 193.6941 | Raw Qini: 0.2558 | EMA Trend: 0.2816 | (patience: 2/20)
Epoch 4/150 | Base Loss: 229.1358 | Tarreg Loss: 40.480015 | Total Loss: 269.6159 | Val Loss: 193.5964 | Raw Qini: 0.0229 | EMA Trend: 0.2428 | (patience: 3/20)
Epoch 5/150 | Base Loss: 0.5239 | Tarreg Loss: 0.590149 | Total Loss: 1.1140 | Val Loss: 193.4664 | Raw Qini: 0.0496 | EMA Trend: 0.2138 | (patience: 4/20)
Epoch 6/150 | Base Loss: 0.5887 | Tarreg Loss: 0.399816 | Total Loss: 0.9885 | Val Loss: 193.3210 | Raw Qini: 0.2454 | EMA Trend: 0.2186 | ✓ above trend but not peak (patience: 5/20)
Epoch 7/150 | Base Loss: 0.7766 | Tarreg Loss: 0.382977 | Total Loss: 1.1595 | Val Loss: 193.1898 | Raw Qini: 0.3649 | EMA Trend: 0.2405 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/150 | Base Loss: 1.3308 | Tarreg Loss: 0.721832 | Total Loss: 2.0526 | Val Loss: 193.1259 | Raw Qini: 0.3407 | EMA Trend: 0.2555 | ✓ above trend but not peak (patience: 1/20)
Epoch 9/150 | Base Loss: 1.4338 | Tarreg Loss: 0.525581 | Total Loss: 1.9593 | Val Loss: 193.1145 | Raw Qini: 0.4785 | EMA Trend: 0.2890 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/150 | Base Loss: 1.6819 | Tarreg Loss: 0.676832 | Total Loss: 2.3587 | Val Loss: 193.1333 | Raw Qini: 0.6506 | EMA Trend: 0.3432 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/150 | Base Loss: 1.9788 | Tarreg Loss: 0.916960 | Total Loss: 2.8957 | Val Loss: 193.0988 | Raw Qini: 1.2488 | EMA Trend: 0.4791 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/150 | Base Loss: 2.0318 | Tarreg Loss: 0.625632 | Total Loss: 2.6574 | Val Loss: 193.0511 | Raw Qini: 1.3610 | EMA Trend: 0.6113 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/150 | Base Loss: 1.4371 | Tarreg Loss: 0.419075 | Total Loss: 1.8562 | Val Loss: 193.0166 | Raw Qini: 1.2687 | EMA Trend: 0.7099 | ✓ above trend but not peak (patience: 1/20)
Epoch 14/150 | Base Loss: 1.5674 | Tarreg Loss: 0.913377 | Total Loss: 2.4807 | Val Loss: 192.9986 | Raw Qini: 1.2127 | EMA Trend: 0.7854 | ✓ above trend but not peak (patience: 2/20)
Epoch 15/150 | Base Loss: 1.4989 | Tarreg Loss: 0.650274 | Total Loss: 2.1492 | Val Loss: 193.0041 | Raw Qini: 1.2347 | EMA Trend: 0.8528 | ✓ above trend but not peak (patience: 3/20)
Epoch 16/150 | Base Loss: 2.0913 | Tarreg Loss: 0.887457 | Total Loss: 2.9787 | Val Loss: 193.0258 | Raw Qini: 1.2487 | EMA Trend: 0.9121 | ✓ above trend but not peak (patience: 4/20)
Epoch 17/150 | Base Loss: 2.5358 | Tarreg Loss: 0.983513 | Total Loss: 3.5194 | Val Loss: 193.0616 | Raw Qini: 1.2324 | EMA Trend: 0.9602 | ✓ above trend but not peak (patience: 5/20)
Epoch 18/150 | Base Loss: 1.7208 | Tarreg Loss: 0.663288 | Total Loss: 2.3841 | Val Loss: 193.0721 | Raw Qini: 1.2164 | EMA Trend: 0.9986 | ✓ above trend but not peak (patience: 6/20)
Epoch 19/150 | Base Loss: 1.6181 | Tarreg Loss: 0.830262 | Total Loss: 2.4484 | Val Loss: 193.0684 | Raw Qini: 1.1955 | EMA Trend: 1.0281 | ✓ above trend but not peak (patience: 7/20)
Epoch 20/150 | Base Loss: 2.2566 | Tarreg Loss: 0.853323 | Total Loss: 3.1099 | Val Loss: 193.0715 | Raw Qini: 1.1868 | EMA Trend: 1.0519 | ✓ above trend but not peak (patience: 8/20)
Epoch 21/150 | Base Loss: 1.8355 | Tarreg Loss: 0.621170 | Total Loss: 2.4567 | Val Loss: 193.0755 | Raw Qini: 1.1820 | EMA Trend: 1.0714 | ✓ above trend but not peak (patience: 9/20)
Epoch 22/150 | Base Loss: 1.3791 | Tarreg Loss: 0.690764 | Total Loss: 2.0698 | Val Loss: 193.0841 | Raw Qini: 1.1476 | EMA Trend: 1.0829 | ✓ above trend but not peak (patience: 10/20)
Epoch 23/150 | Base Loss: 2343.1338 | Tarreg Loss: 773.206055 | Total Loss: 3116.3398 | Val Loss: 193.1078 | Raw Qini: 1.1229 | EMA Trend: 1.0889 | ✓ above trend but not peak (patience: 11/20)
Epoch 24/150 | Base Loss: 1.8792 | Tarreg Loss: 0.497569 | Total Loss: 2.3768 | Val Loss: 193.1586 | Raw Qini: 1.0951 | EMA Trend: 1.0898 | ✓ above trend but not peak (patience: 12/20)
Epoch 25/150 | Base Loss: 3146.7666 | Tarreg Loss: 727.083069 | Total Loss: 3873.8496 | Val Loss: 193.2036 | Raw Qini: 1.0534 | EMA Trend: 1.0843 | (patience: 13/20)
Epoch 26/150 | Base Loss: 2.7531 | Tarreg Loss: 1.081306 | Total Loss: 3.8344 | Val Loss: 193.2527 | Raw Qini: 1.0656 | EMA Trend: 1.0815 | (patience: 14/20)
Epoch 27/150 | Base Loss: 1.4474 | Tarreg Loss: 0.695103 | Total Loss: 2.1425 | Val Loss: 193.2556 | Raw Qini: 1.0824 | EMA Trend: 1.0817 | ✓ above trend but not peak (patience: 15/20)
Epoch 28/150 | Base Loss: 2.5539 | Tarreg Loss: 0.655019 | Total Loss: 3.2089 | Val Loss: 193.2437 | Raw Qini: 1.0797 | EMA Trend: 1.0814 | (patience: 16/20)
Epoch 29/150 | Base Loss: 1.7250 | Tarreg Loss: 1.047953 | Total Loss: 2.7730 | Val Loss: 193.2888 | Raw Qini: 1.0458 | EMA Trend: 1.0760 | (patience: 17/20)
Epoch 30/150 | Base Loss: 2.4383 | Tarreg Loss: 0.687805 | Total Loss: 3.1261 | Val Loss: 193.3471 | Raw Qini: 1.0475 | EMA Trend: 1.0718 | (patience: 18/20)
Epoch 31/150 | Base Loss: 2.8038 | Tarreg Loss: 0.885404 | Total Loss: 3.6892 | Val Loss: 193.3645 | Raw Qini: 1.0555 | EMA Trend: 1.0693 | (patience: 19/20)
Epoch 32/150 | Base Loss: 1.1592 | Tarreg Loss: 0.257636 | Total Loss: 1.4168 | Val Loss: 193.4074 | Raw Qini: 1.0587 | EMA Trend: 1.0677 | (patience: 20/20)

🛑 Early stopping triggered at epoch 32!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 12
   Best Raw Qini: 1.3610
   Final EMA Trend: 1.0677
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 42
Locked random seed: 1874
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Base Loss: 0.3527 | Tarreg Loss: 4.626943 | Total Loss: 4.9797 | Val Loss: 194.0078 | Raw Qini: 0.7407 | EMA Trend: 0.7407 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Base Loss: 0.3602 | Tarreg Loss: 4.606780 | Total Loss: 4.9670 | Val Loss: 193.9513 | Raw Qini: 0.7323 | EMA Trend: 0.7394 | (patience: 1/20)
Epoch 3/150 | Base Loss: 0.3752 | Tarreg Loss: 4.730732 | Total Loss: 5.1059 | Val Loss: 193.8871 | Raw Qini: 0.7488 | EMA Trend: 0.7408 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Base Loss: 0.3970 | Tarreg Loss: 4.384836 | Total Loss: 4.7818 | Val Loss: 193.8118 | Raw Qini: 0.7907 | EMA Trend: 0.7483 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/150 | Base Loss: 0.4597 | Tarreg Loss: 4.417722 | Total Loss: 4.8775 | Val Loss: 193.7240 | Raw Qini: 0.7815 | EMA Trend: 0.7533 | ✓ above trend but not peak (patience: 1/20)
Epoch 6/150 | Base Loss: 0.5271 | Tarreg Loss: 3.718737 | Total Loss: 4.2458 | Val Loss: 193.6305 | Raw Qini: 0.7703 | EMA Trend: 0.7558 | ✓ above trend but not peak (patience: 2/20)
Epoch 7/150 | Base Loss: 0.7385 | Tarreg Loss: 3.668477 | Total Loss: 4.4070 | Val Loss: 193.5534 | Raw Qini: 0.7733 | EMA Trend: 0.7585 | ✓ above trend but not peak (patience: 3/20)
Epoch 8/150 | Base Loss: 1.0938 | Tarreg Loss: 4.236148 | Total Loss: 5.3300 | Val Loss: 193.5878 | Raw Qini: 0.7860 | EMA Trend: 0.7626 | ✓ above trend but not peak (patience: 4/20)
Epoch 9/150 | Base Loss: 1.8235 | Tarreg Loss: 3.039379 | Total Loss: 4.8628 | Val Loss: 193.8859 | Raw Qini: 0.8029 | EMA Trend: 0.7686 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/150 | Base Loss: 3.0802 | Tarreg Loss: 2.937784 | Total Loss: 6.0180 | Val Loss: 194.3540 | Raw Qini: 0.8278 | EMA Trend: 0.7775 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/150 | Base Loss: 3.1805 | Tarreg Loss: 2.770645 | Total Loss: 5.9511 | Val Loss: 194.4216 | Raw Qini: 0.8437 | EMA Trend: 0.7874 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/150 | Base Loss: 3.9881 | Tarreg Loss: 2.266862 | Total Loss: 6.2550 | Val Loss: 194.1085 | Raw Qini: 0.8523 | EMA Trend: 0.7972 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/150 | Base Loss: 3.3795 | Tarreg Loss: 2.247021 | Total Loss: 5.6265 | Val Loss: 193.8244 | Raw Qini: 0.8659 | EMA Trend: 0.8075 | ⭐ NEW BEST (peak ≥ trend)
Epoch 14/150 | Base Loss: 3.0954 | Tarreg Loss: 3.169122 | Total Loss: 6.2646 | Val Loss: 193.7173 | Raw Qini: 0.8851 | EMA Trend: 0.8191 | ⭐ NEW BEST (peak ≥ trend)
Epoch 15/150 | Base Loss: 2.3741 | Tarreg Loss: 3.447477 | Total Loss: 5.8216 | Val Loss: 193.6829 | Raw Qini: 0.8946 | EMA Trend: 0.8304 | ⭐ NEW BEST (peak ≥ trend)
Epoch 16/150 | Base Loss: 2.7613 | Tarreg Loss: 3.071695 | Total Loss: 5.8330 | Val Loss: 193.7791 | Raw Qini: 0.9127 | EMA Trend: 0.8428 | ⭐ NEW BEST (peak ≥ trend)
Epoch 17/150 | Base Loss: 3.0527 | Tarreg Loss: 2.826626 | Total Loss: 5.8793 | Val Loss: 193.8368 | Raw Qini: 0.9215 | EMA Trend: 0.8546 | ⭐ NEW BEST (peak ≥ trend)
Epoch 18/150 | Base Loss: 3.3033 | Tarreg Loss: 2.973783 | Total Loss: 6.2770 | Val Loss: 193.8907 | Raw Qini: 0.9075 | EMA Trend: 0.8625 | ✓ above trend but not peak (patience: 1/20)
Epoch 19/150 | Base Loss: 2.9880 | Tarreg Loss: 2.301133 | Total Loss: 5.2891 | Val Loss: 193.8708 | Raw Qini: 0.9101 | EMA Trend: 0.8697 | ✓ above trend but not peak (patience: 2/20)
Epoch 20/150 | Base Loss: 3.0789 | Tarreg Loss: 3.039835 | Total Loss: 6.1187 | Val Loss: 193.8672 | Raw Qini: 0.9228 | EMA Trend: 0.8776 | ⭐ NEW BEST (peak ≥ trend)
Epoch 21/150 | Base Loss: 2.5210 | Tarreg Loss: 2.026693 | Total Loss: 4.5477 | Val Loss: 193.8583 | Raw Qini: 0.9376 | EMA Trend: 0.8866 | ⭐ NEW BEST (peak ≥ trend)
Epoch 22/150 | Base Loss: 2.7746 | Tarreg Loss: 3.197242 | Total Loss: 5.9719 | Val Loss: 193.8295 | Raw Qini: 0.9435 | EMA Trend: 0.8951 | ⭐ NEW BEST (peak ≥ trend)
Epoch 23/150 | Base Loss: 594.1160 | Tarreg Loss: 173.660767 | Total Loss: 767.7768 | Val Loss: 193.8700 | Raw Qini: 0.9501 | EMA Trend: 0.9034 | ⭐ NEW BEST (peak ≥ trend)
Epoch 24/150 | Base Loss: 3.2057 | Tarreg Loss: 2.583894 | Total Loss: 5.7896 | Val Loss: 193.9816 | Raw Qini: 0.9451 | EMA Trend: 0.9096 | ✓ above trend but not peak (patience: 1/20)
Epoch 25/150 | Base Loss: 156.6505 | Tarreg Loss: 34.270981 | Total Loss: 190.9215 | Val Loss: 194.0665 | Raw Qini: 0.9275 | EMA Trend: 0.9123 | ✓ above trend but not peak (patience: 2/20)
Epoch 26/150 | Base Loss: 3.2192 | Tarreg Loss: 2.371166 | Total Loss: 5.5904 | Val Loss: 194.2541 | Raw Qini: 0.9736 | EMA Trend: 0.9215 | ⭐ NEW BEST (peak ≥ trend)
Epoch 27/150 | Base Loss: 3.3906 | Tarreg Loss: 2.711963 | Total Loss: 6.1026 | Val Loss: 194.1989 | Raw Qini: 1.0283 | EMA Trend: 0.9375 | ⭐ NEW BEST (peak ≥ trend)
Epoch 28/150 | Base Loss: 2.6983 | Tarreg Loss: 3.774907 | Total Loss: 6.4732 | Val Loss: 194.0086 | Raw Qini: 1.0781 | EMA Trend: 0.9586 | ⭐ NEW BEST (peak ≥ trend)
Epoch 29/150 | Base Loss: 4.4550 | Tarreg Loss: 2.749805 | Total Loss: 7.2048 | Val Loss: 193.9292 | Raw Qini: 1.0931 | EMA Trend: 0.9788 | ⭐ NEW BEST (peak ≥ trend)
Epoch 30/150 | Base Loss: 2.9146 | Tarreg Loss: 3.471572 | Total Loss: 6.3862 | Val Loss: 193.8866 | Raw Qini: 1.0997 | EMA Trend: 0.9969 | ⭐ NEW BEST (peak ≥ trend)
Epoch 31/150 | Base Loss: 3383.6226 | Tarreg Loss: 1057.624756 | Total Loss: 4441.2471 | Val Loss: 193.9267 | Raw Qini: 1.0552 | EMA Trend: 1.0057 | ✓ above trend but not peak (patience: 1/20)
Epoch 32/150 | Base Loss: 3.0011 | Tarreg Loss: 3.060066 | Total Loss: 6.0611 | Val Loss: 194.1850 | Raw Qini: 1.0756 | EMA Trend: 1.0162 | ✓ above trend but not peak (patience: 2/20)
Epoch 33/150 | Base Loss: 4.4824 | Tarreg Loss: 2.316880 | Total Loss: 6.7993 | Val Loss: 194.2963 | Raw Qini: 1.0923 | EMA Trend: 1.0276 | ✓ above trend but not peak (patience: 3/20)
Epoch 34/150 | Base Loss: 526.2552 | Tarreg Loss: 111.862610 | Total Loss: 638.1178 | Val Loss: 194.1889 | Raw Qini: 1.1147 | EMA Trend: 1.0406 | ⭐ NEW BEST (peak ≥ trend)
Epoch 35/150 | Base Loss: 3.5814 | Tarreg Loss: 1.780799 | Total Loss: 5.3622 | Val Loss: 194.1218 | Raw Qini: 1.1327 | EMA Trend: 1.0545 | ⭐ NEW BEST (peak ≥ trend)
Epoch 36/150 | Base Loss: 2.5551 | Tarreg Loss: 2.999226 | Total Loss: 5.5544 | Val Loss: 194.1497 | Raw Qini: 1.1271 | EMA Trend: 1.0653 | ✓ above trend but not peak (patience: 1/20)
Epoch 37/150 | Base Loss: 3.6027 | Tarreg Loss: 2.297644 | Total Loss: 5.9003 | Val Loss: 194.2374 | Raw Qini: 1.1051 | EMA Trend: 1.0713 | ✓ above trend but not peak (patience: 2/20)
Epoch 38/150 | Base Loss: 18433.7168 | Tarreg Loss: 4837.102051 | Total Loss: 23270.8184 | Val Loss: 194.1762 | Raw Qini: 1.1197 | EMA Trend: 1.0786 | ✓ above trend but not peak (patience: 3/20)
Epoch 39/150 | Base Loss: 3.4824 | Tarreg Loss: 1.973090 | Total Loss: 5.4555 | Val Loss: 194.1958 | Raw Qini: 1.1390 | EMA Trend: 1.0876 | ⭐ NEW BEST (peak ≥ trend)
Epoch 40/150 | Base Loss: 4.8932 | Tarreg Loss: 2.656794 | Total Loss: 7.5500 | Val Loss: 194.4454 | Raw Qini: 1.1011 | EMA Trend: 1.0897 | ✓ above trend but not peak (patience: 1/20)
Epoch 41/150 | Base Loss: 4.3870 | Tarreg Loss: 2.367429 | Total Loss: 6.7544 | Val Loss: 194.5412 | Raw Qini: 1.0718 | EMA Trend: 1.0870 | (patience: 2/20)
Epoch 42/150 | Base Loss: 3.8106 | Tarreg Loss: 1.554227 | Total Loss: 5.3649 | Val Loss: 194.3217 | Raw Qini: 1.0865 | EMA Trend: 1.0869 | (patience: 3/20)
Epoch 43/150 | Base Loss: 3.0978 | Tarreg Loss: 2.789966 | Total Loss: 5.8878 | Val Loss: 194.3528 | Raw Qini: 1.0770 | EMA Trend: 1.0854 | (patience: 4/20)
Epoch 44/150 | Base Loss: 3.9316 | Tarreg Loss: 2.960630 | Total Loss: 6.8922 | Val Loss: 194.4775 | Raw Qini: 1.0480 | EMA Trend: 1.0798 | (patience: 5/20)
Epoch 45/150 | Base Loss: 4.8997 | Tarreg Loss: 2.085713 | Total Loss: 6.9854 | Val Loss: 194.6947 | Raw Qini: 1.0032 | EMA Trend: 1.0683 | (patience: 6/20)
Epoch 46/150 | Base Loss: 2.4350 | Tarreg Loss: 2.423166 | Total Loss: 4.8582 | Val Loss: 194.6479 | Raw Qini: 0.9989 | EMA Trend: 1.0579 | (patience: 7/20)
Epoch 47/150 | Base Loss: 3.7007 | Tarreg Loss: 3.497113 | Total Loss: 7.1978 | Val Loss: 194.5935 | Raw Qini: 1.0022 | EMA Trend: 1.0495 | (patience: 8/20)
Epoch 48/150 | Base Loss: 3.5054 | Tarreg Loss: 1.938206 | Total Loss: 5.4436 | Val Loss: 194.6507 | Raw Qini: 0.9766 | EMA Trend: 1.0386 | (patience: 9/20)
Epoch 49/150 | Base Loss: 4.5602 | Tarreg Loss: 2.809454 | Total Loss: 7.3696 | Val Loss: 194.7373 | Raw Qini: 0.9735 | EMA Trend: 1.0288 | (patience: 10/20)
Epoch 50/150 | Base Loss: 2.6183 | Tarreg Loss: 2.548157 | Total Loss: 5.1665 | Val Loss: 194.7799 | Raw Qini: 0.9455 | EMA Trend: 1.0163 | (patience: 11/20)
Epoch 51/150 | Base Loss: 3.7409 | Tarreg Loss: 2.384945 | Total Loss: 6.1259 | Val Loss: 194.8385 | Raw Qini: 0.9308 | EMA Trend: 1.0035 | (patience: 12/20)
Epoch 52/150 | Base Loss: 4.2236 | Tarreg Loss: 2.284896 | Total Loss: 6.5085 | Val Loss: 194.9026 | Raw Qini: 0.9277 | EMA Trend: 0.9921 | (patience: 13/20)
Epoch 53/150 | Base Loss: 4.2413 | Tarreg Loss: 1.632498 | Total Loss: 5.8738 | Val Loss: 194.9662 | Raw Qini: 0.8953 | EMA Trend: 0.9776 | (patience: 14/20)
Epoch 54/150 | Base Loss: 3.7039 | Tarreg Loss: 2.723604 | Total Loss: 6.4275 | Val Loss: 194.9234 | Raw Qini: 0.8629 | EMA Trend: 0.9604 | (patience: 15/20)
Epoch 55/150 | Base Loss: 2.2796 | Tarreg Loss: 2.158091 | Total Loss: 4.4377 | Val Loss: 195.0838 | Raw Qini: 0.8547 | EMA Trend: 0.9445 | (patience: 16/20)
Epoch 56/150 | Base Loss: 2.3396 | Tarreg Loss: 3.608362 | Total Loss: 5.9479 | Val Loss: 194.9666 | Raw Qini: 0.8489 | EMA Trend: 0.9302 | (patience: 17/20)
Epoch 57/150 | Base Loss: 4.9114 | Tarreg Loss: 5.031521 | Total Loss: 9.9429 | Val Loss: 195.3030 | Raw Qini: 0.8345 | EMA Trend: 0.9158 | (patience: 18/20)
Epoch 58/150 | Base Loss: 1977.2085 | Tarreg Loss: 439.503021 | Total Loss: 2416.7114 | Val Loss: 195.5701 | Raw Qini: 0.8238 | EMA Trend: 0.9020 | (patience: 19/20)
Epoch 59/150 | Base Loss: 4190.1445 | Tarreg Loss: 1208.799683 | Total Loss: 5398.9443 | Val Loss: 195.5498 | Raw Qini: 0.8069 | EMA Trend: 0.8878 | (patience: 20/20)

🛑 Early stopping triggered at epoch 59!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 39
   Best Raw Qini: 1.1390
   Final EMA Trend: 0.8878
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 1874
Locked random seed: 902745
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Base Loss: 0.3740 | Tarreg Loss: 1.737788 | Total Loss: 2.1118 | Val Loss: 193.8739 | Raw Qini: 0.4637 | EMA Trend: 0.4637 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Base Loss: 0.3771 | Tarreg Loss: 1.613935 | Total Loss: 1.9910 | Val Loss: 193.8109 | Raw Qini: 0.7517 | EMA Trend: 0.5069 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Base Loss: 0.3988 | Tarreg Loss: 1.570119 | Total Loss: 1.9689 | Val Loss: 193.7367 | Raw Qini: 0.8945 | EMA Trend: 0.5650 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Base Loss: 0.4258 | Tarreg Loss: 1.344775 | Total Loss: 1.7706 | Val Loss: 193.6411 | Raw Qini: 0.9827 | EMA Trend: 0.6277 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/150 | Base Loss: 0.5021 | Tarreg Loss: 1.611344 | Total Loss: 2.1135 | Val Loss: 193.5225 | Raw Qini: 1.0334 | EMA Trend: 0.6886 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/150 | Base Loss: 0.6068 | Tarreg Loss: 1.307186 | Total Loss: 1.9139 | Val Loss: 193.3985 | Raw Qini: 1.0418 | EMA Trend: 0.7415 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/150 | Base Loss: 0.8412 | Tarreg Loss: 1.214611 | Total Loss: 2.0558 | Val Loss: 193.3015 | Raw Qini: 1.0655 | EMA Trend: 0.7901 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/150 | Base Loss: 1.3657 | Tarreg Loss: 1.095473 | Total Loss: 2.4611 | Val Loss: 193.3001 | Raw Qini: 1.0930 | EMA Trend: 0.8356 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/150 | Base Loss: 1.8674 | Tarreg Loss: 1.420812 | Total Loss: 3.2882 | Val Loss: 193.4435 | Raw Qini: 1.1114 | EMA Trend: 0.8769 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/150 | Base Loss: 2.4650 | Tarreg Loss: 0.794751 | Total Loss: 3.2597 | Val Loss: 193.6061 | Raw Qini: 1.1691 | EMA Trend: 0.9208 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/150 | Base Loss: 2.5014 | Tarreg Loss: 0.591610 | Total Loss: 3.0931 | Val Loss: 193.6470 | Raw Qini: 1.2069 | EMA Trend: 0.9637 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/150 | Base Loss: 488.3579 | Tarreg Loss: 186.905945 | Total Loss: 675.2639 | Val Loss: 193.5513 | Raw Qini: 1.2305 | EMA Trend: 1.0037 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/150 | Base Loss: 3.0814 | Tarreg Loss: 0.748422 | Total Loss: 3.8299 | Val Loss: 193.5535 | Raw Qini: 1.2018 | EMA Trend: 1.0334 | ✓ above trend but not peak (patience: 1/20)
Epoch 14/150 | Base Loss: 4.1154 | Tarreg Loss: 1.328277 | Total Loss: 5.4437 | Val Loss: 193.4450 | Raw Qini: 1.1788 | EMA Trend: 1.0552 | ✓ above trend but not peak (patience: 2/20)
Epoch 15/150 | Base Loss: 2.1618 | Tarreg Loss: 0.992537 | Total Loss: 3.1543 | Val Loss: 193.3913 | Raw Qini: 1.1536 | EMA Trend: 1.0700 | ✓ above trend but not peak (patience: 3/20)
Epoch 16/150 | Base Loss: 2.0288 | Tarreg Loss: 1.104018 | Total Loss: 3.1328 | Val Loss: 193.3770 | Raw Qini: 1.1408 | EMA Trend: 1.0806 | ✓ above trend but not peak (patience: 4/20)
Epoch 17/150 | Base Loss: 2.4892 | Tarreg Loss: 1.330210 | Total Loss: 3.8194 | Val Loss: 193.3658 | Raw Qini: 1.1208 | EMA Trend: 1.0866 | ✓ above trend but not peak (patience: 5/20)
Epoch 18/150 | Base Loss: 5258.7646 | Tarreg Loss: 1779.512939 | Total Loss: 7038.2773 | Val Loss: 193.4528 | Raw Qini: 1.1012 | EMA Trend: 1.0888 | ✓ above trend but not peak (patience: 6/20)
Epoch 19/150 | Base Loss: 2.4604 | Tarreg Loss: 1.421898 | Total Loss: 3.8823 | Val Loss: 193.6033 | Raw Qini: 1.0935 | EMA Trend: 1.0895 | ✓ above trend but not peak (patience: 7/20)
Epoch 20/150 | Base Loss: 2.6603 | Tarreg Loss: 0.910337 | Total Loss: 3.5707 | Val Loss: 193.6322 | Raw Qini: 1.0978 | EMA Trend: 1.0907 | ✓ above trend but not peak (patience: 8/20)
Epoch 21/150 | Base Loss: 2.4178 | Tarreg Loss: 0.812824 | Total Loss: 3.2306 | Val Loss: 193.5794 | Raw Qini: 1.1051 | EMA Trend: 1.0929 | ✓ above trend but not peak (patience: 9/20)
Epoch 22/150 | Base Loss: 2.5097 | Tarreg Loss: 1.440524 | Total Loss: 3.9502 | Val Loss: 193.5004 | Raw Qini: 1.1168 | EMA Trend: 1.0965 | ✓ above trend but not peak (patience: 10/20)
Epoch 23/150 | Base Loss: 1.8647 | Tarreg Loss: 1.260689 | Total Loss: 3.1254 | Val Loss: 193.4154 | Raw Qini: 1.1299 | EMA Trend: 1.1015 | ✓ above trend but not peak (patience: 11/20)
Epoch 24/150 | Base Loss: 2.1039 | Tarreg Loss: 0.879116 | Total Loss: 2.9830 | Val Loss: 193.4147 | Raw Qini: 1.1349 | EMA Trend: 1.1065 | ✓ above trend but not peak (patience: 12/20)
Epoch 25/150 | Base Loss: 2.7517 | Tarreg Loss: 0.833999 | Total Loss: 3.5857 | Val Loss: 193.4422 | Raw Qini: 1.1430 | EMA Trend: 1.1120 | ✓ above trend but not peak (patience: 13/20)
Epoch 26/150 | Base Loss: 2.4530 | Tarreg Loss: 1.210708 | Total Loss: 3.6637 | Val Loss: 193.4993 | Raw Qini: 1.1627 | EMA Trend: 1.1196 | ✓ above trend but not peak (patience: 14/20)
Epoch 27/150 | Base Loss: 3.0257 | Tarreg Loss: 1.126014 | Total Loss: 4.1517 | Val Loss: 193.5962 | Raw Qini: 1.1680 | EMA Trend: 1.1269 | ✓ above trend but not peak (patience: 15/20)
Epoch 28/150 | Base Loss: 1092.7976 | Tarreg Loss: 301.677917 | Total Loss: 1394.4756 | Val Loss: 193.6502 | Raw Qini: 1.1603 | EMA Trend: 1.1319 | ✓ above trend but not peak (patience: 16/20)
Epoch 29/150 | Base Loss: 2.9554 | Tarreg Loss: 1.310943 | Total Loss: 4.2663 | Val Loss: 193.8219 | Raw Qini: 1.1376 | EMA Trend: 1.1327 | ✓ above trend but not peak (patience: 17/20)
Epoch 30/150 | Base Loss: 2.9220 | Tarreg Loss: 1.164774 | Total Loss: 4.0868 | Val Loss: 193.8926 | Raw Qini: 1.1218 | EMA Trend: 1.1311 | (patience: 18/20)
Epoch 31/150 | Base Loss: 3.4602 | Tarreg Loss: 0.932035 | Total Loss: 4.3922 | Val Loss: 193.8268 | Raw Qini: 1.1234 | EMA Trend: 1.1299 | (patience: 19/20)
Epoch 32/150 | Base Loss: 2.2835 | Tarreg Loss: 1.303482 | Total Loss: 3.5870 | Val Loss: 193.8002 | Raw Qini: 1.1276 | EMA Trend: 1.1296 | (patience: 20/20)

🛑 Early stopping triggered at epoch 32!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 12
   Best Raw Qini: 1.2305
   Final EMA Trend: 1.1296
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 902745
Locked random seed: 1
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Base Loss: 0.3535 | Tarreg Loss: 0.275780 | Total Loss: 0.6293 | Val Loss: 194.2418 | Raw Qini: 1.1679 | EMA Trend: 1.1679 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Base Loss: 0.3440 | Tarreg Loss: 0.264724 | Total Loss: 0.6088 | Val Loss: 194.1549 | Raw Qini: 1.1418 | EMA Trend: 1.1640 | (patience: 1/20)
Epoch 3/150 | Base Loss: 0.3537 | Tarreg Loss: 0.267491 | Total Loss: 0.6212 | Val Loss: 194.0542 | Raw Qini: 0.8297 | EMA Trend: 1.1138 | (patience: 2/20)
Epoch 4/150 | Base Loss: 15190.1523 | Tarreg Loss: 2543.465332 | Total Loss: 17733.6172 | Val Loss: 193.9240 | Raw Qini: 0.7820 | EMA Trend: 1.0641 | (patience: 3/20)
Epoch 5/150 | Base Loss: 0.3572 | Tarreg Loss: 0.224238 | Total Loss: 0.5814 | Val Loss: 193.7502 | Raw Qini: 0.8174 | EMA Trend: 1.0270 | (patience: 4/20)
Epoch 6/150 | Base Loss: 0.4901 | Tarreg Loss: 0.381318 | Total Loss: 0.8714 | Val Loss: 193.5506 | Raw Qini: 0.8525 | EMA Trend: 1.0009 | (patience: 5/20)
Epoch 7/150 | Base Loss: 0.5446 | Tarreg Loss: 0.286155 | Total Loss: 0.8308 | Val Loss: 193.3446 | Raw Qini: 0.9061 | EMA Trend: 0.9867 | (patience: 6/20)
Epoch 8/150 | Base Loss: 0.7697 | Tarreg Loss: 0.478750 | Total Loss: 1.2484 | Val Loss: 193.1586 | Raw Qini: 0.9448 | EMA Trend: 0.9804 | (patience: 7/20)
Epoch 9/150 | Base Loss: 1.4095 | Tarreg Loss: 0.437172 | Total Loss: 1.8467 | Val Loss: 193.0541 | Raw Qini: 0.9557 | EMA Trend: 0.9767 | (patience: 8/20)
Epoch 10/150 | Base Loss: 1.7204 | Tarreg Loss: 0.635122 | Total Loss: 2.3556 | Val Loss: 193.0786 | Raw Qini: 0.9412 | EMA Trend: 0.9714 | (patience: 9/20)
Epoch 11/150 | Base Loss: 2.5593 | Tarreg Loss: 0.485821 | Total Loss: 3.0451 | Val Loss: 193.1996 | Raw Qini: 0.9241 | EMA Trend: 0.9643 | (patience: 10/20)
Epoch 12/150 | Base Loss: 2.1382 | Tarreg Loss: 0.422407 | Total Loss: 2.5606 | Val Loss: 193.2417 | Raw Qini: 0.9012 | EMA Trend: 0.9548 | (patience: 11/20)
Epoch 13/150 | Base Loss: 2.6162 | Tarreg Loss: 0.436170 | Total Loss: 3.0524 | Val Loss: 193.2297 | Raw Qini: 0.8885 | EMA Trend: 0.9449 | (patience: 12/20)
Epoch 14/150 | Base Loss: 2.9768 | Tarreg Loss: 0.607217 | Total Loss: 3.5840 | Val Loss: 193.1622 | Raw Qini: 0.8710 | EMA Trend: 0.9338 | (patience: 13/20)
Epoch 15/150 | Base Loss: 1.7341 | Tarreg Loss: 0.450602 | Total Loss: 2.1847 | Val Loss: 193.0971 | Raw Qini: 0.8342 | EMA Trend: 0.9188 | (patience: 14/20)
Epoch 16/150 | Base Loss: 2121.1138 | Tarreg Loss: 770.386841 | Total Loss: 2891.5005 | Val Loss: 193.0919 | Raw Qini: 0.8312 | EMA Trend: 0.9057 | (patience: 15/20)
Epoch 17/150 | Base Loss: 2.3221 | Tarreg Loss: 0.714915 | Total Loss: 3.0370 | Val Loss: 193.1292 | Raw Qini: 0.8020 | EMA Trend: 0.8901 | (patience: 16/20)
Epoch 18/150 | Base Loss: 2.2188 | Tarreg Loss: 0.526732 | Total Loss: 2.7455 | Val Loss: 193.1602 | Raw Qini: 0.7806 | EMA Trend: 0.8737 | (patience: 17/20)
Epoch 19/150 | Base Loss: 1.4746 | Tarreg Loss: 0.800360 | Total Loss: 2.2750 | Val Loss: 193.1566 | Raw Qini: 0.7773 | EMA Trend: 0.8593 | (patience: 18/20)
Epoch 20/150 | Base Loss: 2.7022 | Tarreg Loss: 0.472402 | Total Loss: 3.1746 | Val Loss: 193.1616 | Raw Qini: 0.7720 | EMA Trend: 0.8462 | (patience: 19/20)
Epoch 21/150 | Base Loss: 1.4272 | Tarreg Loss: 0.169954 | Total Loss: 1.5972 | Val Loss: 193.1945 | Raw Qini: 0.7844 | EMA Trend: 0.8369 | (patience: 20/20)
Epoch 22/150 | Base Loss: 293.3938 | Tarreg Loss: 27.968239 | Total Loss: 321.3620 | Val Loss: 193.2228 | Raw Qini: 0.7995 | EMA Trend: 0.8313 | (patience: 21/20)
Epoch 23/150 | Base Loss: 2.1078 | Tarreg Loss: 0.440309 | Total Loss: 2.5481 | Val Loss: 193.2988 | Raw Qini: 0.8204 | EMA Trend: 0.8296 | (patience: 22/20)
Epoch 24/150 | Base Loss: 2.4212 | Tarreg Loss: 0.429728 | Total Loss: 2.8509 | Val Loss: 193.3139 | Raw Qini: 0.8236 | EMA Trend: 0.8287 | (patience: 23/20)
Epoch 25/150 | Base Loss: 1.9274 | Tarreg Loss: 0.505541 | Total Loss: 2.4330 | Val Loss: 193.2651 | Raw Qini: 0.8020 | EMA Trend: 0.8247 | (patience: 24/20)
Epoch 26/150 | Base Loss: 1.6472 | Tarreg Loss: 0.356205 | Total Loss: 2.0034 | Val Loss: 193.2709 | Raw Qini: 0.7661 | EMA Trend: 0.8159 | (patience: 25/20)
Epoch 27/150 | Base Loss: 2.6843 | Tarreg Loss: 0.731519 | Total Loss: 3.4158 | Val Loss: 193.3052 | Raw Qini: 0.7599 | EMA Trend: 0.8075 | (patience: 26/20)
Epoch 28/150 | Base Loss: 1.8330 | Tarreg Loss: 0.423389 | Total Loss: 2.2563 | Val Loss: 193.3489 | Raw Qini: 0.7456 | EMA Trend: 0.7982 | (patience: 27/20)
Epoch 29/150 | Base Loss: 1.5134 | Tarreg Loss: 0.271853 | Total Loss: 1.7852 | Val Loss: 193.3846 | Raw Qini: 0.7563 | EMA Trend: 0.7920 | (patience: 28/20)
Epoch 30/150 | Base Loss: 1103.5852 | Tarreg Loss: 335.054749 | Total Loss: 1438.6399 | Val Loss: 193.4559 | Raw Qini: 0.7650 | EMA Trend: 0.7879 | (patience: 29/20)
Epoch 31/150 | Base Loss: 1.7063 | Tarreg Loss: 0.467498 | Total Loss: 2.1738 | Val Loss: 193.5160 | Raw Qini: 0.7847 | EMA Trend: 0.7874 | (patience: 30/20)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 1
   Best Raw Qini: 1.1679
   Final EMA Trend: 0.7874
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 1

=====================================================================================
                            CHI TIẾT TỪNG SEED (TEST SET)
=====================================================================================
  Seed   AUUC   AUQC   Lift   KRCC ATE_Err
412312 0.8139 0.8185 0.9069 0.0936  0.4428
    42 0.4688 0.4665 0.5514 0.0679  0.4381
  1874 0.7946 0.7938 1.2402 0.2124  0.9561
902745 0.7543 0.7494 1.2591 0.1310  0.6944
     1 0.8948 0.8959 1.0983 0.1475  0.4327
=====================================================================================
                        KẾT QUẢ TRUNG BÌNH TEST (MEAN ± STD)
-------------------------------------------------------------------------------------
AUUC      : 0.7453 ± 0.1628
AUQC      : 0.7448 ± 0.1644
Lift      : 1.0112 ± 0.2932
KRCC      : 0.1305 ± 0.0554
ATE_Err   : 0.5928 ± 0.2315
=====================================================================================

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)