Import libraries

In [10]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from dragonnet import Dragonnet
import sys
from pathlib import Path
project_root = Path("/benchmark-conversion-vs-revenue-uplift-modeling")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [11]:
%time train_df = pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Men/train_men.csv")
%time test_df =  pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Men/test_men.csv")
%time val_df = pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Men/val_men.csv")

CPU times: user 25.9 ms, sys: 4.11 ms, total: 30 ms
Wall time: 29.8 ms
CPU times: user 10.3 ms, sys: 5.05 ms, total: 15.4 ms
Wall time: 15.4 ms
CPU times: user 4.39 ms, sys: 1.97 ms, total: 6.36 ms
Wall time: 6.36 ms

In [12]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['spend']
treatment_feature = ['treatment']

In [13]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [14]:
print('X_train[:10]', X_train[:1].astype(float))

X_train[:10] [[-0.21435131  1.6331766   1.0667411   0.90252386 -1.1010233   1.07039981
   1.00043033  2.70003843 -0.88552759 -0.88616046]]

In [15]:
print('y_train[:10]', y_train[:1].astype(float))

y_train[:10] [[0.]]

In [16]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25567, 10]); y=torch.Size([25567, 1]); t=torch.Size([25567, 1])
Shape of val: x=torch.Size([4262, 10]); y=torch.Size([4262, 1]); t=torch.Size([4262, 1])
Shape of test: x=torch.Size([12784, 10]); y=torch.Size([12784, 1]); t=torch.Size([12784, 1])

In [17]:
epochs = 70
lr = 5e-5
wd = 1e-5
alpha = 1.0
beta = 1.0
early_stop_metric = "qini"
ema = True
ema_alpha = 0.15
patience = 15
shared_dropout = 0
outcome_dropout = 0 
shared_hidden = 200
outcome_hidden = 100
early_stop_start = 30
activation = torch.nn.ReLU
print (f" epochs = {epochs}")
print (f" learning rate = {lr}")
print (f" weight decay = {wd}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" shared hidden = {shared_hidden}")
print (f" outcome hidden = {outcome_hidden}")
print (f" early stop start = {early_stop_start}")

 epochs = 70
 learning rate = 5e-05
 weight decay = 1e-05
 early stop = qini
 use ema = True
 ema alpha = 0.15
 patience = 15
 shared hidden = 200
 outcome hidden = 100
 early stop start = 30

In [18]:
import pandas as pd
import numpy as np
import torch
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 5e-5, 5e-4, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-4, log=True)
    grid_alpha = trial.suggest_categorical("alpha", [0.1, 0.5, 1.0])
    grid_beta = trial.suggest_categorical("beta", [0.1, 0.5, 1.0])

    val_scores = []
    for SEED in seeds:
        seed_everything(SEED)

        dragonnet = Dragonnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            alpha=grid_alpha,
            beta=grid_beta,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=shared_hidden,
            outcome_hidden=outcome_hidden,
            outcome_droupout=outcome_dropout,
            shared_dropout=shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
            activation=activation
        )

        # Silence Dragonnet epoch logs
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            dragonnet.fit(train_loader, val_loader)

        x_val_device = x_men_val_t.to(device)
        y0_val_p, y1_val_p, _, _ = dragonnet.predict(x_val_device)
        uplift_val = (y1_val_p - y0_val_p).detach().cpu().numpy().flatten()
        y_val_true_np = y_men_val_t.detach().cpu().numpy().flatten()
        t_val_true_np = t_men_val_t.detach().cpu().numpy().flatten()

        current_val_auqc = auqc(y_val_true_np, t_val_true_np, uplift_val, bins=100, plot=False)
        val_scores.append(current_val_auqc)

    mean_val_auqc = float(np.mean(val_scores))
    std_val_auqc = float(np.std(val_scores, ddof=1)) if len(val_scores) > 1 else 0.0
    trial.set_user_attr("std_Val_AUQC", std_val_auqc)
    return mean_val_auqc

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

# 2. Persist search results in notebook variables
trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": t.params["lr"],
        "weight_decay": t.params["weight_decay"],
        "alpha": t.params["alpha"],
        "beta": t.params["beta"],
        "mean_Val_AUQC": float(t.value),
        "std_Val_AUQC": float(t.user_attrs.get("std_Val_AUQC", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_Val_AUQC", ascending=False).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "alpha": float(best_params["alpha"]),
    "beta": float(best_params["beta"]),
    "mean_Val_AUQC": float(study.best_value),
    "std_Val_AUQC": float(study.best_trial.user_attrs.get("std_Val_AUQC", np.nan))
})

  0%|          | 0/50 [00:00<?, ?it/s]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 0. Best value: 0.807496:   2%|▏         | 1/50 [01:02<51:04, 62.54s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 1. Best value: 0.814564:   4%|▍         | 2/50 [01:57<46:19, 57.90s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 0.818935:   6%|▌         | 3/50 [02:43<41:22, 52.81s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 3. Best value: 0.821187:   8%|▊         | 4/50 [03:30<38:32, 50.27s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 3. Best value: 0.821187:  10%|█         | 5/50 [05:07<50:31, 67.36s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 3. Best value: 0.821187:  12%|█▏        | 6/50 [05:58<45:08, 61.56s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 3. Best value: 0.821187:  14%|█▍        | 7/50 [06:59<44:05, 61.53s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 7. Best value: 0.830707:  16%|█▌        | 8/50 [07:49<40:20, 57.63s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 8. Best value: 0.839262:  18%|█▊        | 9/50 [08:40<37:59, 55.61s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 8. Best value: 0.839262:  20%|██        | 10/50 [09:44<38:54, 58.35s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 8. Best value: 0.839262:  22%|██▏       | 11/50 [11:25<46:22, 71.35s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 11. Best value: 0.845266:  24%|██▍       | 12/50 [12:15<41:00, 64.74s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 11. Best value: 0.845266:  26%|██▌       | 13/50 [13:05<37:17, 60.49s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 13. Best value: 0.846582:  28%|██▊       | 14/50 [13:55<34:24, 57.35s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 13. Best value: 0.846582:  30%|███       | 15/50 [14:46<32:10, 55.15s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 13. Best value: 0.846582:  32%|███▏      | 16/50 [16:14<36:53, 65.11s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 13. Best value: 0.846582:  34%|███▍      | 17/50 [17:14<34:59, 63.61s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 17. Best value: 0.848201:  36%|███▌      | 18/50 [18:04<31:44, 59.50s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 17. Best value: 0.848201:  38%|███▊      | 19/50 [19:52<38:15, 74.06s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 17. Best value: 0.848201:  40%|████      | 20/50 [20:45<33:53, 67.80s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 17. Best value: 0.848201:  42%|████▏     | 21/50 [22:02<34:04, 70.51s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 17. Best value: 0.848201:  44%|████▍     | 22/50 [22:51<29:54, 64.07s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 17. Best value: 0.848201:  46%|████▌     | 23/50 [23:43<27:12, 60.47s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  48%|████▊     | 24/50 [24:32<24:41, 56.97s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  50%|█████     | 25/50 [25:30<23:53, 57.33s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  52%|█████▏    | 26/50 [26:22<22:19, 55.81s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  54%|█████▍    | 27/50 [27:13<20:45, 54.17s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  56%|█████▌    | 28/50 [28:12<20:27, 55.78s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  58%|█████▊    | 29/50 [29:01<18:47, 53.71s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  60%|██████    | 30/50 [29:51<17:33, 52.67s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  62%|██████▏   | 31/50 [30:44<16:44, 52.85s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  64%|██████▍   | 32/50 [31:36<15:41, 52.32s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  66%|██████▌   | 33/50 [32:27<14:45, 52.11s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  68%|██████▊   | 34/50 [33:19<13:51, 51.96s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  70%|███████   | 35/50 [34:14<13:14, 52.97s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  72%|███████▏  | 36/50 [35:07<12:19, 52.81s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  74%|███████▍  | 37/50 [35:58<11:21, 52.42s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  76%|███████▌  | 38/50 [36:49<10:22, 51.86s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  78%|███████▊  | 39/50 [37:51<10:06, 55.12s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  80%|████████  | 40/50 [38:44<09:04, 54.45s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  82%|████████▏ | 41/50 [39:42<08:18, 55.44s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  84%|████████▍ | 42/50 [40:30<07:05, 53.21s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  86%|████████▌ | 43/50 [41:20<06:04, 52.11s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  88%|████████▊ | 44/50 [42:08<05:06, 51.09s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  90%|█████████ | 45/50 [43:00<04:16, 51.29s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  92%|█████████▏| 46/50 [43:49<03:22, 50.50s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  94%|█████████▍| 47/50 [44:37<02:29, 49.90s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  96%|█████████▌| 48/50 [45:27<01:39, 49.99s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759:  98%|█████████▊| 49/50 [46:21<00:51, 51.05s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 23. Best value: 0.849759: 100%|██████████| 50/50 [47:13<00:00, 56.68s/it]

In [19]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_AUQC: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 23
Best mean_Val_AUQC: 0.849759
Best params: {'lr': 0.0004813006947602241, 'weight_decay': 1.219863912496383e-05, 'alpha': 0.1, 'beta': 0.1}

Best config table:

         lr  weight_decay  alpha  beta  mean_Val_AUQC  std_Val_AUQC
0  0.000481      0.000012    0.1   0.1       0.849759       0.01948

Top 10 trials:

   trial        lr  weight_decay  alpha  beta  mean_Val_AUQC  std_Val_AUQC
0     23  0.000481      0.000012    0.1   0.1       0.849759      0.019480
1     29  0.000494      0.000024    0.1   0.1       0.849576      0.016550
2     46  0.000497      0.000097    0.1   0.1       0.849487      0.015990
3     31  0.000498      0.000016    0.1   0.1       0.848721      0.017169
4     32  0.000493      0.000016    0.1   0.1       0.848509      0.019917
5     17  0.000495      0.000015    0.1   0.1       0.848201      0.018414
6     21  0.000471      0.000013    0.1   0.1       0.847396      0.019946
7     42  0.000494      0.000019    0.1   0.1       0.847188      0.018942
8     26  0.000492      0.000018    0.1   0.1       0.847050      0.017408
9     13  0.000467      0.000010    1.0   0.1       0.846582      0.018363

In [20]:
import pandas as pd
import numpy as np
import torch

# 1. Evaluate selected config on test set (after tuning)
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

if 'best_cfg' not in globals():
    raise ValueError("best_cfg not found. Run grid-search cell first.")

best_lr = float(best_cfg['lr'])
best_wd = float(best_cfg['weight_decay'])
best_alpha = float(best_cfg['alpha'])
best_beta = float(best_cfg['beta'])

print("Đang đánh giá trên test với best config từ validation:")
print(f"  lr={best_lr:.1e}, weight_decay={best_wd:.1e}, alpha={best_alpha:.1f}, beta={best_beta:.1f}")
print(f"Số seed: {len(seeds)}")

# 2. Loop over seeds for robust test evaluation
for SEED in seeds:
    seed_everything(SEED)

    dragonnet = Dragonnet(
        input_dim=x_men_train_t.shape[1],
        epochs=epochs,
        learning_rate=best_lr,
        alpha=best_alpha,
        beta=best_beta,
        weight_decay=best_wd,
        use_ema=ema,
        ema_alpha=ema_alpha,
        patience=patience,
        shared_hidden=shared_hidden,
        outcome_hidden=outcome_hidden,
        outcome_droupout=outcome_dropout,
        shared_dropout=shared_dropout,
        early_stop_metric=early_stop_metric,
        early_stop_start_epoch=early_stop_start,
        activation=activation
    )

    dragonnet.fit(train_loader, val_loader)

    # Test prediction
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred, _, _ = dragonnet.predict(x_men_test_t_on_device)

    uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
    y_true = y_men_test_t.detach().cpu().numpy().flatten()
    t_true = t_men_test_t.detach().cpu().numpy().flatten()

    # ATE error
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()

    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  Done Seed {SEED}")

# 3. Aggregate final test metrics
df_results = pd.DataFrame(all_runs)

print("\n" + "=" * 85)
print(f"{'CHI TIẾT TỪNG SEED (TEST SET)':^85}")
print("=" * 85)
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format,
    'AUQC': '{:,.4f}'.format,
    'Lift': '{:,.4f}'.format,
    'KRCC': '{:,.4f}'.format,
    'ATE_Err': '{:,.4f}'.format
}))

mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("=" * 85)
print(f"{'KẾT QUẢ TRUNG BÌNH TEST (MEAN ± STD)':^85}")
print("-" * 85)
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")
print("=" * 85)

Đang đánh giá trên test với best config từ validation:
  lr=4.8e-04, weight_decay=1.2e-05, alpha=0.1, beta=0.1
Số seed: 5
Locked random seed: 412312
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/70 | Base Loss: 414.8980 | Tarreg Loss: 20.977810 | Total Loss: 435.8759 | Val Loss: 498.7762 | Raw Qini: 0.6780 | EMA Trend: 0.6780 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/70 | Base Loss: 537.2147 | Tarreg Loss: 27.044498 | Total Loss: 564.2592 | Val Loss: 498.3949 | Raw Qini: 0.6579 | EMA Trend: 0.6750 | (patience: 1/15)
Epoch 3/70 | Base Loss: 287.5820 | Tarreg Loss: 14.456583 | Total Loss: 302.0385 | Val Loss: 497.7483 | Raw Qini: 0.7036 | EMA Trend: 0.6792 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/70 | Base Loss: 261.0580 | Tarreg Loss: 13.230468 | Total Loss: 274.2885 | Val Loss: 496.7348 | Raw Qini: 0.6707 | EMA Trend: 0.6780 | (patience: 1/15)
Epoch 5/70 | Base Loss: 652.1442 | Tarreg Loss: 33.012432 | Total Loss: 685.1567 | Val Loss: 495.9642 | Raw Qini: 0.6362 | EMA Trend: 0.6717 | (patience: 2/15)
Epoch 6/70 | Base Loss: 303.2788 | Tarreg Loss: 15.355283 | Total Loss: 318.6341 | Val Loss: 495.8057 | Raw Qini: 0.6872 | EMA Trend: 0.6740 | ✓ above trend but not peak (patience: 3/15)
Epoch 7/70 | Base Loss: 493.1432 | Tarreg Loss: 24.840006 | Total Loss: 517.9832 | Val Loss: 495.6396 | Raw Qini: 0.7501 | EMA Trend: 0.6854 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/70 | Base Loss: 661.1805 | Tarreg Loss: 33.270504 | Total Loss: 694.4510 | Val Loss: 495.6765 | Raw Qini: 0.7773 | EMA Trend: 0.6992 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/70 | Base Loss: 461.2465 | Tarreg Loss: 23.166601 | Total Loss: 484.4131 | Val Loss: 495.6642 | Raw Qini: 0.7915 | EMA Trend: 0.7131 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/70 | Base Loss: 603.9240 | Tarreg Loss: 30.284702 | Total Loss: 634.2087 | Val Loss: 495.5488 | Raw Qini: 0.8081 | EMA Trend: 0.7273 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/70 | Base Loss: 387.1277 | Tarreg Loss: 19.543570 | Total Loss: 406.6713 | Val Loss: 495.5512 | Raw Qini: 0.8188 | EMA Trend: 0.7410 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/70 | Base Loss: 404.5271 | Tarreg Loss: 20.399466 | Total Loss: 424.9265 | Val Loss: 495.5238 | Raw Qini: 0.8249 | EMA Trend: 0.7536 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/70 | Base Loss: 465.0265 | Tarreg Loss: 23.430618 | Total Loss: 488.4571 | Val Loss: 495.3942 | Raw Qini: 0.8447 | EMA Trend: 0.7673 | ⭐ NEW BEST (peak ≥ trend)
Epoch 14/70 | Base Loss: 711.1624 | Tarreg Loss: 35.752796 | Total Loss: 746.9152 | Val Loss: 495.2380 | Raw Qini: 0.8584 | EMA Trend: 0.7809 | ⭐ NEW BEST (peak ≥ trend)
Epoch 15/70 | Base Loss: 319.7289 | Tarreg Loss: 16.028034 | Total Loss: 335.7570 | Val Loss: 495.1135 | Raw Qini: 0.8625 | EMA Trend: 0.7932 | ⭐ NEW BEST (peak ≥ trend)
Epoch 16/70 | Base Loss: 533.1491 | Tarreg Loss: 26.802534 | Total Loss: 559.9517 | Val Loss: 495.1608 | Raw Qini: 0.8543 | EMA Trend: 0.8024 | ✓ above trend but not peak (patience: 1/15)
Epoch 17/70 | Base Loss: 359.6853 | Tarreg Loss: 18.039616 | Total Loss: 377.7249 | Val Loss: 495.1867 | Raw Qini: 0.8436 | EMA Trend: 0.8085 | ✓ above trend but not peak (patience: 2/15)
Epoch 18/70 | Base Loss: 377.0906 | Tarreg Loss: 18.813940 | Total Loss: 395.9045 | Val Loss: 495.1866 | Raw Qini: 0.8318 | EMA Trend: 0.8120 | ✓ above trend but not peak (patience: 3/15)
Epoch 19/70 | Base Loss: 532.6714 | Tarreg Loss: 26.717182 | Total Loss: 559.3886 | Val Loss: 495.3012 | Raw Qini: 0.7990 | EMA Trend: 0.8101 | (patience: 4/15)
Epoch 20/70 | Base Loss: 243.3941 | Tarreg Loss: 12.349448 | Total Loss: 255.7436 | Val Loss: 495.3105 | Raw Qini: 0.7868 | EMA Trend: 0.8066 | (patience: 5/15)
Epoch 21/70 | Base Loss: 359.4251 | Tarreg Loss: 18.239304 | Total Loss: 377.6644 | Val Loss: 495.1440 | Raw Qini: 0.7908 | EMA Trend: 0.8042 | (patience: 6/15)
Epoch 22/70 | Base Loss: 512.2216 | Tarreg Loss: 25.762232 | Total Loss: 537.9838 | Val Loss: 494.9978 | Raw Qini: 0.7975 | EMA Trend: 0.8032 | (patience: 7/15)
Epoch 23/70 | Base Loss: 346.1581 | Tarreg Loss: 17.490639 | Total Loss: 363.6488 | Val Loss: 494.8413 | Raw Qini: 0.8079 | EMA Trend: 0.8039 | ✓ above trend but not peak (patience: 8/15)
Epoch 24/70 | Base Loss: 459.8865 | Tarreg Loss: 23.396301 | Total Loss: 483.2828 | Val Loss: 494.8034 | Raw Qini: 0.7878 | EMA Trend: 0.8015 | (patience: 9/15)
Epoch 25/70 | Base Loss: 603.5664 | Tarreg Loss: 30.227579 | Total Loss: 633.7940 | Val Loss: 494.8391 | Raw Qini: 0.7625 | EMA Trend: 0.7956 | (patience: 10/15)
Epoch 26/70 | Base Loss: 535.6263 | Tarreg Loss: 26.774885 | Total Loss: 562.4012 | Val Loss: 494.9548 | Raw Qini: 0.7259 | EMA Trend: 0.7852 | (patience: 11/15)
Epoch 27/70 | Base Loss: 630.8489 | Tarreg Loss: 31.820637 | Total Loss: 662.6696 | Val Loss: 495.0117 | Raw Qini: 0.6944 | EMA Trend: 0.7716 | (patience: 12/15)
Epoch 28/70 | Base Loss: 244.7131 | Tarreg Loss: 12.562541 | Total Loss: 257.2757 | Val Loss: 495.0769 | Raw Qini: 0.6932 | EMA Trend: 0.7598 | (patience: 13/15)
Epoch 29/70 | Base Loss: 360.5319 | Tarreg Loss: 18.146231 | Total Loss: 378.6782 | Val Loss: 495.1084 | Raw Qini: 0.6831 | EMA Trend: 0.7483 | (patience: 14/15)
Epoch 30/70 | Base Loss: 477.3633 | Tarreg Loss: 24.232979 | Total Loss: 501.5963 | Val Loss: 495.1606 | Raw Qini: 0.6558 | EMA Trend: 0.7344 | (patience: 15/15)
Epoch 31/70 | Base Loss: 341.0116 | Tarreg Loss: 17.056631 | Total Loss: 358.0682 | Val Loss: 495.1312 | Raw Qini: 0.6653 | EMA Trend: 0.7241 | (patience: 16/15)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 15 epochs

✅ Training completed! Restored model to epoch 15
   Best Raw Qini: 0.8625
   Final EMA Trend: 0.7241
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 412312
Locked random seed: 42
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/70 | Base Loss: 422.8386 | Tarreg Loss: 21.291904 | Total Loss: 444.1305 | Val Loss: 498.3065 | Raw Qini: 0.2591 | EMA Trend: 0.2591 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/70 | Base Loss: 496.7716 | Tarreg Loss: 24.771500 | Total Loss: 521.5432 | Val Loss: 497.9116 | Raw Qini: 0.3715 | EMA Trend: 0.2759 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/70 | Base Loss: 514.5347 | Tarreg Loss: 25.711792 | Total Loss: 540.2465 | Val Loss: 497.2393 | Raw Qini: 0.4134 | EMA Trend: 0.2965 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/70 | Base Loss: 347.2964 | Tarreg Loss: 17.479147 | Total Loss: 364.7755 | Val Loss: 496.3791 | Raw Qini: 0.5878 | EMA Trend: 0.3402 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/70 | Base Loss: 356.5308 | Tarreg Loss: 17.940235 | Total Loss: 374.4711 | Val Loss: 496.0718 | Raw Qini: 0.6831 | EMA Trend: 0.3917 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/70 | Base Loss: 431.4164 | Tarreg Loss: 21.756432 | Total Loss: 453.1729 | Val Loss: 496.0442 | Raw Qini: 0.7344 | EMA Trend: 0.4431 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/70 | Base Loss: 311.4308 | Tarreg Loss: 15.681125 | Total Loss: 327.1119 | Val Loss: 495.6036 | Raw Qini: 0.7723 | EMA Trend: 0.4925 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/70 | Base Loss: 259.0569 | Tarreg Loss: 13.010726 | Total Loss: 272.0677 | Val Loss: 495.5239 | Raw Qini: 0.7898 | EMA Trend: 0.5371 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/70 | Base Loss: 451.7785 | Tarreg Loss: 22.652035 | Total Loss: 474.4306 | Val Loss: 495.5609 | Raw Qini: 0.7983 | EMA Trend: 0.5762 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/70 | Base Loss: 392.2502 | Tarreg Loss: 19.627525 | Total Loss: 411.8777 | Val Loss: 495.5197 | Raw Qini: 0.8109 | EMA Trend: 0.6114 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/70 | Base Loss: 347.4975 | Tarreg Loss: 17.613104 | Total Loss: 365.1106 | Val Loss: 495.3973 | Raw Qini: 0.8123 | EMA Trend: 0.6416 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/70 | Base Loss: 465.6694 | Tarreg Loss: 23.278990 | Total Loss: 488.9484 | Val Loss: 495.2416 | Raw Qini: 0.8242 | EMA Trend: 0.6690 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/70 | Base Loss: 388.5023 | Tarreg Loss: 19.529123 | Total Loss: 408.0314 | Val Loss: 495.0517 | Raw Qini: 0.8345 | EMA Trend: 0.6938 | ⭐ NEW BEST (peak ≥ trend)
Epoch 14/70 | Base Loss: 532.6112 | Tarreg Loss: 26.736557 | Total Loss: 559.3478 | Val Loss: 494.9097 | Raw Qini: 0.8425 | EMA Trend: 0.7161 | ⭐ NEW BEST (peak ≥ trend)
Epoch 15/70 | Base Loss: 595.1260 | Tarreg Loss: 29.671026 | Total Loss: 624.7971 | Val Loss: 494.9166 | Raw Qini: 0.8249 | EMA Trend: 0.7324 | ✓ above trend but not peak (patience: 1/15)
Epoch 16/70 | Base Loss: 562.1064 | Tarreg Loss: 28.150562 | Total Loss: 590.2570 | Val Loss: 494.8615 | Raw Qini: 0.8065 | EMA Trend: 0.7435 | ✓ above trend but not peak (patience: 2/15)
Epoch 17/70 | Base Loss: 479.0200 | Tarreg Loss: 24.032780 | Total Loss: 503.0528 | Val Loss: 494.7770 | Raw Qini: 0.8007 | EMA Trend: 0.7521 | ✓ above trend but not peak (patience: 3/15)
Epoch 18/70 | Base Loss: 444.5599 | Tarreg Loss: 21.897076 | Total Loss: 466.4570 | Val Loss: 494.7823 | Raw Qini: 0.7745 | EMA Trend: 0.7555 | ✓ above trend but not peak (patience: 4/15)
Epoch 19/70 | Base Loss: 613.4404 | Tarreg Loss: 30.806105 | Total Loss: 644.2465 | Val Loss: 494.8977 | Raw Qini: 0.7427 | EMA Trend: 0.7535 | (patience: 5/15)
Epoch 20/70 | Base Loss: 444.7966 | Tarreg Loss: 22.239838 | Total Loss: 467.0365 | Val Loss: 494.9314 | Raw Qini: 0.7251 | EMA Trend: 0.7493 | (patience: 6/15)
Epoch 21/70 | Base Loss: 494.0010 | Tarreg Loss: 24.642668 | Total Loss: 518.6437 | Val Loss: 494.9627 | Raw Qini: 0.6879 | EMA Trend: 0.7401 | (patience: 7/15)
Epoch 22/70 | Base Loss: 543.7361 | Tarreg Loss: 27.214924 | Total Loss: 570.9510 | Val Loss: 494.9363 | Raw Qini: 0.6562 | EMA Trend: 0.7275 | (patience: 8/15)
Epoch 23/70 | Base Loss: 518.4944 | Tarreg Loss: 25.950621 | Total Loss: 544.4451 | Val Loss: 495.0605 | Raw Qini: 0.6167 | EMA Trend: 0.7109 | (patience: 9/15)
Epoch 24/70 | Base Loss: 278.1989 | Tarreg Loss: 14.022458 | Total Loss: 292.2214 | Val Loss: 495.1097 | Raw Qini: 0.6006 | EMA Trend: 0.6943 | (patience: 10/15)
Epoch 25/70 | Base Loss: 404.3556 | Tarreg Loss: 20.228891 | Total Loss: 424.5845 | Val Loss: 495.1428 | Raw Qini: 0.5941 | EMA Trend: 0.6793 | (patience: 11/15)
Epoch 26/70 | Base Loss: 358.3901 | Tarreg Loss: 18.006725 | Total Loss: 376.3968 | Val Loss: 495.1299 | Raw Qini: 0.6280 | EMA Trend: 0.6716 | (patience: 12/15)
Epoch 27/70 | Base Loss: 458.7318 | Tarreg Loss: 23.027624 | Total Loss: 481.7595 | Val Loss: 495.2326 | Raw Qini: 0.5956 | EMA Trend: 0.6602 | (patience: 13/15)
Epoch 28/70 | Base Loss: 366.0892 | Tarreg Loss: 18.378750 | Total Loss: 384.4679 | Val Loss: 495.4005 | Raw Qini: 0.5288 | EMA Trend: 0.6405 | (patience: 14/15)
Epoch 29/70 | Base Loss: 519.3203 | Tarreg Loss: 25.961689 | Total Loss: 545.2819 | Val Loss: 495.5507 | Raw Qini: 0.4997 | EMA Trend: 0.6194 | (patience: 15/15)
Epoch 30/70 | Base Loss: 480.9828 | Tarreg Loss: 24.033541 | Total Loss: 505.0164 | Val Loss: 495.4472 | Raw Qini: 0.5254 | EMA Trend: 0.6053 | (patience: 16/15)
Epoch 31/70 | Base Loss: 536.8286 | Tarreg Loss: 27.012510 | Total Loss: 563.8411 | Val Loss: 495.4536 | Raw Qini: 0.5334 | EMA Trend: 0.5945 | (patience: 17/15)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 15 epochs

✅ Training completed! Restored model to epoch 14
   Best Raw Qini: 0.8425
   Final EMA Trend: 0.5945
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 42
Locked random seed: 1874
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/70 | Base Loss: 421.2921 | Tarreg Loss: 22.291479 | Total Loss: 443.5836 | Val Loss: 498.5189 | Raw Qini: 0.4735 | EMA Trend: 0.4735 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/70 | Base Loss: 456.6181 | Tarreg Loss: 23.936104 | Total Loss: 480.5542 | Val Loss: 498.0499 | Raw Qini: 0.5998 | EMA Trend: 0.4925 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/70 | Base Loss: 562.2100 | Tarreg Loss: 29.185831 | Total Loss: 591.3959 | Val Loss: 497.3817 | Raw Qini: 0.6271 | EMA Trend: 0.5126 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/70 | Base Loss: 597.1566 | Tarreg Loss: 30.644949 | Total Loss: 627.8016 | Val Loss: 496.5551 | Raw Qini: 0.6318 | EMA Trend: 0.5305 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/70 | Base Loss: 403.8498 | Tarreg Loss: 21.152742 | Total Loss: 425.0025 | Val Loss: 496.1939 | Raw Qini: 0.6489 | EMA Trend: 0.5483 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/70 | Base Loss: 520.9796 | Tarreg Loss: 26.897635 | Total Loss: 547.8773 | Val Loss: 496.1886 | Raw Qini: 0.7016 | EMA Trend: 0.5713 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/70 | Base Loss: 425.2818 | Tarreg Loss: 22.013437 | Total Loss: 447.2952 | Val Loss: 495.8091 | Raw Qini: 0.7423 | EMA Trend: 0.5969 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/70 | Base Loss: 522.7874 | Tarreg Loss: 27.023472 | Total Loss: 549.8109 | Val Loss: 495.6371 | Raw Qini: 0.7684 | EMA Trend: 0.6227 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/70 | Base Loss: 311.9413 | Tarreg Loss: 16.541767 | Total Loss: 328.4831 | Val Loss: 495.5092 | Raw Qini: 0.7865 | EMA Trend: 0.6472 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/70 | Base Loss: 376.8907 | Tarreg Loss: 19.539841 | Total Loss: 396.4305 | Val Loss: 495.3831 | Raw Qini: 0.7918 | EMA Trend: 0.6689 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/70 | Base Loss: 697.0964 | Tarreg Loss: 35.545132 | Total Loss: 732.6415 | Val Loss: 495.2914 | Raw Qini: 0.7969 | EMA Trend: 0.6881 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/70 | Base Loss: 555.0524 | Tarreg Loss: 28.518467 | Total Loss: 583.5709 | Val Loss: 495.2352 | Raw Qini: 0.8106 | EMA Trend: 0.7065 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/70 | Base Loss: 565.7313 | Tarreg Loss: 28.860731 | Total Loss: 594.5920 | Val Loss: 495.1883 | Raw Qini: 0.8151 | EMA Trend: 0.7228 | ⭐ NEW BEST (peak ≥ trend)
Epoch 14/70 | Base Loss: 443.2676 | Tarreg Loss: 22.897558 | Total Loss: 466.1652 | Val Loss: 495.1708 | Raw Qini: 0.8186 | EMA Trend: 0.7372 | ⭐ NEW BEST (peak ≥ trend)
Epoch 15/70 | Base Loss: 337.7701 | Tarreg Loss: 17.599741 | Total Loss: 355.3699 | Val Loss: 495.1396 | Raw Qini: 0.8141 | EMA Trend: 0.7487 | ✓ above trend but not peak (patience: 1/15)
Epoch 16/70 | Base Loss: 549.3824 | Tarreg Loss: 28.193909 | Total Loss: 577.5764 | Val Loss: 495.1083 | Raw Qini: 0.8152 | EMA Trend: 0.7587 | ✓ above trend but not peak (patience: 2/15)
Epoch 17/70 | Base Loss: 471.5479 | Tarreg Loss: 24.249479 | Total Loss: 495.7973 | Val Loss: 495.1339 | Raw Qini: 0.7978 | EMA Trend: 0.7645 | ✓ above trend but not peak (patience: 3/15)
Epoch 18/70 | Base Loss: 534.9139 | Tarreg Loss: 27.311111 | Total Loss: 562.2250 | Val Loss: 495.1212 | Raw Qini: 0.7825 | EMA Trend: 0.7672 | ✓ above trend but not peak (patience: 4/15)
Epoch 19/70 | Base Loss: 563.8220 | Tarreg Loss: 29.018560 | Total Loss: 592.8405 | Val Loss: 495.1110 | Raw Qini: 0.7643 | EMA Trend: 0.7668 | (patience: 5/15)
Epoch 20/70 | Base Loss: 499.8907 | Tarreg Loss: 25.553801 | Total Loss: 525.4445 | Val Loss: 495.1153 | Raw Qini: 0.7364 | EMA Trend: 0.7622 | (patience: 6/15)
Epoch 21/70 | Base Loss: 397.7527 | Tarreg Loss: 20.723633 | Total Loss: 418.4764 | Val Loss: 495.1014 | Raw Qini: 0.7326 | EMA Trend: 0.7578 | (patience: 7/15)
Epoch 22/70 | Base Loss: 548.4570 | Tarreg Loss: 27.984823 | Total Loss: 576.4418 | Val Loss: 495.0314 | Raw Qini: 0.7030 | EMA Trend: 0.7496 | (patience: 8/15)
Epoch 23/70 | Base Loss: 315.4580 | Tarreg Loss: 16.336098 | Total Loss: 331.7941 | Val Loss: 495.0417 | Raw Qini: 0.6688 | EMA Trend: 0.7375 | (patience: 9/15)
Epoch 24/70 | Base Loss: 347.6764 | Tarreg Loss: 17.720064 | Total Loss: 365.3965 | Val Loss: 495.0773 | Raw Qini: 0.6616 | EMA Trend: 0.7261 | (patience: 10/15)
Epoch 25/70 | Base Loss: 438.0699 | Tarreg Loss: 22.473850 | Total Loss: 460.5437 | Val Loss: 495.0381 | Raw Qini: 0.6400 | EMA Trend: 0.7132 | (patience: 11/15)
Epoch 26/70 | Base Loss: 331.0490 | Tarreg Loss: 17.179615 | Total Loss: 348.2286 | Val Loss: 495.1066 | Raw Qini: 0.6108 | EMA Trend: 0.6978 | (patience: 12/15)
Epoch 27/70 | Base Loss: 221.1408 | Tarreg Loss: 11.674138 | Total Loss: 232.8149 | Val Loss: 495.1243 | Raw Qini: 0.6068 | EMA Trend: 0.6842 | (patience: 13/15)
Epoch 28/70 | Base Loss: 408.1167 | Tarreg Loss: 20.894650 | Total Loss: 429.0113 | Val Loss: 495.1843 | Raw Qini: 0.5980 | EMA Trend: 0.6712 | (patience: 14/15)
Epoch 29/70 | Base Loss: 412.3007 | Tarreg Loss: 21.247076 | Total Loss: 433.5478 | Val Loss: 495.3109 | Raw Qini: 0.5371 | EMA Trend: 0.6511 | (patience: 15/15)
Epoch 30/70 | Base Loss: 381.0540 | Tarreg Loss: 19.770508 | Total Loss: 400.8245 | Val Loss: 495.3973 | Raw Qini: 0.5021 | EMA Trend: 0.6288 | (patience: 16/15)
Epoch 31/70 | Base Loss: 413.5501 | Tarreg Loss: 22.046295 | Total Loss: 435.5964 | Val Loss: 495.4553 | Raw Qini: 0.5007 | EMA Trend: 0.6096 | (patience: 17/15)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 15 epochs

✅ Training completed! Restored model to epoch 14
   Best Raw Qini: 0.8186
   Final EMA Trend: 0.6096
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 1874
Locked random seed: 902745
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/70 | Base Loss: 408.1194 | Tarreg Loss: 20.867258 | Total Loss: 428.9867 | Val Loss: 498.3340 | Raw Qini: 0.4538 | EMA Trend: 0.4538 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/70 | Base Loss: 352.5766 | Tarreg Loss: 18.202801 | Total Loss: 370.7794 | Val Loss: 497.8989 | Raw Qini: 0.7577 | EMA Trend: 0.4993 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/70 | Base Loss: 371.7027 | Tarreg Loss: 19.143734 | Total Loss: 390.8465 | Val Loss: 497.1783 | Raw Qini: 0.7658 | EMA Trend: 0.5393 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/70 | Base Loss: 439.9175 | Tarreg Loss: 22.337486 | Total Loss: 462.2550 | Val Loss: 496.2093 | Raw Qini: 0.7544 | EMA Trend: 0.5716 | ✓ above trend but not peak (patience: 1/15)
Epoch 5/70 | Base Loss: 480.2464 | Tarreg Loss: 24.468801 | Total Loss: 504.7152 | Val Loss: 495.8036 | Raw Qini: 0.7619 | EMA Trend: 0.6001 | ✓ above trend but not peak (patience: 2/15)
Epoch 6/70 | Base Loss: 549.8821 | Tarreg Loss: 27.656910 | Total Loss: 577.5391 | Val Loss: 495.6525 | Raw Qini: 0.8044 | EMA Trend: 0.6308 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/70 | Base Loss: 535.6178 | Tarreg Loss: 27.193287 | Total Loss: 562.8111 | Val Loss: 495.4418 | Raw Qini: 0.8254 | EMA Trend: 0.6600 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/70 | Base Loss: 413.9772 | Tarreg Loss: 21.233313 | Total Loss: 435.2105 | Val Loss: 495.3556 | Raw Qini: 0.8376 | EMA Trend: 0.6866 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/70 | Base Loss: 610.4960 | Tarreg Loss: 30.560581 | Total Loss: 641.0566 | Val Loss: 495.3585 | Raw Qini: 0.8437 | EMA Trend: 0.7102 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/70 | Base Loss: 457.1575 | Tarreg Loss: 23.303930 | Total Loss: 480.4614 | Val Loss: 495.2043 | Raw Qini: 0.8520 | EMA Trend: 0.7314 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/70 | Base Loss: 549.4917 | Tarreg Loss: 27.686766 | Total Loss: 577.1785 | Val Loss: 495.0607 | Raw Qini: 0.8573 | EMA Trend: 0.7503 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/70 | Base Loss: 491.1136 | Tarreg Loss: 24.852509 | Total Loss: 515.9662 | Val Loss: 494.9801 | Raw Qini: 0.8589 | EMA Trend: 0.7666 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/70 | Base Loss: 404.7805 | Tarreg Loss: 20.500345 | Total Loss: 425.2809 | Val Loss: 494.9909 | Raw Qini: 0.8597 | EMA Trend: 0.7806 | ⭐ NEW BEST (peak ≥ trend)
Epoch 14/70 | Base Loss: 397.3983 | Tarreg Loss: 20.193228 | Total Loss: 417.5916 | Val Loss: 495.0644 | Raw Qini: 0.8510 | EMA Trend: 0.7911 | ✓ above trend but not peak (patience: 1/15)
Epoch 15/70 | Base Loss: 458.4032 | Tarreg Loss: 23.247299 | Total Loss: 481.6505 | Val Loss: 495.0702 | Raw Qini: 0.8469 | EMA Trend: 0.7995 | ✓ above trend but not peak (patience: 2/15)
Epoch 16/70 | Base Loss: 456.3908 | Tarreg Loss: 22.976173 | Total Loss: 479.3670 | Val Loss: 494.9802 | Raw Qini: 0.8546 | EMA Trend: 0.8078 | ✓ above trend but not peak (patience: 3/15)
Epoch 17/70 | Base Loss: 427.9029 | Tarreg Loss: 21.751472 | Total Loss: 449.6543 | Val Loss: 494.8945 | Raw Qini: 0.8596 | EMA Trend: 0.8155 | ✓ above trend but not peak (patience: 4/15)
Epoch 18/70 | Base Loss: 489.5421 | Tarreg Loss: 24.705698 | Total Loss: 514.2478 | Val Loss: 494.7938 | Raw Qini: 0.8634 | EMA Trend: 0.8227 | ⭐ NEW BEST (peak ≥ trend)
Epoch 19/70 | Base Loss: 454.6695 | Tarreg Loss: 22.906004 | Total Loss: 477.5755 | Val Loss: 494.7570 | Raw Qini: 0.8501 | EMA Trend: 0.8268 | ✓ above trend but not peak (patience: 1/15)
Epoch 20/70 | Base Loss: 327.3587 | Tarreg Loss: 16.736954 | Total Loss: 344.0956 | Val Loss: 494.7457 | Raw Qini: 0.8368 | EMA Trend: 0.8283 | ✓ above trend but not peak (patience: 2/15)
Epoch 21/70 | Base Loss: 493.5017 | Tarreg Loss: 25.228041 | Total Loss: 518.7297 | Val Loss: 494.7941 | Raw Qini: 0.8153 | EMA Trend: 0.8264 | (patience: 3/15)
Epoch 22/70 | Base Loss: 495.7177 | Tarreg Loss: 24.949308 | Total Loss: 520.6671 | Val Loss: 494.6743 | Raw Qini: 0.8147 | EMA Trend: 0.8246 | (patience: 4/15)
Epoch 23/70 | Base Loss: 468.7955 | Tarreg Loss: 23.889553 | Total Loss: 492.6851 | Val Loss: 494.5099 | Raw Qini: 0.8292 | EMA Trend: 0.8253 | ✓ above trend but not peak (patience: 5/15)
Epoch 24/70 | Base Loss: 636.8456 | Tarreg Loss: 32.204136 | Total Loss: 669.0497 | Val Loss: 494.4705 | Raw Qini: 0.8218 | EMA Trend: 0.8248 | (patience: 6/15)
Epoch 25/70 | Base Loss: 455.1661 | Tarreg Loss: 23.092937 | Total Loss: 478.2590 | Val Loss: 494.5865 | Raw Qini: 0.7734 | EMA Trend: 0.8171 | (patience: 7/15)
Epoch 26/70 | Base Loss: 325.8528 | Tarreg Loss: 16.700666 | Total Loss: 342.5535 | Val Loss: 494.7791 | Raw Qini: 0.7032 | EMA Trend: 0.8000 | (patience: 8/15)
Epoch 27/70 | Base Loss: 564.0822 | Tarreg Loss: 28.292547 | Total Loss: 592.3748 | Val Loss: 494.7398 | Raw Qini: 0.6992 | EMA Trend: 0.7849 | (patience: 9/15)
Epoch 28/70 | Base Loss: 479.1421 | Tarreg Loss: 24.282087 | Total Loss: 503.4241 | Val Loss: 494.8091 | Raw Qini: 0.6800 | EMA Trend: 0.7691 | (patience: 10/15)
Epoch 29/70 | Base Loss: 512.3870 | Tarreg Loss: 25.869303 | Total Loss: 538.2563 | Val Loss: 494.8283 | Raw Qini: 0.6846 | EMA Trend: 0.7565 | (patience: 11/15)
Epoch 30/70 | Base Loss: 439.8430 | Tarreg Loss: 22.089748 | Total Loss: 461.9327 | Val Loss: 494.8722 | Raw Qini: 0.6832 | EMA Trend: 0.7455 | (patience: 12/15)
Epoch 31/70 | Base Loss: 204.6692 | Tarreg Loss: 10.377000 | Total Loss: 215.0462 | Val Loss: 494.9854 | Raw Qini: 0.6337 | EMA Trend: 0.7287 | (patience: 13/15)
Epoch 32/70 | Base Loss: 518.9343 | Tarreg Loss: 26.060266 | Total Loss: 544.9945 | Val Loss: 494.9843 | Raw Qini: 0.6129 | EMA Trend: 0.7113 | (patience: 14/15)
Epoch 33/70 | Base Loss: 313.1467 | Tarreg Loss: 15.784446 | Total Loss: 328.9311 | Val Loss: 494.9727 | Raw Qini: 0.5979 | EMA Trend: 0.6943 | (patience: 15/15)

🛑 Early stopping triggered at epoch 33!
   No valid peak (raw ≥ trend) found in last 15 epochs

✅ Training completed! Restored model to epoch 18
   Best Raw Qini: 0.8634
   Final EMA Trend: 0.6943
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 902745
Locked random seed: 1
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/70 | Base Loss: 439.6072 | Tarreg Loss: 22.189453 | Total Loss: 461.7967 | Val Loss: 498.8931 | Raw Qini: 0.6979 | EMA Trend: 0.6979 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/70 | Base Loss: 335.6311 | Tarreg Loss: 17.067280 | Total Loss: 352.6984 | Val Loss: 498.4789 | Raw Qini: 0.7098 | EMA Trend: 0.6997 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/70 | Base Loss: 711.8398 | Tarreg Loss: 35.565674 | Total Loss: 747.4055 | Val Loss: 497.7816 | Raw Qini: 0.6786 | EMA Trend: 0.6965 | (patience: 1/15)
Epoch 4/70 | Base Loss: 550.8727 | Tarreg Loss: 27.771772 | Total Loss: 578.6445 | Val Loss: 496.7126 | Raw Qini: 0.7428 | EMA Trend: 0.7034 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/70 | Base Loss: 434.2457 | Tarreg Loss: 21.821753 | Total Loss: 456.0674 | Val Loss: 495.8173 | Raw Qini: 0.7914 | EMA Trend: 0.7166 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/70 | Base Loss: 372.3931 | Tarreg Loss: 18.885933 | Total Loss: 391.2790 | Val Loss: 495.6157 | Raw Qini: 0.8428 | EMA Trend: 0.7356 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/70 | Base Loss: 436.1389 | Tarreg Loss: 21.800993 | Total Loss: 457.9399 | Val Loss: 495.3367 | Raw Qini: 0.8558 | EMA Trend: 0.7536 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/70 | Base Loss: 399.6868 | Tarreg Loss: 19.958378 | Total Loss: 419.6452 | Val Loss: 495.1558 | Raw Qini: 0.8603 | EMA Trend: 0.7696 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/70 | Base Loss: 433.8552 | Tarreg Loss: 21.814253 | Total Loss: 455.6695 | Val Loss: 495.2171 | Raw Qini: 0.8543 | EMA Trend: 0.7823 | ✓ above trend but not peak (patience: 1/15)
Epoch 10/70 | Base Loss: 587.3905 | Tarreg Loss: 29.405775 | Total Loss: 616.7963 | Val Loss: 495.2384 | Raw Qini: 0.8618 | EMA Trend: 0.7942 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/70 | Base Loss: 362.9359 | Tarreg Loss: 18.235769 | Total Loss: 381.1717 | Val Loss: 495.1688 | Raw Qini: 0.8560 | EMA Trend: 0.8035 | ✓ above trend but not peak (patience: 1/15)
Epoch 12/70 | Base Loss: 450.8557 | Tarreg Loss: 22.502058 | Total Loss: 473.3577 | Val Loss: 495.1133 | Raw Qini: 0.8491 | EMA Trend: 0.8103 | ✓ above trend but not peak (patience: 2/15)
Epoch 13/70 | Base Loss: 513.6109 | Tarreg Loss: 25.668539 | Total Loss: 539.2794 | Val Loss: 495.0399 | Raw Qini: 0.8506 | EMA Trend: 0.8164 | ✓ above trend but not peak (patience: 3/15)
Epoch 14/70 | Base Loss: 480.6682 | Tarreg Loss: 24.023691 | Total Loss: 504.6918 | Val Loss: 494.9557 | Raw Qini: 0.8502 | EMA Trend: 0.8214 | ✓ above trend but not peak (patience: 4/15)
Epoch 15/70 | Base Loss: 475.0429 | Tarreg Loss: 23.877880 | Total Loss: 498.9208 | Val Loss: 494.8931 | Raw Qini: 0.8465 | EMA Trend: 0.8252 | ✓ above trend but not peak (patience: 5/15)
Epoch 16/70 | Base Loss: 594.2012 | Tarreg Loss: 30.023396 | Total Loss: 624.2246 | Val Loss: 494.8221 | Raw Qini: 0.8398 | EMA Trend: 0.8274 | ✓ above trend but not peak (patience: 6/15)
Epoch 17/70 | Base Loss: 535.4151 | Tarreg Loss: 26.679600 | Total Loss: 562.0947 | Val Loss: 494.7614 | Raw Qini: 0.8457 | EMA Trend: 0.8301 | ✓ above trend but not peak (patience: 7/15)
Epoch 18/70 | Base Loss: 471.6103 | Tarreg Loss: 23.692690 | Total Loss: 495.3029 | Val Loss: 494.8382 | Raw Qini: 0.8201 | EMA Trend: 0.8286 | (patience: 8/15)
Epoch 19/70 | Base Loss: 411.2765 | Tarreg Loss: 20.652866 | Total Loss: 431.9294 | Val Loss: 494.9847 | Raw Qini: 0.7717 | EMA Trend: 0.8201 | (patience: 9/15)
Epoch 20/70 | Base Loss: 674.6861 | Tarreg Loss: 33.709770 | Total Loss: 708.3959 | Val Loss: 495.0323 | Raw Qini: 0.7398 | EMA Trend: 0.8080 | (patience: 10/15)
Epoch 21/70 | Base Loss: 478.2548 | Tarreg Loss: 23.820402 | Total Loss: 502.0752 | Val Loss: 495.0898 | Raw Qini: 0.6921 | EMA Trend: 0.7907 | (patience: 11/15)
Epoch 22/70 | Base Loss: 416.0912 | Tarreg Loss: 20.675413 | Total Loss: 436.7666 | Val Loss: 494.9576 | Raw Qini: 0.6950 | EMA Trend: 0.7763 | (patience: 12/15)
Epoch 23/70 | Base Loss: 573.9310 | Tarreg Loss: 28.633467 | Total Loss: 602.5645 | Val Loss: 494.9084 | Raw Qini: 0.6864 | EMA Trend: 0.7628 | (patience: 13/15)
Epoch 24/70 | Base Loss: 548.8486 | Tarreg Loss: 27.394291 | Total Loss: 576.2429 | Val Loss: 495.0233 | Raw Qini: 0.6481 | EMA Trend: 0.7456 | (patience: 14/15)
Epoch 25/70 | Base Loss: 333.3423 | Tarreg Loss: 16.690559 | Total Loss: 350.0328 | Val Loss: 495.1951 | Raw Qini: 0.6118 | EMA Trend: 0.7255 | (patience: 15/15)
Epoch 26/70 | Base Loss: 641.1286 | Tarreg Loss: 32.230572 | Total Loss: 673.3592 | Val Loss: 495.4149 | Raw Qini: 0.5425 | EMA Trend: 0.6981 | (patience: 16/15)
Epoch 27/70 | Base Loss: 699.7760 | Tarreg Loss: 35.113152 | Total Loss: 734.8892 | Val Loss: 495.6600 | Raw Qini: 0.5004 | EMA Trend: 0.6684 | (patience: 17/15)
Epoch 28/70 | Base Loss: 250.2271 | Tarreg Loss: 12.505567 | Total Loss: 262.7326 | Val Loss: 495.7377 | Raw Qini: 0.5011 | EMA Trend: 0.6433 | (patience: 18/15)
Epoch 29/70 | Base Loss: 391.0404 | Tarreg Loss: 19.517263 | Total Loss: 410.5577 | Val Loss: 495.7239 | Raw Qini: 0.5226 | EMA Trend: 0.6252 | (patience: 19/15)
Epoch 30/70 | Base Loss: 437.8906 | Tarreg Loss: 21.996857 | Total Loss: 459.8875 | Val Loss: 495.6544 | Raw Qini: 0.5456 | EMA Trend: 0.6133 | (patience: 20/15)
Epoch 31/70 | Base Loss: 382.4886 | Tarreg Loss: 19.039000 | Total Loss: 401.5276 | Val Loss: 495.6447 | Raw Qini: 0.5465 | EMA Trend: 0.6033 | (patience: 21/15)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 15 epochs

✅ Training completed! Restored model to epoch 10
   Best Raw Qini: 0.8618
   Final EMA Trend: 0.6033
   Strategy: Selected highest peak that stayed above EMA trend
  Done Seed 1

=====================================================================================
                            CHI TIẾT TỪNG SEED (TEST SET)
=====================================================================================
  Seed   AUUC   AUQC   Lift   KRCC ATE_Err
412312 0.5484 0.5467 0.9494 0.0669  0.5156
    42 0.5051 0.5023 0.6266 0.0093  0.2694
  1874 0.5105 0.5068 0.9663 0.0418  0.4181
902745 0.5245 0.5220 0.8282 0.0185  0.4541
     1 0.5649 0.5615 0.8112 0.0601  0.2460
=====================================================================================
                        KẾT QUẢ TRUNG BÌNH TEST (MEAN ± STD)
-------------------------------------------------------------------------------------
AUUC      : 0.5307 ± 0.0254
AUQC      : 0.5279 ± 0.0256
Lift      : 0.8364 ± 0.1364
KRCC      : 0.0393 ± 0.0252
ATE_Err   : 0.3806 ± 0.1178
=====================================================================================

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/Dragonnet/dragonnet.py:328: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)