Import libraries

In [1]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from cfrnet import CFRnet
import sys
from pathlib import Path
project_root = Path("/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [2]:
%time train_df = pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Men/train_men.csv")
%time test_df =  pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Women/test_women.csv")
%time val_df = pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Women/val_women.csv")

CPU times: user 25.8 ms, sys: 6.95 ms, total: 32.7 ms
Wall time: 32.1 ms
CPU times: user 12.3 ms, sys: 4.02 ms, total: 16.3 ms
Wall time: 16.3 ms
CPU times: user 4.38 ms, sys: 2.95 ms, total: 7.32 ms
Wall time: 7.33 ms

In [3]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['conversion']
treatment_feature = ['treatment']

In [4]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [5]:
print('X_train[:10]', X_train[:1].astype(float))

X_train[:10] [[-0.21435131  1.6331766   1.0667411   0.90252386 -1.1010233   1.07039981
   1.00043033  2.70003843 -0.88552759 -0.88616046]]

In [6]:
print('y_train[:10]', y_train[:1].astype(float))

y_train[:10] [[0.]]

In [7]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25567, 10]); y=torch.Size([25567, 1]); t=torch.Size([25567, 1])
Shape of val: x=torch.Size([4270, 10]); y=torch.Size([4270, 1]); t=torch.Size([4270, 1])
Shape of test: x=torch.Size([12808, 10]); y=torch.Size([12808, 1]); t=torch.Size([12808, 1])

In [8]:
epochs = 150
alpha = 1
lr = 1e-3
wd = 1e-5
method = "mmd_rbf"
early_stop_metric = "qini"
ema = True
ema_alpha = 0.15
patience = 20
early_stop_start = 0
shared_hidden = 200
outcome_hidden = 100
outcome_dropout = 0.0
shared_dropout = 0.0 
activation = torch.nn.ReLU

print (f" epochs = {epochs}")
print (f" method = {method}")
print (f" alpha = {alpha}")
print (f" learning rate = {lr}")
print (f" weight decay = {wd}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" shared hidden = {shared_hidden}")
print (f" outcome hidden = {outcome_hidden}")
print (f"activation = {activation}")

 epochs = 150
 method = mmd_rbf
 alpha = 1
 learning rate = 0.001
 weight decay = 1e-05
 early stop = qini
 use ema = True
 ema alpha = 0.15
 patience = 20
 shared hidden = 200
 outcome hidden = 100
activation = <class 'torch.nn.modules.activation.ReLU'>

In [9]:
import pandas as pd
import numpy as np
import torch
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 5e-5, 5e-4, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-4, log=True)
    grid_alpha = trial.suggest_categorical("alpha", [0.1, 0.5, 1.0])
    grid_method = trial.suggest_categorical("method", ["mmd_rbf", "mmd_linear"])
    val_scores = []
    for SEED in seeds:
        seed_everything(SEED)

        cfr = CFRnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            alpha=grid_alpha,
            method=grid_method,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=shared_hidden,
            outcome_hidden=outcome_hidden,
            outcome_dropout=outcome_dropout,
            shared_dropout=shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
            activation=activation
        )

        # Silence CFRNet epoch logs
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            cfr.fit(train_loader, val_loader)

        x_val_device = x_men_val_t.to(device)
        y0_val_p, y1_val_p= cfr.predict(x_val_device)
        uplift_val = (y1_val_p - y0_val_p).detach().cpu().numpy().flatten()
        y_val_true_np = y_men_val_t.detach().cpu().numpy().flatten()
        t_val_true_np = t_men_val_t.detach().cpu().numpy().flatten()

        current_val_auqc = auqc(y_val_true_np, t_val_true_np, uplift_val, bins=100, plot=False)
        val_scores.append(current_val_auqc)

    mean_val_auqc = float(np.mean(val_scores))
    std_val_auqc = float(np.std(val_scores, ddof=1)) if len(val_scores) > 1 else 0.0
    trial.set_user_attr("std_Val_AUQC", std_val_auqc)
    return mean_val_auqc

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

# 2. Persist search results in notebook variables
trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": t.params["lr"],
        "weight_decay": t.params["weight_decay"],
        "alpha": t.params["alpha"],
        "method": t.params["method"],
        "mean_Val_AUQC": float(t.value),
        "std_Val_AUQC": float(t.user_attrs.get("std_Val_AUQC", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_Val_AUQC", ascending=False).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "alpha": float(best_params["alpha"]),
    "method": t.params["method"],
    "mean_Val_AUQC": float(study.best_value),
    "std_Val_AUQC": float(study.best_trial.user_attrs.get("std_Val_AUQC", np.nan))
})

/home/ducvu0904/miniconda3/envs/ai/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
  0%|          | 0/50 [00:00<?, ?it/s]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 0. Best value: 0.840854:   2%|▏         | 1/50 [00:52<42:48, 52.42s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 0. Best value: 0.840854:   4%|▍         | 2/50 [01:37<38:33, 48.19s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 0.843471:   6%|▌         | 3/50 [02:28<38:51, 49.61s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 3. Best value: 0.844729:   8%|▊         | 4/50 [03:16<37:23, 48.77s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 3. Best value: 0.844729:  10%|█         | 5/50 [03:58<34:49, 46.43s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 3. Best value: 0.844729:  12%|█▏        | 6/50 [04:46<34:25, 46.95s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 6. Best value: 0.8492:  14%|█▍        | 7/50 [05:32<33:24, 46.61s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 7. Best value: 0.849207:  16%|█▌        | 8/50 [06:27<34:29, 49.27s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 7. Best value: 0.849207:  18%|█▊        | 9/50 [07:09<32:02, 46.90s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 7. Best value: 0.849207:  20%|██        | 10/50 [07:50<30:00, 45.02s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 7. Best value: 0.849207:  22%|██▏       | 11/50 [08:59<34:09, 52.54s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 7. Best value: 0.849207:  24%|██▍       | 12/50 [09:54<33:48, 53.38s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 7. Best value: 0.849207:  26%|██▌       | 13/50 [10:53<33:57, 55.07s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 7. Best value: 0.849207:  28%|██▊       | 14/50 [11:46<32:33, 54.26s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 7. Best value: 0.849207:  30%|███       | 15/50 [12:37<31:06, 53.34s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 7. Best value: 0.849207:  32%|███▏      | 16/50 [13:28<29:46, 52.53s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 16. Best value: 0.851364:  34%|███▍      | 17/50 [14:15<28:05, 51.09s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 16. Best value: 0.851364:  36%|███▌      | 18/50 [15:22<29:46, 55.83s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 16. Best value: 0.851364:  38%|███▊      | 19/50 [16:20<29:10, 56.45s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 19. Best value: 0.852278:  40%|████      | 20/50 [17:19<28:34, 57.16s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 19. Best value: 0.852278:  42%|████▏     | 21/50 [18:19<28:06, 58.17s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  44%|████▍     | 22/50 [19:20<27:27, 58.85s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  46%|████▌     | 23/50 [20:13<25:44, 57.22s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  48%|████▊     | 24/50 [21:10<24:46, 57.19s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  50%|█████     | 25/50 [22:07<23:46, 57.05s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  52%|█████▏    | 26/50 [22:57<21:58, 54.93s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  54%|█████▍    | 27/50 [23:50<20:51, 54.43s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  56%|█████▌    | 28/50 [24:38<19:10, 52.29s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  58%|█████▊    | 29/50 [25:24<17:37, 50.38s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  60%|██████    | 30/50 [26:10<16:20, 49.02s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  62%|██████▏   | 31/50 [26:59<15:33, 49.15s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  64%|██████▍   | 32/50 [27:48<14:41, 48.99s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  66%|██████▌   | 33/50 [28:45<14:35, 51.52s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  68%|██████▊   | 34/50 [29:36<13:43, 51.49s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  70%|███████   | 35/50 [30:37<13:32, 54.15s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  72%|███████▏  | 36/50 [31:28<12:26, 53.30s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  74%|███████▍  | 37/50 [32:22<11:35, 53.52s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  76%|███████▌  | 38/50 [33:19<10:55, 54.59s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  78%|███████▊  | 39/50 [34:14<10:00, 54.58s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  80%|████████  | 40/50 [35:06<08:59, 53.90s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  82%|████████▏ | 41/50 [35:58<08:00, 53.36s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  84%|████████▍ | 42/50 [36:56<07:17, 54.63s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  86%|████████▌ | 43/50 [37:53<06:28, 55.51s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  88%|████████▊ | 44/50 [38:52<05:38, 56.38s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  90%|█████████ | 45/50 [39:54<04:49, 57.99s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  92%|█████████▏| 46/50 [40:54<03:54, 58.66s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  94%|█████████▍| 47/50 [41:50<02:53, 57.85s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  96%|█████████▌| 48/50 [42:36<01:48, 54.43s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856:  98%|█████████▊| 49/50 [43:38<00:56, 56.80s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 0.852856: 100%|██████████| 50/50 [44:36<00:00, 53.53s/it]

In [10]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_AUQC: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 21
Best mean_Val_AUQC: 0.852856
Best params: {'lr': 0.00011327625005423851, 'weight_decay': 2.1878042054849755e-05, 'alpha': 0.5, 'method': 'mmd_linear'}

Best config table:

         lr weight_decay alpha      method mean_Val_AUQC std_Val_AUQC
0  0.000113     0.000022   0.5  mmd_linear      0.852856     0.076983

Top 10 trials:

,trial,lr,weight_decay,alpha,method,mean_Val_AUQC,std_Val_AUQC
0,21,0.000113,0.000022,0.5,mmd_linear,0.852856,0.076983
1,19,0.000112,0.000033,0.5,mmd_linear,0.852278,0.076960
2,16,0.000121,0.000031,0.1,mmd_linear,0.851364,0.067761
3,18,0.000120,0.000020,0.5,mmd_rbf,0.850125,0.065760
4,37,0.000112,0.000025,0.5,mmd_rbf,0.850004,0.065797
5,7,0.000160,0.000017,0.1,mmd_rbf,0.849207,0.062809
6,6,0.000146,0.000090,0.1,mmd_linear,0.849200,0.071993
7,12,0.000107,0.000096,0.1,mmd_rbf,0.849023,0.057570
8,40,0.000162,0.000018,0.5,mmd_rbf,0.848998,0.065112
9,35,0.000179,0.000036,0.5,mmd_linear,0.848672,0.068580

In [13]:
import pandas as pd
import numpy as np
import torch

# 1. Cấu hình
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

print(f"🔄 Đang huấn luyện TARNet trên {len(seeds)} seeds khác nhau... Vui lòng đợi.")

# 2. Vòng lặp chạy (Chỉ xử lý, không in kết quả lẻ)
for SEED in seeds:
    seed_everything(SEED)
    
    # Khởi tạo lại mô hình
    cfrnet = CFRnet(
        input_dim=x_men_train_t.shape[1], epochs=epochs, learning_rate=1.13E-04, 
        alpha=0.5, method="mmd_linear",
        weight_decay=2.20E-05, use_ema=ema, ema_alpha=ema_alpha, patience=patience,
        shared_hidden=shared_hidden, outcome_hidden=outcome_hidden,
        early_stop_metric=early_stop_metric, early_stop_start_epoch=early_stop_start,
        activation=activation
    )
    
    cfrnet.fit(train_loader, val_loader)
    
    # Predict
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = cfrnet.predict(x_men_test_t_on_device)
    
    uplift_pred = (y1_pred - y0_pred).cpu().numpy().flatten()
    y_true = y_men_test_t.cpu().numpy().flatten()
    t_true = t_men_test_t.cpu().numpy().flatten()
    
    # Tính toán
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()
    
    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  ✔️ Đã xong Seed {SEED}")

# 3. HIỂN THỊ KẾT QUẢ TỔNG HỢP (Print 1 lúc)
df_results = pd.DataFrame(all_runs)

print("\n" + "="*85)
print(f"{'CHI TIẾT TỪNG SEED':^85}")
print("="*85)
# Sử dụng to_string để in bảng đẹp mắt
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format, 'AUQC': '{:,.4f}'.format, 
    'Lift': '{:,.4f}'.format, 'KRCC': '{:,.4f}'.format, 'ATE_Err': '{:,.4f}'.format
}))

# 4. Tính toán Mean và Std
mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("="*85)
print(f"{'KẾT QUẢ TRUNG BÌNH (MEAN ± STD)':^85}")
print("-" * 85)
summary_data = []
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")

print("="*85)

🔄 Đang huấn luyện TARNet trên 5 seeds khác nhau... Vui lòng đợi.
Locked random seed: 412312
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 1
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/150 | Loss: 0.5045 | Val Loss: 0.5028 | Val Qini: 0.7268 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7268 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.4972 | Val Loss: 0.4955 | Val Qini: 0.7408 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7289 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Loss: 0.4904 | Val Loss: 0.4889 | Val Qini: 0.8022 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7399 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Loss: 0.4840 | Val Loss: 0.4825 | Val Qini: 0.6705 (patience: 1/20)EMA Trend: 0.7295 | (patience: 1/20)
Epoch 5/150 | Loss: 0.4776 | Val Loss: 0.4758 | Val Qini: 0.6198 (patience: 2/20)EMA Trend: 0.7130 | (patience: 2/20)
Epoch 6/150 | Loss: 0.4704 | Val Loss: 0.4682 | Val Qini: 0.5649 (patience: 3/20)EMA Trend: 0.6908 | (patience: 3/20)
Epoch 7/150 | Loss: 0.4619 | Val Loss: 0.4592 | Val Qini: 0.4771 (patience: 4/20)EMA Trend: 0.6588 | (patience: 4/20)
Epoch 8/150 | Loss: 0.4517 | Val Loss: 0.4488 | Val Qini: 0.5379 (patience: 5/20)EMA Trend: 0.6406 | (patience: 5/20)
Epoch 9/150 | Loss: 0.4399 | Val Loss: 0.4363 | Val Qini: 0.5861 (patience: 6/20)EMA Trend: 0.6325 | (patience: 6/20)
Epoch 10/150 | Loss: 0.4250 | Val Loss: 0.4204 | Val Qini: 0.4948 (patience: 7/20)EMA Trend: 0.6118 | (patience: 7/20)
Epoch 11/150 | Loss: 0.4067 | Val Loss: 0.3997 | Val Qini: 0.5699 (patience: 8/20)EMA Trend: 0.6055 | (patience: 8/20)
Epoch 12/150 | Loss: 0.3812 | Val Loss: 0.3726 | Val Qini: 0.6093 ✓ above trend but not peak (patience: 9/20)EMA Trend: 0.6061 | ✓ above trend but not peak (patience: 9/20)
Epoch 13/150 | Loss: 0.3488 | Val Loss: 0.3380 | Val Qini: 0.6004 (patience: 10/20)EMA Trend: 0.6052 | (patience: 10/20)
Epoch 14/150 | Loss: 0.3078 | Val Loss: 0.2956 | Val Qini: 0.6307 ✓ above trend but not peak (patience: 11/20)EMA Trend: 0.6091 | ✓ above trend but not peak (patience: 11/20)
Epoch 15/150 | Loss: 0.2627 | Val Loss: 0.2457 | Val Qini: 0.6084 (patience: 12/20)EMA Trend: 0.6090 | (patience: 12/20)
Epoch 16/150 | Loss: 0.2104 | Val Loss: 0.1915 | Val Qini: 0.4754 (patience: 13/20)EMA Trend: 0.5889 | (patience: 13/20)
Epoch 17/150 | Loss: 0.1600 | Val Loss: 0.1383 | Val Qini: 0.3096 (patience: 14/20)EMA Trend: 0.5470 | (patience: 14/20)
Epoch 18/150 | Loss: 0.1061 | Val Loss: 0.0929 | Val Qini: 0.3068 (patience: 15/20)EMA Trend: 0.5110 | (patience: 15/20)
Epoch 19/150 | Loss: 0.0692 | Val Loss: 0.0599 | Val Qini: 0.3274 (patience: 16/20)EMA Trend: 0.4834 | (patience: 16/20)
Epoch 20/150 | Loss: 0.0496 | Val Loss: 0.0396 | Val Qini: 0.3327 (patience: 17/20)EMA Trend: 0.4608 | (patience: 17/20)
Epoch 21/150 | Loss: 0.0348 | Val Loss: 0.0288 | Val Qini: 0.3307 (patience: 18/20)EMA Trend: 0.4413 | (patience: 18/20)
Epoch 22/150 | Loss: 0.0276 | Val Loss: 0.0234 | Val Qini: 0.3315 (patience: 19/20)EMA Trend: 0.4248 | (patience: 19/20)
Epoch 23/150 | Loss: 0.0210 | Val Loss: 0.0208 | Val Qini: 0.3275 (patience: 20/20)EMA Trend: 0.4102 | (patience: 20/20)

🛑 Early stopping triggered at epoch 23!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 3
   Best Raw Qini: 0.8022
   Final EMA Trend: 0.4102
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 412312
Locked random seed: 42
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 1
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Loss: 0.5182 | Val Loss: 0.5165 | Val Qini: 0.1239 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1239 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.5110 | Val Loss: 0.5092 | Val Qini: -0.0727 (patience: 1/20)EMA Trend: 0.0944 | (patience: 1/20)
Epoch 3/150 | Loss: 0.5037 | Val Loss: 0.5016 | Val Qini: -0.1411 (patience: 2/20)EMA Trend: 0.0591 | (patience: 2/20)
Epoch 4/150 | Loss: 0.4955 | Val Loss: 0.4931 | Val Qini: -0.1737 (patience: 3/20)EMA Trend: 0.0242 | (patience: 3/20)
Epoch 5/150 | Loss: 0.4858 | Val Loss: 0.4829 | Val Qini: -0.1029 (patience: 4/20)EMA Trend: 0.0051 | (patience: 4/20)
Epoch 6/150 | Loss: 0.4737 | Val Loss: 0.4704 | Val Qini: -0.0736 (patience: 5/20)EMA Trend: -0.0067 | (patience: 5/20)
Epoch 7/150 | Loss: 0.4592 | Val Loss: 0.4550 | Val Qini: -0.0393 (patience: 6/20)EMA Trend: -0.0116 | (patience: 6/20)
Epoch 8/150 | Loss: 0.4410 | Val Loss: 0.4355 | Val Qini: 0.0662 ✓ above trend but not peak (patience: 7/20)EMA Trend: 0.0001 | ✓ above trend but not peak (patience: 7/20)
Epoch 9/150 | Loss: 0.4176 | Val Loss: 0.4102 | Val Qini: 0.1740 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.0262 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/150 | Loss: 0.3872 | Val Loss: 0.3778 | Val Qini: 0.2239 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.0558 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/150 | Loss: 0.3497 | Val Loss: 0.3374 | Val Qini: 0.2118 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.0792 | ✓ above trend but not peak (patience: 1/20)
Epoch 12/150 | Loss: 0.3046 | Val Loss: 0.2891 | Val Qini: 0.2181 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.1001 | ✓ above trend but not peak (patience: 2/20)
Epoch 13/150 | Loss: 0.2509 | Val Loss: 0.2343 | Val Qini: 0.2192 ✓ above trend but not peak (patience: 3/20)EMA Trend: 0.1179 | ✓ above trend but not peak (patience: 3/20)
Epoch 14/150 | Loss: 0.1922 | Val Loss: 0.1777 | Val Qini: 0.2265 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1342 | ⭐ NEW BEST (peak ≥ trend)
Epoch 15/150 | Loss: 0.1429 | Val Loss: 0.1256 | Val Qini: 0.2902 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1576 | ⭐ NEW BEST (peak ≥ trend)
Epoch 16/150 | Loss: 0.1005 | Val Loss: 0.0837 | Val Qini: 0.5550 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.2172 | ⭐ NEW BEST (peak ≥ trend)
Epoch 17/150 | Loss: 0.0686 | Val Loss: 0.0545 | Val Qini: 0.8643 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.3143 | ⭐ NEW BEST (peak ≥ trend)
Epoch 18/150 | Loss: 0.0466 | Val Loss: 0.0366 | Val Qini: 0.8358 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.3925 | ✓ above trend but not peak (patience: 1/20)
Epoch 19/150 | Loss: 0.0350 | Val Loss: 0.0266 | Val Qini: 0.8258 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.4575 | ✓ above trend but not peak (patience: 2/20)
Epoch 20/150 | Loss: 0.0275 | Val Loss: 0.0214 | Val Qini: 0.8187 ✓ above trend but not peak (patience: 3/20)EMA Trend: 0.5117 | ✓ above trend but not peak (patience: 3/20)
Epoch 21/150 | Loss: 0.0292 | Val Loss: 0.0187 | Val Qini: 0.8121 ✓ above trend but not peak (patience: 4/20)EMA Trend: 0.5568 | ✓ above trend but not peak (patience: 4/20)
Epoch 22/150 | Loss: 0.0213 | Val Loss: 0.0172 | Val Qini: 0.7923 ✓ above trend but not peak (patience: 5/20)EMA Trend: 0.5921 | ✓ above trend but not peak (patience: 5/20)
Epoch 23/150 | Loss: 0.0190 | Val Loss: 0.0165 | Val Qini: 0.7850 ✓ above trend but not peak (patience: 6/20)EMA Trend: 0.6210 | ✓ above trend but not peak (patience: 6/20)
Epoch 24/150 | Loss: 0.0275 | Val Loss: 0.0161 | Val Qini: 0.7749 ✓ above trend but not peak (patience: 7/20)EMA Trend: 0.6441 | ✓ above trend but not peak (patience: 7/20)
Epoch 25/150 | Loss: 0.0174 | Val Loss: 0.0158 | Val Qini: 0.7628 ✓ above trend but not peak (patience: 8/20)EMA Trend: 0.6619 | ✓ above trend but not peak (patience: 8/20)
Epoch 26/150 | Loss: 0.0212 | Val Loss: 0.0156 | Val Qini: 0.7555 ✓ above trend but not peak (patience: 9/20)EMA Trend: 0.6759 | ✓ above trend but not peak (patience: 9/20)
Epoch 27/150 | Loss: 0.0189 | Val Loss: 0.0155 | Val Qini: 0.7416 ✓ above trend but not peak (patience: 10/20)EMA Trend: 0.6858 | ✓ above trend but not peak (patience: 10/20)
Epoch 28/150 | Loss: 0.0207 | Val Loss: 0.0154 | Val Qini: 0.7326 ✓ above trend but not peak (patience: 11/20)EMA Trend: 0.6928 | ✓ above trend but not peak (patience: 11/20)
Epoch 29/150 | Loss: 0.0252 | Val Loss: 0.0153 | Val Qini: 0.7283 ✓ above trend but not peak (patience: 12/20)EMA Trend: 0.6981 | ✓ above trend but not peak (patience: 12/20)
Epoch 30/150 | Loss: 0.0210 | Val Loss: 0.0153 | Val Qini: 0.7075 ✓ above trend but not peak (patience: 13/20)EMA Trend: 0.6995 | ✓ above trend but not peak (patience: 13/20)
Epoch 31/150 | Loss: 0.0227 | Val Loss: 0.0152 | Val Qini: 0.6972 (patience: 14/20)EMA Trend: 0.6992 | (patience: 14/20)
Epoch 32/150 | Loss: 0.0150 | Val Loss: 0.0152 | Val Qini: 0.6829 (patience: 15/20)EMA Trend: 0.6968 | (patience: 15/20)
Epoch 33/150 | Loss: 0.0175 | Val Loss: 0.0152 | Val Qini: 0.6619 (patience: 16/20)EMA Trend: 0.6915 | (patience: 16/20)
Epoch 34/150 | Loss: 0.0179 | Val Loss: 0.0152 | Val Qini: 0.6579 (patience: 17/20)EMA Trend: 0.6865 | (patience: 17/20)
Epoch 35/150 | Loss: 0.0161 | Val Loss: 0.0152 | Val Qini: 0.6460 (patience: 18/20)EMA Trend: 0.6804 | (patience: 18/20)
Epoch 36/150 | Loss: 0.0202 | Val Loss: 0.0151 | Val Qini: 0.6424 (patience: 19/20)EMA Trend: 0.6747 | (patience: 19/20)
Epoch 37/150 | Loss: 0.0195 | Val Loss: 0.0151 | Val Qini: 0.6280 (patience: 20/20)EMA Trend: 0.6677 | (patience: 20/20)

🛑 Early stopping triggered at epoch 37!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 17
   Best Raw Qini: 0.8643
   Final EMA Trend: 0.6677
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 42
Locked random seed: 1874
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 1
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Loss: 0.4961 | Val Loss: 0.4938 | Val Qini: 0.2911 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.2911 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.4880 | Val Loss: 0.4855 | Val Qini: 0.3260 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.2964 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Loss: 0.4790 | Val Loss: 0.4766 | Val Qini: 0.5349 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.3322 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Loss: 0.4694 | Val Loss: 0.4668 | Val Qini: 0.7267 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.3913 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/150 | Loss: 0.4592 | Val Loss: 0.4555 | Val Qini: 0.7557 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.4460 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/150 | Loss: 0.4460 | Val Loss: 0.4417 | Val Qini: 0.7405 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.4902 | ✓ above trend but not peak (patience: 1/20)
Epoch 7/150 | Loss: 0.4296 | Val Loss: 0.4243 | Val Qini: 0.7766 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5331 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/150 | Loss: 0.4082 | Val Loss: 0.4021 | Val Qini: 0.8322 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5780 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/150 | Loss: 0.3823 | Val Loss: 0.3739 | Val Qini: 0.8598 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6203 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/150 | Loss: 0.3487 | Val Loss: 0.3384 | Val Qini: 0.9086 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6635 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/150 | Loss: 0.3085 | Val Loss: 0.2956 | Val Qini: 0.9197 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7019 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/150 | Loss: 0.2616 | Val Loss: 0.2467 | Val Qini: 0.8294 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.7211 | ✓ above trend but not peak (patience: 1/20)
Epoch 13/150 | Loss: 0.2084 | Val Loss: 0.1941 | Val Qini: 0.8102 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.7344 | ✓ above trend but not peak (patience: 2/20)
Epoch 14/150 | Loss: 0.1576 | Val Loss: 0.1421 | Val Qini: 0.8057 ✓ above trend but not peak (patience: 3/20)EMA Trend: 0.7451 | ✓ above trend but not peak (patience: 3/20)
Epoch 15/150 | Loss: 0.1120 | Val Loss: 0.0966 | Val Qini: 0.8215 ✓ above trend but not peak (patience: 4/20)EMA Trend: 0.7566 | ✓ above trend but not peak (patience: 4/20)
Epoch 16/150 | Loss: 0.0726 | Val Loss: 0.0625 | Val Qini: 0.8376 ✓ above trend but not peak (patience: 5/20)EMA Trend: 0.7687 | ✓ above trend but not peak (patience: 5/20)
Epoch 17/150 | Loss: 0.0490 | Val Loss: 0.0408 | Val Qini: 0.8516 ✓ above trend but not peak (patience: 6/20)EMA Trend: 0.7812 | ✓ above trend but not peak (patience: 6/20)
Epoch 18/150 | Loss: 0.0348 | Val Loss: 0.0287 | Val Qini: 0.8500 ✓ above trend but not peak (patience: 7/20)EMA Trend: 0.7915 | ✓ above trend but not peak (patience: 7/20)
Epoch 19/150 | Loss: 0.0273 | Val Loss: 0.0224 | Val Qini: 0.8550 ✓ above trend but not peak (patience: 8/20)EMA Trend: 0.8010 | ✓ above trend but not peak (patience: 8/20)
Epoch 20/150 | Loss: 0.0300 | Val Loss: 0.0193 | Val Qini: 0.8592 ✓ above trend but not peak (patience: 9/20)EMA Trend: 0.8098 | ✓ above trend but not peak (patience: 9/20)
Epoch 21/150 | Loss: 0.0220 | Val Loss: 0.0176 | Val Qini: 0.8602 ✓ above trend but not peak (patience: 10/20)EMA Trend: 0.8173 | ✓ above trend but not peak (patience: 10/20)
Epoch 22/150 | Loss: 0.0207 | Val Loss: 0.0168 | Val Qini: 0.8685 ✓ above trend but not peak (patience: 11/20)EMA Trend: 0.8250 | ✓ above trend but not peak (patience: 11/20)
Epoch 23/150 | Loss: 0.0214 | Val Loss: 0.0163 | Val Qini: 0.8665 ✓ above trend but not peak (patience: 12/20)EMA Trend: 0.8312 | ✓ above trend but not peak (patience: 12/20)
Epoch 24/150 | Loss: 0.0234 | Val Loss: 0.0160 | Val Qini: 0.8774 ✓ above trend but not peak (patience: 13/20)EMA Trend: 0.8382 | ✓ above trend but not peak (patience: 13/20)
Epoch 25/150 | Loss: 0.0192 | Val Loss: 0.0158 | Val Qini: 0.8794 ✓ above trend but not peak (patience: 14/20)EMA Trend: 0.8443 | ✓ above trend but not peak (patience: 14/20)
Epoch 26/150 | Loss: 0.0199 | Val Loss: 0.0157 | Val Qini: 0.8924 ✓ above trend but not peak (patience: 15/20)EMA Trend: 0.8516 | ✓ above trend but not peak (patience: 15/20)
Epoch 27/150 | Loss: 0.0217 | Val Loss: 0.0157 | Val Qini: 0.8950 ✓ above trend but not peak (patience: 16/20)EMA Trend: 0.8581 | ✓ above trend but not peak (patience: 16/20)
Epoch 28/150 | Loss: 0.0232 | Val Loss: 0.0156 | Val Qini: 0.9045 ✓ above trend but not peak (patience: 17/20)EMA Trend: 0.8650 | ✓ above trend but not peak (patience: 17/20)
Epoch 29/150 | Loss: 0.0207 | Val Loss: 0.0156 | Val Qini: 0.9118 ✓ above trend but not peak (patience: 18/20)EMA Trend: 0.8720 | ✓ above trend but not peak (patience: 18/20)
Epoch 30/150 | Loss: 0.0190 | Val Loss: 0.0156 | Val Qini: 0.9234 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.8797 | ⭐ NEW BEST (peak ≥ trend)
Epoch 31/150 | Loss: 0.0203 | Val Loss: 0.0156 | Val Qini: 0.9274 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.8869 | ⭐ NEW BEST (peak ≥ trend)
Epoch 32/150 | Loss: 0.0222 | Val Loss: 0.0155 | Val Qini: 0.9402 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.8949 | ⭐ NEW BEST (peak ≥ trend)
Epoch 33/150 | Loss: 0.0227 | Val Loss: 0.0155 | Val Qini: 0.9356 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.9010 | ✓ above trend but not peak (patience: 1/20)
Epoch 34/150 | Loss: 0.0239 | Val Loss: 0.0155 | Val Qini: 0.9349 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.9061 | ✓ above trend but not peak (patience: 2/20)
Epoch 35/150 | Loss: 0.0182 | Val Loss: 0.0155 | Val Qini: 0.9444 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.9118 | ⭐ NEW BEST (peak ≥ trend)
Epoch 36/150 | Loss: 0.0233 | Val Loss: 0.0155 | Val Qini: 0.9556 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.9184 | ⭐ NEW BEST (peak ≥ trend)
Epoch 37/150 | Loss: 0.0190 | Val Loss: 0.0155 | Val Qini: 0.9514 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.9233 | ✓ above trend but not peak (patience: 1/20)
Epoch 38/150 | Loss: 0.0206 | Val Loss: 0.0155 | Val Qini: 0.9522 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.9277 | ✓ above trend but not peak (patience: 2/20)
Epoch 39/150 | Loss: 0.0173 | Val Loss: 0.0155 | Val Qini: 0.9524 ✓ above trend but not peak (patience: 3/20)EMA Trend: 0.9314 | ✓ above trend but not peak (patience: 3/20)
Epoch 40/150 | Loss: 0.0217 | Val Loss: 0.0155 | Val Qini: 0.9187 (patience: 4/20)EMA Trend: 0.9295 | (patience: 4/20)
Epoch 41/150 | Loss: 0.0222 | Val Loss: 0.0155 | Val Qini: 0.8980 (patience: 5/20)EMA Trend: 0.9248 | (patience: 5/20)
Epoch 42/150 | Loss: 0.0191 | Val Loss: 0.0155 | Val Qini: 0.8692 (patience: 6/20)EMA Trend: 0.9164 | (patience: 6/20)
Epoch 43/150 | Loss: 0.0134 | Val Loss: 0.0155 | Val Qini: 0.8543 (patience: 7/20)EMA Trend: 0.9071 | (patience: 7/20)
Epoch 44/150 | Loss: 0.0188 | Val Loss: 0.0155 | Val Qini: 0.8199 (patience: 8/20)EMA Trend: 0.8940 | (patience: 8/20)
Epoch 45/150 | Loss: 0.0218 | Val Loss: 0.0154 | Val Qini: 0.7756 (patience: 9/20)EMA Trend: 0.8763 | (patience: 9/20)
Epoch 46/150 | Loss: 0.0200 | Val Loss: 0.0154 | Val Qini: 0.7515 (patience: 10/20)EMA Trend: 0.8576 | (patience: 10/20)
Epoch 47/150 | Loss: 0.0172 | Val Loss: 0.0154 | Val Qini: 0.7278 (patience: 11/20)EMA Trend: 0.8381 | (patience: 11/20)
Epoch 48/150 | Loss: 0.0180 | Val Loss: 0.0154 | Val Qini: 0.6997 (patience: 12/20)EMA Trend: 0.8173 | (patience: 12/20)
Epoch 49/150 | Loss: 0.0176 | Val Loss: 0.0154 | Val Qini: 0.6802 (patience: 13/20)EMA Trend: 0.7968 | (patience: 13/20)
Epoch 50/150 | Loss: 0.0173 | Val Loss: 0.0154 | Val Qini: 0.6627 (patience: 14/20)EMA Trend: 0.7767 | (patience: 14/20)
Epoch 51/150 | Loss: 0.0204 | Val Loss: 0.0154 | Val Qini: 0.6426 (patience: 15/20)EMA Trend: 0.7566 | (patience: 15/20)
Epoch 52/150 | Loss: 0.0212 | Val Loss: 0.0154 | Val Qini: 0.6244 (patience: 16/20)EMA Trend: 0.7367 | (patience: 16/20)
Epoch 53/150 | Loss: 0.0222 | Val Loss: 0.0154 | Val Qini: 0.6094 (patience: 17/20)EMA Trend: 0.7176 | (patience: 17/20)
Epoch 54/150 | Loss: 0.0214 | Val Loss: 0.0153 | Val Qini: 0.5942 (patience: 18/20)EMA Trend: 0.6991 | (patience: 18/20)
Epoch 55/150 | Loss: 0.0190 | Val Loss: 0.0153 | Val Qini: 0.5868 (patience: 19/20)EMA Trend: 0.6823 | (patience: 19/20)
Epoch 56/150 | Loss: 0.0158 | Val Loss: 0.0153 | Val Qini: 0.5688 (patience: 20/20)EMA Trend: 0.6652 | (patience: 20/20)

🛑 Early stopping triggered at epoch 56!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 36
   Best Raw Qini: 0.9556
   Final EMA Trend: 0.6652
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 1874
Locked random seed: 902745
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 1
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Loss: 0.5096 | Val Loss: 0.5071 | Val Qini: 0.8809 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.8809 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.4997 | Val Loss: 0.4971 | Val Qini: 0.8915 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.8825 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Loss: 0.4892 | Val Loss: 0.4863 | Val Qini: 0.8350 (patience: 1/20)EMA Trend: 0.8753 | (patience: 1/20)
Epoch 4/150 | Loss: 0.4778 | Val Loss: 0.4744 | Val Qini: 0.7518 (patience: 2/20)EMA Trend: 0.8568 | (patience: 2/20)
Epoch 5/150 | Loss: 0.4645 | Val Loss: 0.4602 | Val Qini: 0.7816 (patience: 3/20)EMA Trend: 0.8455 | (patience: 3/20)
Epoch 6/150 | Loss: 0.4479 | Val Loss: 0.4427 | Val Qini: 0.8207 (patience: 4/20)EMA Trend: 0.8418 | (patience: 4/20)
Epoch 7/150 | Loss: 0.4270 | Val Loss: 0.4210 | Val Qini: 0.8379 (patience: 5/20)EMA Trend: 0.8412 | (patience: 5/20)
Epoch 8/150 | Loss: 0.4027 | Val Loss: 0.3946 | Val Qini: 0.7849 (patience: 6/20)EMA Trend: 0.8328 | (patience: 6/20)
Epoch 9/150 | Loss: 0.3727 | Val Loss: 0.3627 | Val Qini: 0.7830 (patience: 7/20)EMA Trend: 0.8253 | (patience: 7/20)
Epoch 10/150 | Loss: 0.3350 | Val Loss: 0.3241 | Val Qini: 0.7638 (patience: 8/20)EMA Trend: 0.8161 | (patience: 8/20)
Epoch 11/150 | Loss: 0.2922 | Val Loss: 0.2777 | Val Qini: 0.7298 (patience: 9/20)EMA Trend: 0.8031 | (patience: 9/20)
Epoch 12/150 | Loss: 0.2391 | Val Loss: 0.2249 | Val Qini: 0.6951 (patience: 10/20)EMA Trend: 0.7869 | (patience: 10/20)
Epoch 13/150 | Loss: 0.1874 | Val Loss: 0.1698 | Val Qini: 0.6836 (patience: 11/20)EMA Trend: 0.7714 | (patience: 11/20)
Epoch 14/150 | Loss: 0.1354 | Val Loss: 0.1186 | Val Qini: 0.5608 (patience: 12/20)EMA Trend: 0.7398 | (patience: 12/20)
Epoch 15/150 | Loss: 0.0926 | Val Loss: 0.0775 | Val Qini: 0.1407 (patience: 13/20)EMA Trend: 0.6500 | (patience: 13/20)
Epoch 16/150 | Loss: 0.0578 | Val Loss: 0.0496 | Val Qini: 0.1642 (patience: 14/20)EMA Trend: 0.5771 | (patience: 14/20)
Epoch 17/150 | Loss: 0.0442 | Val Loss: 0.0332 | Val Qini: 0.1910 (patience: 15/20)EMA Trend: 0.5192 | (patience: 15/20)
Epoch 18/150 | Loss: 0.0301 | Val Loss: 0.0247 | Val Qini: 0.1960 (patience: 16/20)EMA Trend: 0.4707 | (patience: 16/20)
Epoch 19/150 | Loss: 0.0235 | Val Loss: 0.0206 | Val Qini: 0.1947 (patience: 17/20)EMA Trend: 0.4293 | (patience: 17/20)
Epoch 20/150 | Loss: 0.0246 | Val Loss: 0.0185 | Val Qini: 0.1972 (patience: 18/20)EMA Trend: 0.3945 | (patience: 18/20)
Epoch 21/150 | Loss: 0.0200 | Val Loss: 0.0175 | Val Qini: 0.1977 (patience: 19/20)EMA Trend: 0.3650 | (patience: 19/20)
Epoch 22/150 | Loss: 0.0296 | Val Loss: 0.0170 | Val Qini: 0.2036 (patience: 20/20)EMA Trend: 0.3408 | (patience: 20/20)

🛑 Early stopping triggered at epoch 22!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 2
   Best Raw Qini: 0.8915
   Final EMA Trend: 0.3408
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 902745
Locked random seed: 1
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 1
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Loss: 0.5066 | Val Loss: 0.5051 | Val Qini: 0.7054 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7054 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.4998 | Val Loss: 0.4982 | Val Qini: 0.7477 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7117 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Loss: 0.4927 | Val Loss: 0.4907 | Val Qini: 0.7070 (patience: 1/20)EMA Trend: 0.7110 | (patience: 1/20)
Epoch 4/150 | Loss: 0.4842 | Val Loss: 0.4819 | Val Qini: 0.6916 (patience: 2/20)EMA Trend: 0.7081 | (patience: 2/20)
Epoch 5/150 | Loss: 0.4742 | Val Loss: 0.4713 | Val Qini: 0.7523 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7147 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/150 | Loss: 0.4622 | Val Loss: 0.4582 | Val Qini: 0.7554 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7208 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/150 | Loss: 0.4469 | Val Loss: 0.4422 | Val Qini: 0.7213 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.7209 | ✓ above trend but not peak (patience: 1/20)
Epoch 8/150 | Loss: 0.4279 | Val Loss: 0.4224 | Val Qini: 0.6674 (patience: 2/20)EMA Trend: 0.7129 | (patience: 2/20)
Epoch 9/150 | Loss: 0.4048 | Val Loss: 0.3969 | Val Qini: 0.4563 (patience: 3/20)EMA Trend: 0.6744 | (patience: 3/20)
Epoch 10/150 | Loss: 0.3732 | Val Loss: 0.3642 | Val Qini: 0.2440 (patience: 4/20)EMA Trend: 0.6098 | (patience: 4/20)
Epoch 11/150 | Loss: 0.3344 | Val Loss: 0.3225 | Val Qini: 0.2481 (patience: 5/20)EMA Trend: 0.5556 | (patience: 5/20)
Epoch 12/150 | Loss: 0.2876 | Val Loss: 0.2724 | Val Qini: 0.2157 (patience: 6/20)EMA Trend: 0.5046 | (patience: 6/20)
Epoch 13/150 | Loss: 0.2333 | Val Loss: 0.2161 | Val Qini: 0.2661 (patience: 7/20)EMA Trend: 0.4688 | (patience: 7/20)
Epoch 14/150 | Loss: 0.1762 | Val Loss: 0.1584 | Val Qini: 0.2866 (patience: 8/20)EMA Trend: 0.4415 | (patience: 8/20)
Epoch 15/150 | Loss: 0.1199 | Val Loss: 0.1067 | Val Qini: 0.3012 (patience: 9/20)EMA Trend: 0.4204 | (patience: 9/20)
Epoch 16/150 | Loss: 0.0768 | Val Loss: 0.0677 | Val Qini: 0.4802 ✓ above trend but not peak (patience: 10/20)EMA Trend: 0.4294 | ✓ above trend but not peak (patience: 10/20)
Epoch 17/150 | Loss: 0.0572 | Val Loss: 0.0433 | Val Qini: 0.5488 ✓ above trend but not peak (patience: 11/20)EMA Trend: 0.4473 | ✓ above trend but not peak (patience: 11/20)
Epoch 18/150 | Loss: 0.0341 | Val Loss: 0.0304 | Val Qini: 0.6089 ✓ above trend but not peak (patience: 12/20)EMA Trend: 0.4716 | ✓ above trend but not peak (patience: 12/20)
Epoch 19/150 | Loss: 0.0322 | Val Loss: 0.0243 | Val Qini: 0.6660 ✓ above trend but not peak (patience: 13/20)EMA Trend: 0.5007 | ✓ above trend but not peak (patience: 13/20)
Epoch 20/150 | Loss: 0.0366 | Val Loss: 0.0215 | Val Qini: 0.6913 ✓ above trend but not peak (patience: 14/20)EMA Trend: 0.5293 | ✓ above trend but not peak (patience: 14/20)
Epoch 21/150 | Loss: 0.0203 | Val Loss: 0.0202 | Val Qini: 0.6959 ✓ above trend but not peak (patience: 15/20)EMA Trend: 0.5543 | ✓ above trend but not peak (patience: 15/20)
Epoch 22/150 | Loss: 0.0283 | Val Loss: 0.0195 | Val Qini: 0.7092 ✓ above trend but not peak (patience: 16/20)EMA Trend: 0.5775 | ✓ above trend but not peak (patience: 16/20)
Epoch 23/150 | Loss: 0.0198 | Val Loss: 0.0190 | Val Qini: 0.7140 ✓ above trend but not peak (patience: 17/20)EMA Trend: 0.5980 | ✓ above trend but not peak (patience: 17/20)
Epoch 24/150 | Loss: 0.0249 | Val Loss: 0.0187 | Val Qini: 0.7191 ✓ above trend but not peak (patience: 18/20)EMA Trend: 0.6162 | ✓ above trend but not peak (patience: 18/20)
Epoch 25/150 | Loss: 0.0274 | Val Loss: 0.0185 | Val Qini: 0.7119 ✓ above trend but not peak (patience: 19/20)EMA Trend: 0.6305 | ✓ above trend but not peak (patience: 19/20)
Epoch 26/150 | Loss: 0.0313 | Val Loss: 0.0183 | Val Qini: 0.7093 ✓ above trend but not peak (patience: 20/20)EMA Trend: 0.6423 | ✓ above trend but not peak (patience: 20/20)

🛑 Early stopping triggered at epoch 26!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 6
   Best Raw Qini: 0.7554
   Final EMA Trend: 0.6423
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 1

=====================================================================================
                                 CHI TIẾT TỪNG SEED
=====================================================================================
  Seed   AUUC   AUQC   Lift   KRCC ATE_Err
412312 0.6764 0.6763 0.0041 0.0742  0.0334
    42 0.5452 0.5414 0.0026 0.0315  0.0908
  1874 0.7362 0.7334 0.0084 0.0965  0.0030
902745 0.6486 0.6484 0.0068 0.1048  0.0232
     1 0.6745 0.6686 0.0072 0.0986  0.0090
=====================================================================================
                           KẾT QUẢ TRUNG BÌNH (MEAN ± STD)
-------------------------------------------------------------------------------------
AUUC      : 0.6562 ± 0.0699
AUQC      : 0.6536 ± 0.0702
Lift      : 0.0058 ± 0.0024
KRCC      : 0.0811 ± 0.0300
ATE_Err   : 0.0319 ± 0.0350
=====================================================================================

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

In [14]:
import pandas as pd
import numpy as np
import torch

# 1. Cấu hình
seeds = [4212312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

print(f"🔄 Đang huấn luyện TARNet trên {len(seeds)} seeds khác nhau... Vui lòng đợi.")

# 2. Vòng lặp chạy (Chỉ xử lý, không in kết quả lẻ)
for SEED in seeds:
    seed_everything(SEED)
    
    # Khởi tạo lại mô hình
    cfrnet = CFRnet(
        input_dim=x_men_train_t.shape[1], epochs=epochs, learning_rate=0.000158, 
        alpha=1, method="mmd_rbf",
        weight_decay=0.000021, use_ema=ema, ema_alpha=ema_alpha, patience=patience,
        shared_hidden=shared_hidden, outcome_hidden=outcome_hidden,
        early_stop_metric=early_stop_metric, early_stop_start_epoch=early_stop_start,
        activation=activation
    )
    
    cfrnet.fit(train_loader, val_loader)
    
    # Predict
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = cfrnet.predict(x_men_test_t_on_device)
    
    uplift_pred = (y1_pred - y0_pred).cpu().numpy().flatten()
    y_true = y_men_test_t.cpu().numpy().flatten()
    t_true = t_men_test_t.cpu().numpy().flatten()
    
    # Tính toán
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()
    
    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  ✔️ Đã xong Seed {SEED}")

# 3. HIỂN THỊ KẾT QUẢ TỔNG HỢP (Print 1 lúc)
df_results = pd.DataFrame(all_runs)

print("\n" + "="*85)
print(f"{'CHI TIẾT TỪNG SEED':^85}")
print("="*85)
# Sử dụng to_string để in bảng đẹp mắt
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format, 'AUQC': '{:,.4f}'.format, 
    'Lift': '{:,.4f}'.format, 'KRCC': '{:,.4f}'.format, 'ATE_Err': '{:,.4f}'.format
}))

# 4. Tính toán Mean và Std
mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("="*85)
print(f"{'KẾT QUẢ TRUNG BÌNH (MEAN ± STD)':^85}")
print("-" * 85)
summary_data = []
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")

print("="*85)

🔄 Đang huấn luyện TARNet trên 5 seeds khác nhau... Vui lòng đợi.
Locked random seed: 4212312
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 1
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/150 | Loss: 0.4937 | Val Loss: 0.4914 | Val Qini: 1.0413 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.0413 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.4846 | Val Loss: 0.4819 | Val Qini: 1.1402 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.0561 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Loss: 0.4741 | Val Loss: 0.4710 | Val Qini: 1.0283 (patience: 1/20)EMA Trend: 1.0519 | (patience: 1/20)
Epoch 4/150 | Loss: 0.4615 | Val Loss: 0.4572 | Val Qini: 0.9413 (patience: 2/20)EMA Trend: 1.0353 | (patience: 2/20)
Epoch 5/150 | Loss: 0.4446 | Val Loss: 0.4388 | Val Qini: 0.9158 (patience: 3/20)EMA Trend: 1.0174 | (patience: 3/20)
Epoch 6/150 | Loss: 0.4216 | Val Loss: 0.4144 | Val Qini: 0.9747 (patience: 4/20)EMA Trend: 1.0110 | (patience: 4/20)
Epoch 7/150 | Loss: 0.3925 | Val Loss: 0.3826 | Val Qini: 1.0544 ✓ above trend but not peak (patience: 5/20)EMA Trend: 1.0175 | ✓ above trend but not peak (patience: 5/20)
Epoch 8/150 | Loss: 0.3528 | Val Loss: 0.3402 | Val Qini: 1.0793 ✓ above trend but not peak (patience: 6/20)EMA Trend: 1.0268 | ✓ above trend but not peak (patience: 6/20)
Epoch 9/150 | Loss: 0.3023 | Val Loss: 0.2856 | Val Qini: 1.0649 ✓ above trend but not peak (patience: 7/20)EMA Trend: 1.0325 | ✓ above trend but not peak (patience: 7/20)
Epoch 10/150 | Loss: 0.2414 | Val Loss: 0.2202 | Val Qini: 1.0481 ✓ above trend but not peak (patience: 8/20)EMA Trend: 1.0348 | ✓ above trend but not peak (patience: 8/20)
Epoch 11/150 | Loss: 0.1695 | Val Loss: 0.1512 | Val Qini: 1.0378 ✓ above trend but not peak (patience: 9/20)EMA Trend: 1.0353 | ✓ above trend but not peak (patience: 9/20)
Epoch 12/150 | Loss: 0.1067 | Val Loss: 0.0911 | Val Qini: 0.6582 (patience: 10/20)EMA Trend: 0.9787 | (patience: 10/20)
Epoch 13/150 | Loss: 0.0614 | Val Loss: 0.0502 | Val Qini: 0.2695 (patience: 11/20)EMA Trend: 0.8723 | (patience: 11/20)
Epoch 14/150 | Loss: 0.0353 | Val Loss: 0.0289 | Val Qini: 0.0994 (patience: 12/20)EMA Trend: 0.7564 | (patience: 12/20)
Epoch 15/150 | Loss: 0.0244 | Val Loss: 0.0200 | Val Qini: 0.0701 (patience: 13/20)EMA Trend: 0.6535 | (patience: 13/20)
Epoch 16/150 | Loss: 0.0181 | Val Loss: 0.0166 | Val Qini: 0.0602 (patience: 14/20)EMA Trend: 0.5645 | (patience: 14/20)
Epoch 17/150 | Loss: 0.0213 | Val Loss: 0.0154 | Val Qini: 0.0535 (patience: 15/20)EMA Trend: 0.4878 | (patience: 15/20)
Epoch 18/150 | Loss: 0.0186 | Val Loss: 0.0149 | Val Qini: 0.0492 (patience: 16/20)EMA Trend: 0.4220 | (patience: 16/20)
Epoch 19/150 | Loss: 0.0195 | Val Loss: 0.0147 | Val Qini: 0.0465 (patience: 17/20)EMA Trend: 0.3657 | (patience: 17/20)
Epoch 20/150 | Loss: 0.0168 | Val Loss: 0.0146 | Val Qini: 0.0494 (patience: 18/20)EMA Trend: 0.3183 | (patience: 18/20)
Epoch 21/150 | Loss: 0.0200 | Val Loss: 0.0146 | Val Qini: 0.0480 (patience: 19/20)EMA Trend: 0.2777 | (patience: 19/20)
Epoch 22/150 | Loss: 0.0194 | Val Loss: 0.0146 | Val Qini: 0.0508 (patience: 20/20)EMA Trend: 0.2437 | (patience: 20/20)

🛑 Early stopping triggered at epoch 22!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 2
   Best Raw Qini: 1.1402
   Final EMA Trend: 0.2437
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 4212312
Locked random seed: 42
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 1
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Loss: 0.5160 | Val Loss: 0.5134 | Val Qini: 0.0432 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.0432 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.5059 | Val Loss: 0.5032 | Val Qini: -0.1289 (patience: 1/20)EMA Trend: 0.0174 | (patience: 1/20)
Epoch 3/150 | Loss: 0.4951 | Val Loss: 0.4916 | Val Qini: -0.1698 (patience: 2/20)EMA Trend: -0.0107 | (patience: 2/20)
Epoch 4/150 | Loss: 0.4815 | Val Loss: 0.4773 | Val Qini: -0.1088 (patience: 3/20)EMA Trend: -0.0254 | (patience: 3/20)
Epoch 5/150 | Loss: 0.4644 | Val Loss: 0.4588 | Val Qini: -0.0456 (patience: 4/20)EMA Trend: -0.0284 | (patience: 4/20)
Epoch 6/150 | Loss: 0.4413 | Val Loss: 0.4344 | Val Qini: 0.0512 ⭐ NEW BEST (peak ≥ trend)EMA Trend: -0.0165 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/150 | Loss: 0.4105 | Val Loss: 0.4009 | Val Qini: 0.1844 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.0136 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/150 | Loss: 0.3688 | Val Loss: 0.3559 | Val Qini: 0.2154 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.0439 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/150 | Loss: 0.3150 | Val Loss: 0.2983 | Val Qini: 0.2085 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.0686 | ✓ above trend but not peak (patience: 1/20)
Epoch 10/150 | Loss: 0.2486 | Val Loss: 0.2294 | Val Qini: 0.2137 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.0904 | ✓ above trend but not peak (patience: 2/20)
Epoch 11/150 | Loss: 0.1773 | Val Loss: 0.1579 | Val Qini: 0.2283 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1111 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/150 | Loss: 0.1130 | Val Loss: 0.0966 | Val Qini: 0.5037 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1700 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/150 | Loss: 0.0670 | Val Loss: 0.0548 | Val Qini: 0.8736 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.2755 | ⭐ NEW BEST (peak ≥ trend)
Epoch 14/150 | Loss: 0.0352 | Val Loss: 0.0320 | Val Qini: 0.8345 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.3593 | ✓ above trend but not peak (patience: 1/20)
Epoch 15/150 | Loss: 0.0276 | Val Loss: 0.0217 | Val Qini: 0.8256 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.4293 | ✓ above trend but not peak (patience: 2/20)
Epoch 16/150 | Loss: 0.0242 | Val Loss: 0.0175 | Val Qini: 0.8179 ✓ above trend but not peak (patience: 3/20)EMA Trend: 0.4876 | ✓ above trend but not peak (patience: 3/20)
Epoch 17/150 | Loss: 0.0202 | Val Loss: 0.0158 | Val Qini: 0.8152 ✓ above trend but not peak (patience: 4/20)EMA Trend: 0.5367 | ✓ above trend but not peak (patience: 4/20)
Epoch 18/150 | Loss: 0.0193 | Val Loss: 0.0151 | Val Qini: 0.8064 ✓ above trend but not peak (patience: 5/20)EMA Trend: 0.5772 | ✓ above trend but not peak (patience: 5/20)
Epoch 19/150 | Loss: 0.0219 | Val Loss: 0.0148 | Val Qini: 0.8006 ✓ above trend but not peak (patience: 6/20)EMA Trend: 0.6107 | ✓ above trend but not peak (patience: 6/20)
Epoch 20/150 | Loss: 0.0170 | Val Loss: 0.0147 | Val Qini: 0.7979 ✓ above trend but not peak (patience: 7/20)EMA Trend: 0.6388 | ✓ above trend but not peak (patience: 7/20)
Epoch 21/150 | Loss: 0.0172 | Val Loss: 0.0146 | Val Qini: 0.8034 ✓ above trend but not peak (patience: 8/20)EMA Trend: 0.6634 | ✓ above trend but not peak (patience: 8/20)
Epoch 22/150 | Loss: 0.0174 | Val Loss: 0.0145 | Val Qini: 0.7920 ✓ above trend but not peak (patience: 9/20)EMA Trend: 0.6827 | ✓ above trend but not peak (patience: 9/20)
Epoch 23/150 | Loss: 0.0172 | Val Loss: 0.0145 | Val Qini: 0.7947 ✓ above trend but not peak (patience: 10/20)EMA Trend: 0.6995 | ✓ above trend but not peak (patience: 10/20)
Epoch 24/150 | Loss: 0.0174 | Val Loss: 0.0145 | Val Qini: 0.7932 ✓ above trend but not peak (patience: 11/20)EMA Trend: 0.7136 | ✓ above trend but not peak (patience: 11/20)
Epoch 25/150 | Loss: 0.0157 | Val Loss: 0.0145 | Val Qini: 0.7877 ✓ above trend but not peak (patience: 12/20)EMA Trend: 0.7247 | ✓ above trend but not peak (patience: 12/20)
Epoch 26/150 | Loss: 0.0174 | Val Loss: 0.0145 | Val Qini: 0.7875 ✓ above trend but not peak (patience: 13/20)EMA Trend: 0.7341 | ✓ above trend but not peak (patience: 13/20)
Epoch 27/150 | Loss: 0.0179 | Val Loss: 0.0145 | Val Qini: 0.7889 ✓ above trend but not peak (patience: 14/20)EMA Trend: 0.7423 | ✓ above trend but not peak (patience: 14/20)
Epoch 28/150 | Loss: 0.0190 | Val Loss: 0.0145 | Val Qini: 0.7857 ✓ above trend but not peak (patience: 15/20)EMA Trend: 0.7488 | ✓ above trend but not peak (patience: 15/20)
Epoch 29/150 | Loss: 0.0194 | Val Loss: 0.0144 | Val Qini: 0.7841 ✓ above trend but not peak (patience: 16/20)EMA Trend: 0.7541 | ✓ above trend but not peak (patience: 16/20)
Epoch 30/150 | Loss: 0.0186 | Val Loss: 0.0144 | Val Qini: 0.7797 ✓ above trend but not peak (patience: 17/20)EMA Trend: 0.7580 | ✓ above trend but not peak (patience: 17/20)
Epoch 31/150 | Loss: 0.0183 | Val Loss: 0.0144 | Val Qini: 0.7740 ✓ above trend but not peak (patience: 18/20)EMA Trend: 0.7604 | ✓ above trend but not peak (patience: 18/20)
Epoch 32/150 | Loss: 0.0142 | Val Loss: 0.0144 | Val Qini: 0.7755 ✓ above trend but not peak (patience: 19/20)EMA Trend: 0.7626 | ✓ above trend but not peak (patience: 19/20)
Epoch 33/150 | Loss: 0.0170 | Val Loss: 0.0144 | Val Qini: 0.7740 ✓ above trend but not peak (patience: 20/20)EMA Trend: 0.7643 | ✓ above trend but not peak (patience: 20/20)

🛑 Early stopping triggered at epoch 33!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 13
   Best Raw Qini: 0.8736
   Final EMA Trend: 0.7643
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 42
Locked random seed: 1874
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 1
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Loss: 0.4936 | Val Loss: 0.4904 | Val Qini: 0.3094 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.3094 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.4820 | Val Loss: 0.4784 | Val Qini: 0.4704 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.3336 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Loss: 0.4689 | Val Loss: 0.4652 | Val Qini: 0.7329 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.3935 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Loss: 0.4538 | Val Loss: 0.4494 | Val Qini: 0.7245 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.4431 | ✓ above trend but not peak (patience: 1/20)
Epoch 5/150 | Loss: 0.4352 | Val Loss: 0.4286 | Val Qini: 0.7166 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.4842 | ✓ above trend but not peak (patience: 2/20)
Epoch 6/150 | Loss: 0.4093 | Val Loss: 0.4007 | Val Qini: 0.8135 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5336 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/150 | Loss: 0.3744 | Val Loss: 0.3631 | Val Qini: 0.8597 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5825 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/150 | Loss: 0.3271 | Val Loss: 0.3138 | Val Qini: 0.9223 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6335 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/150 | Loss: 0.2705 | Val Loss: 0.2534 | Val Qini: 0.8635 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.6680 | ✓ above trend but not peak (patience: 1/20)
Epoch 10/150 | Loss: 0.2042 | Val Loss: 0.1862 | Val Qini: 0.8093 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.6892 | ✓ above trend but not peak (patience: 2/20)
Epoch 11/150 | Loss: 0.1390 | Val Loss: 0.1207 | Val Qini: 0.8016 ✓ above trend but not peak (patience: 3/20)EMA Trend: 0.7060 | ✓ above trend but not peak (patience: 3/20)
Epoch 12/150 | Loss: 0.0843 | Val Loss: 0.0693 | Val Qini: 0.8227 ✓ above trend but not peak (patience: 4/20)EMA Trend: 0.7235 | ✓ above trend but not peak (patience: 4/20)
Epoch 13/150 | Loss: 0.0464 | Val Loss: 0.0385 | Val Qini: 0.8391 ✓ above trend but not peak (patience: 5/20)EMA Trend: 0.7409 | ✓ above trend but not peak (patience: 5/20)
Epoch 14/150 | Loss: 0.0317 | Val Loss: 0.0241 | Val Qini: 0.8406 ✓ above trend but not peak (patience: 6/20)EMA Trend: 0.7558 | ✓ above trend but not peak (patience: 6/20)
Epoch 15/150 | Loss: 0.0240 | Val Loss: 0.0184 | Val Qini: 0.8474 ✓ above trend but not peak (patience: 7/20)EMA Trend: 0.7696 | ✓ above trend but not peak (patience: 7/20)
Epoch 16/150 | Loss: 0.0179 | Val Loss: 0.0162 | Val Qini: 0.8527 ✓ above trend but not peak (patience: 8/20)EMA Trend: 0.7820 | ✓ above trend but not peak (patience: 8/20)
Epoch 17/150 | Loss: 0.0181 | Val Loss: 0.0153 | Val Qini: 0.8645 ✓ above trend but not peak (patience: 9/20)EMA Trend: 0.7944 | ✓ above trend but not peak (patience: 9/20)
Epoch 18/150 | Loss: 0.0200 | Val Loss: 0.0149 | Val Qini: 0.8713 ✓ above trend but not peak (patience: 10/20)EMA Trend: 0.8059 | ✓ above trend but not peak (patience: 10/20)
Epoch 19/150 | Loss: 0.0175 | Val Loss: 0.0148 | Val Qini: 0.8802 ✓ above trend but not peak (patience: 11/20)EMA Trend: 0.8171 | ✓ above trend but not peak (patience: 11/20)
Epoch 20/150 | Loss: 0.0185 | Val Loss: 0.0147 | Val Qini: 0.8860 ✓ above trend but not peak (patience: 12/20)EMA Trend: 0.8274 | ✓ above trend but not peak (patience: 12/20)
Epoch 21/150 | Loss: 0.0188 | Val Loss: 0.0146 | Val Qini: 0.8644 ✓ above trend but not peak (patience: 13/20)EMA Trend: 0.8330 | ✓ above trend but not peak (patience: 13/20)
Epoch 22/150 | Loss: 0.0152 | Val Loss: 0.0146 | Val Qini: 0.9008 ✓ above trend but not peak (patience: 14/20)EMA Trend: 0.8431 | ✓ above trend but not peak (patience: 14/20)
Epoch 23/150 | Loss: 0.0192 | Val Loss: 0.0146 | Val Qini: 0.9012 ✓ above trend but not peak (patience: 15/20)EMA Trend: 0.8519 | ✓ above trend but not peak (patience: 15/20)
Epoch 24/150 | Loss: 0.0162 | Val Loss: 0.0146 | Val Qini: 0.8822 ✓ above trend but not peak (patience: 16/20)EMA Trend: 0.8564 | ✓ above trend but not peak (patience: 16/20)
Epoch 25/150 | Loss: 0.0180 | Val Loss: 0.0145 | Val Qini: 0.8289 (patience: 17/20)EMA Trend: 0.8523 | (patience: 17/20)
Epoch 26/150 | Loss: 0.0187 | Val Loss: 0.0145 | Val Qini: 0.7509 (patience: 18/20)EMA Trend: 0.8371 | (patience: 18/20)
Epoch 27/150 | Loss: 0.0186 | Val Loss: 0.0145 | Val Qini: 0.6459 (patience: 19/20)EMA Trend: 0.8084 | (patience: 19/20)
Epoch 28/150 | Loss: 0.0227 | Val Loss: 0.0145 | Val Qini: 0.5816 (patience: 20/20)EMA Trend: 0.7744 | (patience: 20/20)

🛑 Early stopping triggered at epoch 28!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 8
   Best Raw Qini: 0.9223
   Final EMA Trend: 0.7744
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 1874
Locked random seed: 902745
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 1
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Loss: 0.5066 | Val Loss: 0.5030 | Val Qini: 0.8864 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.8864 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.4925 | Val Loss: 0.4885 | Val Qini: 0.8610 (patience: 1/20)EMA Trend: 0.8826 | (patience: 1/20)
Epoch 3/150 | Loss: 0.4770 | Val Loss: 0.4724 | Val Qini: 0.7511 (patience: 2/20)EMA Trend: 0.8629 | (patience: 2/20)
Epoch 4/150 | Loss: 0.4583 | Val Loss: 0.4524 | Val Qini: 0.7956 (patience: 3/20)EMA Trend: 0.8528 | (patience: 3/20)
Epoch 5/150 | Loss: 0.4342 | Val Loss: 0.4263 | Val Qini: 0.8429 (patience: 4/20)EMA Trend: 0.8513 | (patience: 4/20)
Epoch 6/150 | Loss: 0.4026 | Val Loss: 0.3927 | Val Qini: 0.7912 (patience: 5/20)EMA Trend: 0.8423 | (patience: 5/20)
Epoch 7/150 | Loss: 0.3626 | Val Loss: 0.3503 | Val Qini: 0.7787 (patience: 6/20)EMA Trend: 0.8328 | (patience: 6/20)
Epoch 8/150 | Loss: 0.3126 | Val Loss: 0.2964 | Val Qini: 0.7570 (patience: 7/20)EMA Trend: 0.8214 | (patience: 7/20)
Epoch 9/150 | Loss: 0.2508 | Val Loss: 0.2310 | Val Qini: 0.7137 (patience: 8/20)EMA Trend: 0.8052 | (patience: 8/20)
Epoch 10/150 | Loss: 0.1795 | Val Loss: 0.1605 | Val Qini: 0.6812 (patience: 9/20)EMA Trend: 0.7866 | (patience: 9/20)
Epoch 11/150 | Loss: 0.1159 | Val Loss: 0.0974 | Val Qini: 0.3818 (patience: 10/20)EMA Trend: 0.7259 | (patience: 10/20)
Epoch 12/150 | Loss: 0.0619 | Val Loss: 0.0533 | Val Qini: 0.1498 (patience: 11/20)EMA Trend: 0.6395 | (patience: 11/20)
Epoch 13/150 | Loss: 0.0390 | Val Loss: 0.0299 | Val Qini: 0.1838 (patience: 12/20)EMA Trend: 0.5711 | (patience: 12/20)
Epoch 14/150 | Loss: 0.0263 | Val Loss: 0.0202 | Val Qini: 0.1931 (patience: 13/20)EMA Trend: 0.5144 | (patience: 13/20)
Epoch 15/150 | Loss: 0.0242 | Val Loss: 0.0166 | Val Qini: 0.1977 (patience: 14/20)EMA Trend: 0.4669 | (patience: 14/20)
Epoch 16/150 | Loss: 0.0199 | Val Loss: 0.0153 | Val Qini: 0.1973 (patience: 15/20)EMA Trend: 0.4265 | (patience: 15/20)
Epoch 17/150 | Loss: 0.0193 | Val Loss: 0.0148 | Val Qini: 0.1963 (patience: 16/20)EMA Trend: 0.3919 | (patience: 16/20)
Epoch 18/150 | Loss: 0.0187 | Val Loss: 0.0146 | Val Qini: 0.2005 (patience: 17/20)EMA Trend: 0.3632 | (patience: 17/20)
Epoch 19/150 | Loss: 0.0173 | Val Loss: 0.0145 | Val Qini: 0.2007 (patience: 18/20)EMA Trend: 0.3388 | (patience: 18/20)
Epoch 20/150 | Loss: 0.0175 | Val Loss: 0.0145 | Val Qini: 0.1995 (patience: 19/20)EMA Trend: 0.3179 | (patience: 19/20)
Epoch 21/150 | Loss: 0.0171 | Val Loss: 0.0145 | Val Qini: 0.2068 (patience: 20/20)EMA Trend: 0.3013 | (patience: 20/20)

🛑 Early stopping triggered at epoch 21!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 1
   Best Raw Qini: 0.8864
   Final EMA Trend: 0.3013
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 902745
Locked random seed: 1
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 1
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Loss: 0.5044 | Val Loss: 0.5022 | Val Qini: 0.7333 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7333 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.4947 | Val Loss: 0.4922 | Val Qini: 0.7180 (patience: 1/20)EMA Trend: 0.7310 | (patience: 1/20)
Epoch 3/150 | Loss: 0.4837 | Val Loss: 0.4803 | Val Qini: 0.6996 (patience: 2/20)EMA Trend: 0.7263 | (patience: 2/20)
Epoch 4/150 | Loss: 0.4696 | Val Loss: 0.4653 | Val Qini: 0.7779 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7340 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/150 | Loss: 0.4515 | Val Loss: 0.4460 | Val Qini: 0.7444 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.7356 | ✓ above trend but not peak (patience: 1/20)
Epoch 6/150 | Loss: 0.4291 | Val Loss: 0.4210 | Val Qini: 0.6924 (patience: 2/20)EMA Trend: 0.7291 | (patience: 2/20)
Epoch 7/150 | Loss: 0.3975 | Val Loss: 0.3873 | Val Qini: 0.4333 (patience: 3/20)EMA Trend: 0.6848 | (patience: 3/20)
Epoch 8/150 | Loss: 0.3545 | Val Loss: 0.3411 | Val Qini: 0.2665 (patience: 4/20)EMA Trend: 0.6220 | (patience: 4/20)
Epoch 9/150 | Loss: 0.2988 | Val Loss: 0.2808 | Val Qini: 0.2142 (patience: 5/20)EMA Trend: 0.5608 | (patience: 5/20)
Epoch 10/150 | Loss: 0.2286 | Val Loss: 0.2096 | Val Qini: 0.2564 (patience: 6/20)EMA Trend: 0.5152 | (patience: 6/20)
Epoch 11/150 | Loss: 0.1563 | Val Loss: 0.1366 | Val Qini: 0.2790 (patience: 7/20)EMA Trend: 0.4797 | (patience: 7/20)
Epoch 12/150 | Loss: 0.0940 | Val Loss: 0.0767 | Val Qini: 0.3871 (patience: 8/20)EMA Trend: 0.4658 | (patience: 8/20)
Epoch 13/150 | Loss: 0.0506 | Val Loss: 0.0402 | Val Qini: 0.5532 ✓ above trend but not peak (patience: 9/20)EMA Trend: 0.4790 | ✓ above trend but not peak (patience: 9/20)
Epoch 14/150 | Loss: 0.0336 | Val Loss: 0.0238 | Val Qini: 0.6563 ✓ above trend but not peak (patience: 10/20)EMA Trend: 0.5056 | ✓ above trend but not peak (patience: 10/20)
Epoch 15/150 | Loss: 0.0215 | Val Loss: 0.0179 | Val Qini: 0.7109 ✓ above trend but not peak (patience: 11/20)EMA Trend: 0.5364 | ✓ above trend but not peak (patience: 11/20)
Epoch 16/150 | Loss: 0.0182 | Val Loss: 0.0159 | Val Qini: 0.7275 ✓ above trend but not peak (patience: 12/20)EMA Trend: 0.5650 | ✓ above trend but not peak (patience: 12/20)
Epoch 17/150 | Loss: 0.0188 | Val Loss: 0.0152 | Val Qini: 0.7419 ✓ above trend but not peak (patience: 13/20)EMA Trend: 0.5916 | ✓ above trend but not peak (patience: 13/20)
Epoch 18/150 | Loss: 0.0177 | Val Loss: 0.0150 | Val Qini: 0.7455 ✓ above trend but not peak (patience: 14/20)EMA Trend: 0.6147 | ✓ above trend but not peak (patience: 14/20)
Epoch 19/150 | Loss: 0.0206 | Val Loss: 0.0148 | Val Qini: 0.7432 ✓ above trend but not peak (patience: 15/20)EMA Trend: 0.6339 | ✓ above trend but not peak (patience: 15/20)
Epoch 20/150 | Loss: 0.0215 | Val Loss: 0.0148 | Val Qini: 0.7483 ✓ above trend but not peak (patience: 16/20)EMA Trend: 0.6511 | ✓ above trend but not peak (patience: 16/20)
Epoch 21/150 | Loss: 0.0171 | Val Loss: 0.0148 | Val Qini: 0.7455 ✓ above trend but not peak (patience: 17/20)EMA Trend: 0.6652 | ✓ above trend but not peak (patience: 17/20)
Epoch 22/150 | Loss: 0.0162 | Val Loss: 0.0147 | Val Qini: 0.7465 ✓ above trend but not peak (patience: 18/20)EMA Trend: 0.6774 | ✓ above trend but not peak (patience: 18/20)
Epoch 23/150 | Loss: 0.0166 | Val Loss: 0.0147 | Val Qini: 0.7438 ✓ above trend but not peak (patience: 19/20)EMA Trend: 0.6874 | ✓ above trend but not peak (patience: 19/20)
Epoch 24/150 | Loss: 0.0214 | Val Loss: 0.0147 | Val Qini: 0.7383 ✓ above trend but not peak (patience: 20/20)EMA Trend: 0.6950 | ✓ above trend but not peak (patience: 20/20)

🛑 Early stopping triggered at epoch 24!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 4
   Best Raw Qini: 0.7779
   Final EMA Trend: 0.6950
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 1

=====================================================================================
                                 CHI TIẾT TỪNG SEED
=====================================================================================
   Seed   AUUC   AUQC   Lift   KRCC ATE_Err
4212312 0.5595 0.5585 0.0037 0.0525  0.0021
     42 0.5612 0.5571 0.0043 0.0039  0.0977
   1874 0.7214 0.7184 0.0054 0.1245  0.0375
 902745 0.6013 0.6008 0.0037 0.0760  0.0230
      1 0.6884 0.6820 0.0074 0.1038  0.0092
=====================================================================================
                           KẾT QUẢ TRUNG BÌNH (MEAN ± STD)
-------------------------------------------------------------------------------------
AUUC      : 0.6264 ± 0.0746
AUQC      : 0.6234 ± 0.0734
Lift      : 0.0049 ± 0.0016
KRCC      : 0.0722 ± 0.0469
ATE_Err   : 0.0339 ± 0.0382
=====================================================================================

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Conversion/CFRnet/cfrnet.py:275: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)