Import libraries

In [ ]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from cfrnet import CFRnet
import sys
from pathlib import Path
project_root = Path("/home/ducm/Benchmark-conversion-vs-revenue-uplift-modeling")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [ ]:
%time train_df = pd.read_csv(r"../../dataset/Hillstrom/Women/train_women.csv")
%time test_df =  pd.read_csv(r"../../dataset/Hillstrom/Women/test_women.csv")
%time val_df = pd.read_csv(r"../../dataset/Hillstrom/Women/val_women.csv")

In [ ]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['spend']
treatment_feature = ['treatment']

In [ ]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [ ]:
print('X_train[:10]', X_train[:1].astype(float))

In [ ]:
print('y_train[:10]', y_train[:1].astype(float))

In [ ]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

In [ ]:
epochs = 150
alpha = 0.1
lr = 1e-3
wd = 1e-5
method = "mmd_rbf"
early_stop_metric = "qini"
ema = True
ema_alpha = 0.15
patience = 20
early_stop_start = 30
shared_hidden = 200
outcome_hidden = 100
outcome_dropout = 0
shared_dropout = 0.0
activation = torch.nn.ReLU

print (f" epochs = {epochs}")
print (f" method = {method}")
print (f" alpha = {alpha}")
print (f" learning rate = {lr}")
print (f" weight decay = {wd}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" shared hidden = {shared_hidden}")
print (f" outcome hidden = {outcome_hidden}")
print (f"activation = {activation}")

In [9]:
import pandas as pd
import numpy as np
import torch
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 5e-5, 5e-4, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-4, log=True)
    grid_alpha = trial.suggest_categorical("alpha", [0.1, 0.5, 1.0])
    grid_method = trial.suggest_categorical("method", ["mmd_rbf", "mmd_linear"])
    val_scores = []
    for SEED in seeds:
        seed_everything(SEED)

        cfr = CFRnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            alpha=grid_alpha,
            method=grid_method,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=shared_hidden,
            outcome_hidden=outcome_hidden,
            outcome_dropout=outcome_dropout,
            shared_dropout=shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
            activation=activation
        )

        # Silence CFRNet epoch logs
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            cfr.fit(train_loader, val_loader)

        x_val_device = x_men_val_t.to(device)
        y0_val_p, y1_val_p= cfr.predict(x_val_device)
        uplift_val = (y1_val_p - y0_val_p).detach().cpu().numpy().flatten()
        y_val_true_np = y_men_val_t.detach().cpu().numpy().flatten()
        t_val_true_np = t_men_val_t.detach().cpu().numpy().flatten()

        current_val_auqc = auqc(y_val_true_np, t_val_true_np, uplift_val, bins=100, plot=False)
        val_scores.append(current_val_auqc)

    mean_val_auqc = float(np.mean(val_scores))
    std_val_auqc = float(np.std(val_scores, ddof=1)) if len(val_scores) > 1 else 0.0
    trial.set_user_attr("std_Val_AUQC", std_val_auqc)
    return mean_val_auqc

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

# 2. Persist search results in notebook variables
trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": t.params["lr"],
        "weight_decay": t.params["weight_decay"],
        "alpha": t.params["alpha"],
        "method": t.params["method"],
        "mean_Val_AUQC": float(t.value),
        "std_Val_AUQC": float(t.user_attrs.get("std_Val_AUQC", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_Val_AUQC", ascending=False).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "alpha": float(best_params["alpha"]),
    "method": t.params["method"],
    "mean_Val_AUQC": float(study.best_value),
    "std_Val_AUQC": float(study.best_trial.user_attrs.get("std_Val_AUQC", np.nan))
})

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 0. Best value: 1.2285:   2%|▏         | 1/50 [01:04<52:38, 64.46s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 0. Best value: 1.2285:   4%|▍         | 2/50 [02:09<52:01, 65.04s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 1.2313:   6%|▌         | 3/50 [03:23<53:56, 68.87s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 1.2313:   8%|▊         | 4/50 [04:24<50:22, 65.71s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 1.2313:  10%|█         | 5/50 [05:20<46:43, 62.30s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 1.2313:  12%|█▏        | 6/50 [06:30<47:29, 64.77s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 1.2313:  14%|█▍        | 7/50 [07:40<47:45, 66.63s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 1.2313:  16%|█▌        | 8/50 [08:56<48:41, 69.55s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 1.2313:  18%|█▊        | 9/50 [09:54<45:07, 66.03s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 1.2313:  20%|██        | 10/50 [11:01<44:15, 66.38s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 1.2313:  22%|██▏       | 11/50 [13:12<55:52, 85.96s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 1.2313:  24%|██▍       | 12/50 [14:43<55:33, 87.73s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 2. Best value: 1.2313:  26%|██▌       | 13/50 [16:18<55:25, 89.89s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 13. Best value: 1.23243:  28%|██▊       | 14/50 [17:43<53:00, 88.34s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 14. Best value: 1.23444:  30%|███       | 15/50 [19:07<50:43, 86.97s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 14. Best value: 1.23444:  32%|███▏      | 16/50 [20:53<52:38, 92.91s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 14. Best value: 1.23444:  34%|███▍      | 17/50 [22:15<49:16, 89.61s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 17. Best value: 1.23768:  36%|███▌      | 18/50 [23:39<46:47, 87.73s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 17. Best value: 1.23768:  38%|███▊      | 19/50 [25:27<48:35, 94.04s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 17. Best value: 1.23768:  40%|████      | 20/50 [26:58<46:33, 93.12s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 17. Best value: 1.23768:  42%|████▏     | 21/50 [28:18<42:59, 88.96s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 1.24164:  44%|████▍     | 22/50 [29:42<40:51, 87.54s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 1.24164:  46%|████▌     | 23/50 [31:07<39:02, 86.74s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 1.24164:  48%|████▊     | 24/50 [32:42<38:40, 89.24s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 1.24164:  50%|█████     | 25/50 [34:43<41:10, 98.82s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 1.24164:  52%|█████▏    | 26/50 [36:04<37:20, 93.36s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 1.24164:  54%|█████▍    | 27/50 [37:45<36:41, 95.71s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 1.24164:  56%|█████▌    | 28/50 [39:24<35:30, 96.83s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 1.24164:  58%|█████▊    | 29/50 [40:30<30:37, 87.50s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 1.24164:  60%|██████    | 30/50 [41:41<27:33, 82.66s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 1.24164:  62%|██████▏   | 31/50 [43:14<27:07, 85.67s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 21. Best value: 1.24164:  64%|██████▍   | 32/50 [44:58<27:18, 91.02s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 32. Best value: 1.24288:  66%|██████▌   | 33/50 [46:40<26:47, 94.55s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 33. Best value: 1.25447:  68%|██████▊   | 34/50 [48:20<25:39, 96.20s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 33. Best value: 1.25447:  70%|███████   | 35/50 [50:02<24:28, 97.88s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 35. Best value: 1.25534:  72%|███████▏  | 36/50 [51:49<23:25, 100.39s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 35. Best value: 1.25534:  74%|███████▍  | 37/50 [53:22<21:18, 98.38s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 35. Best value: 1.25534:  76%|███████▌  | 38/50 [54:34<18:05, 90.43s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 38. Best value: 1.26157:  78%|███████▊  | 39/50 [56:02<16:26, 89.72s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 38. Best value: 1.26157:  80%|████████  | 40/50 [57:19<14:18, 85.81s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 38. Best value: 1.26157:  82%|████████▏ | 41/50 [58:40<12:39, 84.39s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 38. Best value: 1.26157:  84%|████████▍ | 42/50 [59:59<11:01, 82.70s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 38. Best value: 1.26157:  86%|████████▌ | 43/50 [1:01:10<09:15, 79.32s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 38. Best value: 1.26157:  88%|████████▊ | 44/50 [1:02:22<07:43, 77.22s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 38. Best value: 1.26157:  90%|█████████ | 45/50 [1:03:27<06:06, 73.31s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 38. Best value: 1.26157:  92%|█████████▏| 46/50 [1:04:42<04:55, 73.95s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 38. Best value: 1.26157:  94%|█████████▍| 47/50 [1:05:58<03:43, 74.54s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 38. Best value: 1.26157:  96%|█████████▌| 48/50 [1:07:14<02:29, 74.94s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 38. Best value: 1.26157:  98%|█████████▊| 49/50 [1:08:28<01:14, 74.66s/it]

Locked random seed: 412312

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 42

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1874

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 902745

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Locked random seed: 1

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)
Best trial: 38. Best value: 1.26157: 100%|██████████| 50/50 [1:09:30<00:00, 83.41s/it]

In [10]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_AUQC: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 38
Best mean_Val_AUQC: 1.261568
Best params: {'lr': 8.96891731626277e-05, 'weight_decay': 1.0521745552369724e-05, 'alpha': 0.5, 'method': 'mmd_rbf'}

Best config table:

        lr weight_decay alpha   method mean_Val_AUQC std_Val_AUQC
0  0.00009     0.000011   0.5  mmd_rbf      1.261568     0.172405

Top 10 trials:

   trial        lr  weight_decay  alpha   method  mean_Val_AUQC  std_Val_AUQC
0     38  0.000090      0.000011    0.5  mmd_rbf       1.261568      0.172405
1     43  0.000097      0.000013    0.5  mmd_rbf       1.258789      0.164246
2     41  0.000100      0.000012    0.5  mmd_rbf       1.257921      0.169278
3     40  0.000104      0.000012    0.5  mmd_rbf       1.257450      0.164451
4     46  0.000097      0.000011    0.5  mmd_rbf       1.256604      0.166434
5     45  0.000096      0.000010    0.5  mmd_rbf       1.256293      0.167552
6     35  0.000087      0.000017    0.5  mmd_rbf       1.255343      0.173346
7     36  0.000084      0.000017    0.5  mmd_rbf       1.254805      0.165695
8     33  0.000085      0.000019    0.1  mmd_rbf       1.254475      0.170182
9     47  0.000103      0.000011    0.5  mmd_rbf       1.254187      0.164394

In [13]:
import pandas as pd
import numpy as np
import torch

# 1. Cấu hình
seeds = [7,8,9,10,11]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

print(f"🔄 Đang huấn luyện TARNet trên {len(seeds)} seeds khác nhau... Vui lòng đợi.")

# 2. Vòng lặp chạy (Chỉ xử lý, không in kết quả lẻ)
for SEED in seeds:
    seed_everything(SEED)
    
    # Khởi tạo lại mô hình
    cfr = CFRnet(
        input_dim=x_men_train_t.shape[1], epochs=epochs, learning_rate=9.00E-05, 
        alpha = 0.5, method="mmd_rbf",
        weight_decay=1.10E-05, use_ema=ema, ema_alpha=ema_alpha, patience=patience,
        shared_hidden=shared_hidden, outcome_hidden=outcome_hidden,
        outcome_dropout=outcome_dropout, shared_dropout=shared_dropout,
        early_stop_metric=early_stop_metric, early_stop_start_epoch=early_stop_start,
        activation=activation
    )
    
    cfr.fit(train_loader, val_loader)
    
    # Predict
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = cfr.predict(x_men_test_t_on_device)
    
    uplift_pred = (y1_pred - y0_pred).cpu().numpy().flatten()
    y_true = y_men_test_t.cpu().numpy().flatten()
    t_true = t_men_test_t.cpu().numpy().flatten()
    
    # Tính toán
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()
    
    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  ✔️ Đã xong Seed {SEED}")

# 3. HIỂN THỊ KẾT QUẢ TỔNG HỢP (Print 1 lúc)
df_results = pd.DataFrame(all_runs)

print("\n" + "="*85)
print(f"{'CHI TIẾT TỪNG SEED':^85}")
print("="*85)
# Sử dụng to_string để in bảng đẹp mắt
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format, 'AUQC': '{:,.4f}'.format, 
    'Lift': '{:,.4f}'.format, 'KRCC': '{:,.4f}'.format, 'ATE_Err': '{:,.4f}'.format
}))

# 4. Tính toán Mean và Std
mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("="*85)
print(f"{'KẾT QUẢ TRUNG BÌNH (MEAN ± STD)':^85}")
print("-" * 85)
summary_data = []
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")

print("="*85)

🔄 Đang huấn luyện TARNet trên 5 seeds khác nhau... Vui lòng đợi.
Locked random seed: 7
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/150 | Loss: 0.0062 | Val Loss: 193.9340 | Val Qini: 1.1879 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.1879 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.0093 | Val Loss: 193.8902 | Val Qini: 1.1256 (patience: 1/20)EMA Trend: 1.1785 | (patience: 1/20)
Epoch 3/150 | Loss: 112.5429 | Val Loss: 193.8456 | Val Qini: 0.9856 (patience: 2/20)EMA Trend: 1.1496 | (patience: 2/20)
Epoch 4/150 | Loss: 0.0009 | Val Loss: 193.7974 | Val Qini: 0.8104 (patience: 3/20)EMA Trend: 1.0987 | (patience: 3/20)
Epoch 5/150 | Loss: 0.0030 | Val Loss: 193.7462 | Val Qini: 0.6813 (patience: 4/20)EMA Trend: 1.0361 | (patience: 4/20)
Epoch 6/150 | Loss: 697.0491 | Val Loss: 193.6908 | Val Qini: 0.6965 (patience: 5/20)EMA Trend: 0.9851 | (patience: 5/20)
Epoch 7/150 | Loss: 0.0149 | Val Loss: 193.6266 | Val Qini: 0.8255 (patience: 6/20)EMA Trend: 0.9612 | (patience: 6/20)
Epoch 8/150 | Loss: 0.0036 | Val Loss: 193.5568 | Val Qini: 0.8983 (patience: 7/20)EMA Trend: 0.9518 | (patience: 7/20)
Epoch 9/150 | Loss: 6666.3945 | Val Loss: 193.4771 | Val Qini: 0.9708 ✓ above trend but not peak (patience: 8/20)EMA Trend: 0.9546 | ✓ above trend but not peak (patience: 8/20)
Epoch 10/150 | Loss: 0.0505 | Val Loss: 193.3854 | Val Qini: 0.9431 (patience: 9/20)EMA Trend: 0.9529 | (patience: 9/20)
Epoch 11/150 | Loss: 0.0720 | Val Loss: 193.2951 | Val Qini: 0.9579 ✓ above trend but not peak (patience: 10/20)EMA Trend: 0.9536 | ✓ above trend but not peak (patience: 10/20)
Epoch 12/150 | Loss: 0.1131 | Val Loss: 193.2066 | Val Qini: 0.9538 ✓ above trend but not peak (patience: 11/20)EMA Trend: 0.9537 | ✓ above trend but not peak (patience: 11/20)
Epoch 13/150 | Loss: 227.9371 | Val Loss: 193.1127 | Val Qini: 0.9091 (patience: 12/20)EMA Trend: 0.9470 | (patience: 12/20)
Epoch 14/150 | Loss: 0.2445 | Val Loss: 193.0055 | Val Qini: 0.8423 (patience: 13/20)EMA Trend: 0.9313 | (patience: 13/20)
Epoch 15/150 | Loss: 0.3889 | Val Loss: 192.9147 | Val Qini: 0.7792 (patience: 14/20)EMA Trend: 0.9085 | (patience: 14/20)
Epoch 16/150 | Loss: 1147.6809 | Val Loss: 192.8350 | Val Qini: 0.7256 (patience: 15/20)EMA Trend: 0.8810 | (patience: 15/20)
Epoch 17/150 | Loss: 1847.3835 | Val Loss: 192.7623 | Val Qini: 0.7092 (patience: 16/20)EMA Trend: 0.8553 | (patience: 16/20)
Epoch 18/150 | Loss: 0.9496 | Val Loss: 192.7289 | Val Qini: 0.7622 (patience: 17/20)EMA Trend: 0.8413 | (patience: 17/20)
Epoch 19/150 | Loss: 4386.3428 | Val Loss: 192.7338 | Val Qini: 0.7607 (patience: 18/20)EMA Trend: 0.8292 | (patience: 18/20)
Epoch 20/150 | Loss: 1.3886 | Val Loss: 192.7760 | Val Qini: 0.7442 (patience: 19/20)EMA Trend: 0.8165 | (patience: 19/20)
Epoch 21/150 | Loss: 1.3976 | Val Loss: 192.7998 | Val Qini: 0.7564 (patience: 20/20)EMA Trend: 0.8075 | (patience: 20/20)
Epoch 22/150 | Loss: 1.6659 | Val Loss: 192.7858 | Val Qini: 0.7466 (patience: 21/20)EMA Trend: 0.7983 | (patience: 21/20)
Epoch 23/150 | Loss: 1.3766 | Val Loss: 192.7596 | Val Qini: 0.7567 (patience: 22/20)EMA Trend: 0.7921 | (patience: 22/20)
Epoch 24/150 | Loss: 1.3550 | Val Loss: 192.7363 | Val Qini: 0.7625 (patience: 23/20)EMA Trend: 0.7877 | (patience: 23/20)
Epoch 25/150 | Loss: 628.9574 | Val Loss: 192.7224 | Val Qini: 0.7669 (patience: 24/20)EMA Trend: 0.7845 | (patience: 24/20)
Epoch 26/150 | Loss: 3.5582 | Val Loss: 192.7249 | Val Qini: 0.7463 (patience: 25/20)EMA Trend: 0.7788 | (patience: 25/20)
Epoch 27/150 | Loss: 1.7169 | Val Loss: 192.7270 | Val Qini: 0.7296 (patience: 26/20)EMA Trend: 0.7714 | (patience: 26/20)
Epoch 28/150 | Loss: 1.1308 | Val Loss: 192.7291 | Val Qini: 0.7173 (patience: 27/20)EMA Trend: 0.7633 | (patience: 27/20)
Epoch 29/150 | Loss: 1.5073 | Val Loss: 192.7332 | Val Qini: 0.7104 (patience: 28/20)EMA Trend: 0.7554 | (patience: 28/20)
Epoch 30/150 | Loss: 1.3525 | Val Loss: 192.7325 | Val Qini: 0.7288 (patience: 29/20)EMA Trend: 0.7514 | (patience: 29/20)
Epoch 31/150 | Loss: 1.4737 | Val Loss: 192.7282 | Val Qini: 0.7531 ✓ above trend but not peak (patience: 30/20)EMA Trend: 0.7516 | ✓ above trend but not peak (patience: 30/20)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 1
   Best Raw Qini: 1.1879
   Final EMA Trend: 0.7516
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 7
Locked random seed: 8
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Loss: 0.0199 | Val Loss: 193.7141 | Val Qini: -0.1747 ⭐ NEW BEST (peak ≥ trend)EMA Trend: -0.1747 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.0466 | Val Loss: 193.6765 | Val Qini: -0.0411 ⭐ NEW BEST (peak ≥ trend)EMA Trend: -0.1546 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Loss: 0.0050 | Val Loss: 193.6410 | Val Qini: 0.0925 ⭐ NEW BEST (peak ≥ trend)EMA Trend: -0.1176 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Loss: 0.0239 | Val Loss: 193.6052 | Val Qini: 0.1451 ⭐ NEW BEST (peak ≥ trend)EMA Trend: -0.0782 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/150 | Loss: 0.0198 | Val Loss: 193.5687 | Val Qini: 0.1478 ⭐ NEW BEST (peak ≥ trend)EMA Trend: -0.0443 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/150 | Loss: 0.0238 | Val Loss: 193.5307 | Val Qini: 0.0516 ✓ above trend but not peak (patience: 1/20)EMA Trend: -0.0299 | ✓ above trend but not peak (patience: 1/20)
Epoch 7/150 | Loss: 0.0134 | Val Loss: 193.4900 | Val Qini: 0.0157 ✓ above trend but not peak (patience: 2/20)EMA Trend: -0.0231 | ✓ above trend but not peak (patience: 2/20)
Epoch 8/150 | Loss: 177.7208 | Val Loss: 193.4427 | Val Qini: -0.0246 (patience: 3/20)EMA Trend: -0.0233 | (patience: 3/20)
Epoch 9/150 | Loss: 0.0493 | Val Loss: 193.3863 | Val Qini: -0.0267 (patience: 4/20)EMA Trend: -0.0238 | (patience: 4/20)
Epoch 10/150 | Loss: 0.0810 | Val Loss: 193.3274 | Val Qini: 0.0375 ✓ above trend but not peak (patience: 5/20)EMA Trend: -0.0146 | ✓ above trend but not peak (patience: 5/20)
Epoch 11/150 | Loss: 0.0909 | Val Loss: 193.2627 | Val Qini: 0.1112 ✓ above trend but not peak (patience: 6/20)EMA Trend: 0.0043 | ✓ above trend but not peak (patience: 6/20)
Epoch 12/150 | Loss: 0.1041 | Val Loss: 193.1952 | Val Qini: 0.1542 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.0268 | ⭐ NEW BEST (peak ≥ trend)
Epoch 13/150 | Loss: 0.1599 | Val Loss: 193.1236 | Val Qini: 0.2005 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.0528 | ⭐ NEW BEST (peak ≥ trend)
Epoch 14/150 | Loss: 0.2312 | Val Loss: 193.0490 | Val Qini: 0.2594 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.0838 | ⭐ NEW BEST (peak ≥ trend)
Epoch 15/150 | Loss: 0.2931 | Val Loss: 192.9715 | Val Qini: 0.3530 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1242 | ⭐ NEW BEST (peak ≥ trend)
Epoch 16/150 | Loss: 0.4196 | Val Loss: 192.8965 | Val Qini: 0.3945 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1647 | ⭐ NEW BEST (peak ≥ trend)
Epoch 17/150 | Loss: 0.4684 | Val Loss: 192.8291 | Val Qini: 0.4551 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.2083 | ⭐ NEW BEST (peak ≥ trend)
Epoch 18/150 | Loss: 0.5236 | Val Loss: 192.7720 | Val Qini: 0.5703 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.2626 | ⭐ NEW BEST (peak ≥ trend)
Epoch 19/150 | Loss: 0.8365 | Val Loss: 192.7272 | Val Qini: 0.8589 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.3520 | ⭐ NEW BEST (peak ≥ trend)
Epoch 20/150 | Loss: 0.8298 | Val Loss: 192.6972 | Val Qini: 1.1124 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.4661 | ⭐ NEW BEST (peak ≥ trend)
Epoch 21/150 | Loss: 0.9484 | Val Loss: 192.6837 | Val Qini: 1.2822 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5885 | ⭐ NEW BEST (peak ≥ trend)
Epoch 22/150 | Loss: 715.1174 | Val Loss: 192.6841 | Val Qini: 1.2692 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.6906 | ✓ above trend but not peak (patience: 1/20)
Epoch 23/150 | Loss: 1.4451 | Val Loss: 192.7044 | Val Qini: 1.1592 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.7609 | ✓ above trend but not peak (patience: 2/20)
Epoch 24/150 | Loss: 1.2006 | Val Loss: 192.7201 | Val Qini: 1.1116 ✓ above trend but not peak (patience: 3/20)EMA Trend: 0.8135 | ✓ above trend but not peak (patience: 3/20)
Epoch 25/150 | Loss: 1.7052 | Val Loss: 192.7177 | Val Qini: 1.1032 ✓ above trend but not peak (patience: 4/20)EMA Trend: 0.8570 | ✓ above trend but not peak (patience: 4/20)
Epoch 26/150 | Loss: 1.6496 | Val Loss: 192.6958 | Val Qini: 1.0821 ✓ above trend but not peak (patience: 5/20)EMA Trend: 0.8907 | ✓ above trend but not peak (patience: 5/20)
Epoch 27/150 | Loss: 1.4211 | Val Loss: 192.6769 | Val Qini: 1.1079 ✓ above trend but not peak (patience: 6/20)EMA Trend: 0.9233 | ✓ above trend but not peak (patience: 6/20)
Epoch 28/150 | Loss: 84.0891 | Val Loss: 192.6629 | Val Qini: 1.1208 ✓ above trend but not peak (patience: 7/20)EMA Trend: 0.9529 | ✓ above trend but not peak (patience: 7/20)
Epoch 29/150 | Loss: 1.6080 | Val Loss: 192.6603 | Val Qini: 1.1115 ✓ above trend but not peak (patience: 8/20)EMA Trend: 0.9767 | ✓ above trend but not peak (patience: 8/20)
Epoch 30/150 | Loss: 1.5134 | Val Loss: 192.6662 | Val Qini: 1.1011 ✓ above trend but not peak (patience: 9/20)EMA Trend: 0.9954 | ✓ above trend but not peak (patience: 9/20)
Epoch 31/150 | Loss: 1.4859 | Val Loss: 192.6735 | Val Qini: 1.1123 ✓ above trend but not peak (patience: 10/20)EMA Trend: 1.0129 | ✓ above trend but not peak (patience: 10/20)
Epoch 32/150 | Loss: 1.3965 | Val Loss: 192.6856 | Val Qini: 1.1060 ✓ above trend but not peak (patience: 11/20)EMA Trend: 1.0269 | ✓ above trend but not peak (patience: 11/20)
Epoch 33/150 | Loss: 2.2264 | Val Loss: 192.6958 | Val Qini: 1.1143 ✓ above trend but not peak (patience: 12/20)EMA Trend: 1.0400 | ✓ above trend but not peak (patience: 12/20)
Epoch 34/150 | Loss: 1.3420 | Val Loss: 192.6961 | Val Qini: 1.1115 ✓ above trend but not peak (patience: 13/20)EMA Trend: 1.0507 | ✓ above trend but not peak (patience: 13/20)
Epoch 35/150 | Loss: 1.6442 | Val Loss: 192.6912 | Val Qini: 1.1185 ✓ above trend but not peak (patience: 14/20)EMA Trend: 1.0609 | ✓ above trend but not peak (patience: 14/20)
Epoch 36/150 | Loss: 1.8593 | Val Loss: 192.6838 | Val Qini: 1.1180 ✓ above trend but not peak (patience: 15/20)EMA Trend: 1.0695 | ✓ above trend but not peak (patience: 15/20)
Epoch 37/150 | Loss: 1.3686 | Val Loss: 192.6803 | Val Qini: 1.1243 ✓ above trend but not peak (patience: 16/20)EMA Trend: 1.0777 | ✓ above trend but not peak (patience: 16/20)
Epoch 38/150 | Loss: 1.3998 | Val Loss: 192.6774 | Val Qini: 1.1407 ✓ above trend but not peak (patience: 17/20)EMA Trend: 1.0871 | ✓ above trend but not peak (patience: 17/20)
Epoch 39/150 | Loss: 1.1726 | Val Loss: 192.6825 | Val Qini: 1.1282 ✓ above trend but not peak (patience: 18/20)EMA Trend: 1.0933 | ✓ above trend but not peak (patience: 18/20)
Epoch 40/150 | Loss: 6317.1890 | Val Loss: 192.6848 | Val Qini: 1.1196 ✓ above trend but not peak (patience: 19/20)EMA Trend: 1.0973 | ✓ above trend but not peak (patience: 19/20)
Epoch 41/150 | Loss: 1.9622 | Val Loss: 192.6945 | Val Qini: 1.1049 ✓ above trend but not peak (patience: 20/20)EMA Trend: 1.0984 | ✓ above trend but not peak (patience: 20/20)

🛑 Early stopping triggered at epoch 41!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 21
   Best Raw Qini: 1.2822
   Final EMA Trend: 1.0984
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 8
Locked random seed: 9
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Loss: -0.0114 | Val Loss: 193.6684 | Val Qini: 1.4031 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.4031 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: -0.0005 | Val Loss: 193.6250 | Val Qini: 1.4032 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.4031 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Loss: -0.0026 | Val Loss: 193.5821 | Val Qini: 1.3495 (patience: 1/20)EMA Trend: 1.3951 | (patience: 1/20)
Epoch 4/150 | Loss: 0.0043 | Val Loss: 193.5371 | Val Qini: 1.3377 (patience: 2/20)EMA Trend: 1.3865 | (patience: 2/20)
Epoch 5/150 | Loss: 0.0062 | Val Loss: 193.4891 | Val Qini: 1.3389 (patience: 3/20)EMA Trend: 1.3793 | (patience: 3/20)
Epoch 6/150 | Loss: 0.0465 | Val Loss: 193.4373 | Val Qini: 1.3048 (patience: 4/20)EMA Trend: 1.3682 | (patience: 4/20)
Epoch 7/150 | Loss: 0.0433 | Val Loss: 193.3817 | Val Qini: 1.3056 (patience: 5/20)EMA Trend: 1.3588 | (patience: 5/20)
Epoch 8/150 | Loss: 0.0761 | Val Loss: 193.3241 | Val Qini: 1.3277 (patience: 6/20)EMA Trend: 1.3541 | (patience: 6/20)
Epoch 9/150 | Loss: 0.1170 | Val Loss: 193.2642 | Val Qini: 1.3241 (patience: 7/20)EMA Trend: 1.3496 | (patience: 7/20)
Epoch 10/150 | Loss: 0.0950 | Val Loss: 193.2005 | Val Qini: 1.3154 (patience: 8/20)EMA Trend: 1.3445 | (patience: 8/20)
Epoch 11/150 | Loss: 0.1497 | Val Loss: 193.1341 | Val Qini: 1.2729 (patience: 9/20)EMA Trend: 1.3337 | (patience: 9/20)
Epoch 12/150 | Loss: 0.1938 | Val Loss: 193.0657 | Val Qini: 1.2485 (patience: 10/20)EMA Trend: 1.3210 | (patience: 10/20)
Epoch 13/150 | Loss: 0.1867 | Val Loss: 192.9966 | Val Qini: 1.2262 (patience: 11/20)EMA Trend: 1.3067 | (patience: 11/20)
Epoch 14/150 | Loss: 0.2863 | Val Loss: 192.9264 | Val Qini: 1.2094 (patience: 12/20)EMA Trend: 1.2921 | (patience: 12/20)
Epoch 15/150 | Loss: 0.3657 | Val Loss: 192.8579 | Val Qini: 1.2071 (patience: 13/20)EMA Trend: 1.2794 | (patience: 13/20)
Epoch 16/150 | Loss: 0.4351 | Val Loss: 192.7959 | Val Qini: 1.1847 (patience: 14/20)EMA Trend: 1.2652 | (patience: 14/20)
Epoch 17/150 | Loss: 0.6863 | Val Loss: 192.7411 | Val Qini: 1.1709 (patience: 15/20)EMA Trend: 1.2511 | (patience: 15/20)
Epoch 18/150 | Loss: 0.7431 | Val Loss: 192.7045 | Val Qini: 1.1520 (patience: 16/20)EMA Trend: 1.2362 | (patience: 16/20)
Epoch 19/150 | Loss: 202.3362 | Val Loss: 192.6839 | Val Qini: 1.1488 (patience: 17/20)EMA Trend: 1.2231 | (patience: 17/20)
Epoch 20/150 | Loss: 1.3381 | Val Loss: 192.6834 | Val Qini: 1.1324 (patience: 18/20)EMA Trend: 1.2095 | (patience: 18/20)
Epoch 21/150 | Loss: 98.7639 | Val Loss: 192.6973 | Val Qini: 1.1140 (patience: 19/20)EMA Trend: 1.1952 | (patience: 19/20)
Epoch 22/150 | Loss: 1.7910 | Val Loss: 192.7224 | Val Qini: 1.0980 (patience: 20/20)EMA Trend: 1.1806 | (patience: 20/20)
Epoch 23/150 | Loss: 1085.1178 | Val Loss: 192.7395 | Val Qini: 1.0749 (patience: 21/20)EMA Trend: 1.1647 | (patience: 21/20)
Epoch 24/150 | Loss: 1.6573 | Val Loss: 192.7526 | Val Qini: 1.0434 (patience: 22/20)EMA Trend: 1.1465 | (patience: 22/20)
Epoch 25/150 | Loss: 1.9844 | Val Loss: 192.7412 | Val Qini: 1.0251 (patience: 23/20)EMA Trend: 1.1283 | (patience: 23/20)
Epoch 26/150 | Loss: 1.3993 | Val Loss: 192.7256 | Val Qini: 1.0004 (patience: 24/20)EMA Trend: 1.1091 | (patience: 24/20)
Epoch 27/150 | Loss: 1.7188 | Val Loss: 192.7095 | Val Qini: 0.9799 (patience: 25/20)EMA Trend: 1.0897 | (patience: 25/20)
Epoch 28/150 | Loss: 1.4500 | Val Loss: 192.7040 | Val Qini: 0.9685 (patience: 26/20)EMA Trend: 1.0716 | (patience: 26/20)
Epoch 29/150 | Loss: 1.7226 | Val Loss: 192.6975 | Val Qini: 0.9726 (patience: 27/20)EMA Trend: 1.0567 | (patience: 27/20)
Epoch 30/150 | Loss: 1.1068 | Val Loss: 192.6947 | Val Qini: 0.9779 (patience: 28/20)EMA Trend: 1.0449 | (patience: 28/20)
Epoch 31/150 | Loss: 1.4650 | Val Loss: 192.6996 | Val Qini: 0.9848 (patience: 29/20)EMA Trend: 1.0359 | (patience: 29/20)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 2
   Best Raw Qini: 1.4032
   Final EMA Trend: 1.0359
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 9
Locked random seed: 10
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Loss: 0.0048 | Val Loss: 193.9865 | Val Qini: 1.2316 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.2316 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: -0.0002 | Val Loss: 193.9410 | Val Qini: 1.2679 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.2371 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Loss: 0.0081 | Val Loss: 193.8935 | Val Qini: 1.3181 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.2492 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Loss: 0.0104 | Val Loss: 193.8441 | Val Qini: 1.3206 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.2599 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/150 | Loss: 0.0202 | Val Loss: 193.7926 | Val Qini: 1.3740 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.2770 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/150 | Loss: 0.0300 | Val Loss: 193.7371 | Val Qini: 1.4490 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.3028 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/150 | Loss: 0.0155 | Val Loss: 193.6776 | Val Qini: 1.4864 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.3304 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/150 | Loss: 0.0072 | Val Loss: 193.6106 | Val Qini: 1.5067 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 1.3568 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/150 | Loss: 0.0312 | Val Loss: 193.5335 | Val Qini: 1.4940 ✓ above trend but not peak (patience: 1/20)EMA Trend: 1.3774 | ✓ above trend but not peak (patience: 1/20)
Epoch 10/150 | Loss: 0.0089 | Val Loss: 193.4472 | Val Qini: 1.5025 ✓ above trend but not peak (patience: 2/20)EMA Trend: 1.3962 | ✓ above trend but not peak (patience: 2/20)
Epoch 11/150 | Loss: 0.0635 | Val Loss: 193.3562 | Val Qini: 1.4933 ✓ above trend but not peak (patience: 3/20)EMA Trend: 1.4107 | ✓ above trend but not peak (patience: 3/20)
Epoch 12/150 | Loss: 157.7420 | Val Loss: 193.2585 | Val Qini: 1.4796 ✓ above trend but not peak (patience: 4/20)EMA Trend: 1.4211 | ✓ above trend but not peak (patience: 4/20)
Epoch 13/150 | Loss: 0.0886 | Val Loss: 193.1460 | Val Qini: 1.4766 ✓ above trend but not peak (patience: 5/20)EMA Trend: 1.4294 | ✓ above trend but not peak (patience: 5/20)
Epoch 14/150 | Loss: 0.1448 | Val Loss: 193.0405 | Val Qini: 1.4708 ✓ above trend but not peak (patience: 6/20)EMA Trend: 1.4356 | ✓ above trend but not peak (patience: 6/20)
Epoch 15/150 | Loss: 0.1857 | Val Loss: 192.9380 | Val Qini: 1.4611 ✓ above trend but not peak (patience: 7/20)EMA Trend: 1.4394 | ✓ above trend but not peak (patience: 7/20)
Epoch 16/150 | Loss: 0.2834 | Val Loss: 192.8399 | Val Qini: 1.4620 ✓ above trend but not peak (patience: 8/20)EMA Trend: 1.4428 | ✓ above trend but not peak (patience: 8/20)
Epoch 17/150 | Loss: 0.4284 | Val Loss: 192.7514 | Val Qini: 1.4533 ✓ above trend but not peak (patience: 9/20)EMA Trend: 1.4444 | ✓ above trend but not peak (patience: 9/20)
Epoch 18/150 | Loss: 0.5881 | Val Loss: 192.6746 | Val Qini: 1.4491 ✓ above trend but not peak (patience: 10/20)EMA Trend: 1.4451 | ✓ above trend but not peak (patience: 10/20)
Epoch 19/150 | Loss: 0.7002 | Val Loss: 192.6200 | Val Qini: 1.4376 (patience: 11/20)EMA Trend: 1.4440 | (patience: 11/20)
Epoch 20/150 | Loss: 6079.0308 | Val Loss: 192.5869 | Val Qini: 1.4341 (patience: 12/20)EMA Trend: 1.4425 | (patience: 12/20)
Epoch 21/150 | Loss: 0.9639 | Val Loss: 192.5727 | Val Qini: 1.4053 (patience: 13/20)EMA Trend: 1.4369 | (patience: 13/20)
Epoch 22/150 | Loss: 1.3676 | Val Loss: 192.5821 | Val Qini: 1.3938 (patience: 14/20)EMA Trend: 1.4304 | (patience: 14/20)
Epoch 23/150 | Loss: 1.4572 | Val Loss: 192.5987 | Val Qini: 1.3709 (patience: 15/20)EMA Trend: 1.4215 | (patience: 15/20)
Epoch 24/150 | Loss: 1.3817 | Val Loss: 192.6170 | Val Qini: 1.3592 (patience: 16/20)EMA Trend: 1.4122 | (patience: 16/20)
Epoch 25/150 | Loss: 1.3506 | Val Loss: 192.6238 | Val Qini: 1.3410 (patience: 17/20)EMA Trend: 1.4015 | (patience: 17/20)
Epoch 26/150 | Loss: 1.3577 | Val Loss: 192.6220 | Val Qini: 1.3279 (patience: 18/20)EMA Trend: 1.3905 | (patience: 18/20)
Epoch 27/150 | Loss: 1.5258 | Val Loss: 192.6133 | Val Qini: 1.3080 (patience: 19/20)EMA Trend: 1.3781 | (patience: 19/20)
Epoch 28/150 | Loss: 1.6606 | Val Loss: 192.6078 | Val Qini: 1.2662 (patience: 20/20)EMA Trend: 1.3613 | (patience: 20/20)
Epoch 29/150 | Loss: 1.2404 | Val Loss: 192.6049 | Val Qini: 1.2414 (patience: 21/20)EMA Trend: 1.3433 | (patience: 21/20)
Epoch 30/150 | Loss: 1.0845 | Val Loss: 192.6115 | Val Qini: 1.2121 (patience: 22/20)EMA Trend: 1.3236 | (patience: 22/20)
Epoch 31/150 | Loss: 124.1158 | Val Loss: 192.6219 | Val Qini: 1.1925 (patience: 23/20)EMA Trend: 1.3040 | (patience: 23/20)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 8
   Best Raw Qini: 1.5067
   Final EMA Trend: 1.3040
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 10
Locked random seed: 11
🔃🔃🔃Begin training Dragonnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)

Epoch 1/150 | Loss: 0.0181 | Val Loss: 193.7505 | Val Qini: 0.4608 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.4608 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/150 | Loss: 0.0002 | Val Loss: 193.7276 | Val Qini: 0.6230 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.4852 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/150 | Loss: 0.0237 | Val Loss: 193.7040 | Val Qini: 0.8190 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5352 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/150 | Loss: -0.0155 | Val Loss: 193.6801 | Val Qini: 0.8857 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5878 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/150 | Loss: 0.0074 | Val Loss: 193.6542 | Val Qini: 0.9349 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6399 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/150 | Loss: 0.0014 | Val Loss: 193.6255 | Val Qini: 0.9452 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6857 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/150 | Loss: 0.0002 | Val Loss: 193.5930 | Val Qini: 0.9237 ✓ above trend but not peak (patience: 1/20)EMA Trend: 0.7214 | ✓ above trend but not peak (patience: 1/20)
Epoch 8/150 | Loss: 0.0053 | Val Loss: 193.5546 | Val Qini: 0.9208 ✓ above trend but not peak (patience: 2/20)EMA Trend: 0.7513 | ✓ above trend but not peak (patience: 2/20)
Epoch 9/150 | Loss: 0.0124 | Val Loss: 193.5097 | Val Qini: 0.9234 ✓ above trend but not peak (patience: 3/20)EMA Trend: 0.7771 | ✓ above trend but not peak (patience: 3/20)
Epoch 10/150 | Loss: 0.0262 | Val Loss: 193.4577 | Val Qini: 0.9039 ✓ above trend but not peak (patience: 4/20)EMA Trend: 0.7961 | ✓ above trend but not peak (patience: 4/20)
Epoch 11/150 | Loss: 0.0546 | Val Loss: 193.3992 | Val Qini: 0.8968 ✓ above trend but not peak (patience: 5/20)EMA Trend: 0.8112 | ✓ above trend but not peak (patience: 5/20)
Epoch 12/150 | Loss: 0.0588 | Val Loss: 193.3335 | Val Qini: 0.8808 ✓ above trend but not peak (patience: 6/20)EMA Trend: 0.8217 | ✓ above trend but not peak (patience: 6/20)
Epoch 13/150 | Loss: 0.1154 | Val Loss: 193.2615 | Val Qini: 0.8505 ✓ above trend but not peak (patience: 7/20)EMA Trend: 0.8260 | ✓ above trend but not peak (patience: 7/20)
Epoch 14/150 | Loss: 0.1329 | Val Loss: 193.1876 | Val Qini: 0.8292 ✓ above trend but not peak (patience: 8/20)EMA Trend: 0.8265 | ✓ above trend but not peak (patience: 8/20)
Epoch 15/150 | Loss: 0.1477 | Val Loss: 193.1104 | Val Qini: 0.8317 ✓ above trend but not peak (patience: 9/20)EMA Trend: 0.8272 | ✓ above trend but not peak (patience: 9/20)
Epoch 16/150 | Loss: 0.1913 | Val Loss: 193.0300 | Val Qini: 0.8407 ✓ above trend but not peak (patience: 10/20)EMA Trend: 0.8293 | ✓ above trend but not peak (patience: 10/20)
Epoch 17/150 | Loss: 0.2450 | Val Loss: 192.9482 | Val Qini: 0.8275 (patience: 11/20)EMA Trend: 0.8290 | (patience: 11/20)
Epoch 18/150 | Loss: 0.4131 | Val Loss: 192.8695 | Val Qini: 0.8245 (patience: 12/20)EMA Trend: 0.8283 | (patience: 12/20)
Epoch 19/150 | Loss: 0.4774 | Val Loss: 192.7971 | Val Qini: 0.8120 (patience: 13/20)EMA Trend: 0.8259 | (patience: 13/20)
Epoch 20/150 | Loss: 0.6450 | Val Loss: 192.7356 | Val Qini: 0.8004 (patience: 14/20)EMA Trend: 0.8220 | (patience: 14/20)
Epoch 21/150 | Loss: 0.7411 | Val Loss: 192.7004 | Val Qini: 0.7977 (patience: 15/20)EMA Trend: 0.8184 | (patience: 15/20)
Epoch 22/150 | Loss: 1.0168 | Val Loss: 192.6835 | Val Qini: 0.7866 (patience: 16/20)EMA Trend: 0.8136 | (patience: 16/20)
Epoch 23/150 | Loss: 0.9890 | Val Loss: 192.6846 | Val Qini: 0.7788 (patience: 17/20)EMA Trend: 0.8084 | (patience: 17/20)
Epoch 24/150 | Loss: 1.4380 | Val Loss: 192.6941 | Val Qini: 0.7720 (patience: 18/20)EMA Trend: 0.8029 | (patience: 18/20)
Epoch 25/150 | Loss: 1.4883 | Val Loss: 192.7135 | Val Qini: 0.7640 (patience: 19/20)EMA Trend: 0.7971 | (patience: 19/20)
Epoch 26/150 | Loss: 1.3952 | Val Loss: 192.7242 | Val Qini: 0.7501 (patience: 20/20)EMA Trend: 0.7901 | (patience: 20/20)
Epoch 27/150 | Loss: 1.6955 | Val Loss: 192.7329 | Val Qini: 0.7312 (patience: 21/20)EMA Trend: 0.7812 | (patience: 21/20)
Epoch 28/150 | Loss: 145.5967 | Val Loss: 192.7453 | Val Qini: 0.7342 (patience: 22/20)EMA Trend: 0.7742 | (patience: 22/20)
Epoch 29/150 | Loss: 1.6655 | Val Loss: 192.7578 | Val Qini: 0.7255 (patience: 23/20)EMA Trend: 0.7669 | (patience: 23/20)
Epoch 30/150 | Loss: 1.7869 | Val Loss: 192.7552 | Val Qini: 0.7124 (patience: 24/20)EMA Trend: 0.7587 | (patience: 24/20)
Epoch 31/150 | Loss: 1546.4323 | Val Loss: 192.7578 | Val Qini: 0.6977 (patience: 25/20)EMA Trend: 0.7496 | (patience: 25/20)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 20 epochs

✅ Training completed! Restored model to epoch 6
   Best Raw Qini: 0.9452
   Final EMA Trend: 0.7496
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 11

=====================================================================================
                                 CHI TIẾT TỪNG SEED
=====================================================================================
 Seed   AUUC   AUQC   Lift    KRCC ATE_Err
    7 0.5760 0.5752 0.8274  0.1091  0.5142
    8 0.6137 0.6099 0.8279  0.0481  0.3353
    9 0.4489 0.4473 1.0151 -0.0609  0.4480
   10 0.7841 0.7786 1.2409  0.0922  0.6497
   11 0.5697 0.5648 0.4449 -0.0082  0.4290
=====================================================================================
                           KẾT QUẢ TRUNG BÌNH (MEAN ± STD)
-------------------------------------------------------------------------------------
AUUC      : 0.5985 ± 0.1208
AUQC      : 0.5952 ± 0.1194
Lift      : 0.8712 ± 0.2928
KRCC      : 0.0361 ± 0.0707
ATE_Err   : 0.4752 ± 0.1166
=====================================================================================

/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/Revenue/CFRnet/cfrnet.py:276: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x = torch.tensor(x, dtype=torch.float32, device=self.device)