Import libraries

In [19]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from tarnet import Tarnet
import sys
from pathlib import Path
project_root = Path("/home/ducm/Benchmark-conversion-vs-revenue-uplift-modeling/Revenue/Tarnet/main_tarnet.ipynb")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [20]:
%time train_df = pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Women/train_women.csv")
%time test_df =  pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Women/test_women.csv")
%time val_df = pd.read_csv(r"/home/ducvu0904/Documents/Lab/Conversion vs revenue benchmarking/dataset/Hillstrom/Women/val_women.csv")

CPU times: user 25.5 ms, sys: 6.02 ms, total: 31.5 ms
Wall time: 31 ms
CPU times: user 13 ms, sys: 4.01 ms, total: 17 ms
Wall time: 16.8 ms
CPU times: user 5.6 ms, sys: 0 ns, total: 5.6 ms
Wall time: 5.59 ms

In [21]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['conversion']
treatment_feature = ['treatment']

In [22]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [23]:
print('X_train[:10]', X_train[:1].astype(float))

X_train[:10] [[-0.78953321  1.6460815   1.41745802 -1.11692492  0.91314538  1.07643872
   0.9950542  -0.36894675 -0.88924565  1.13133938]]

In [24]:
print('y_train[:10]', y_train[:10].astype(float))

y_train[:10] [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

In [25]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25615, 10]); y=torch.Size([25615, 1]); t=torch.Size([25615, 1])
Shape of val: x=torch.Size([4270, 10]); y=torch.Size([4270, 1]); t=torch.Size([4270, 1])
Shape of test: x=torch.Size([12808, 10]); y=torch.Size([12808, 1]); t=torch.Size([12808, 1])

In [26]:
epochs = 70
lr = 5e-4
wd = 1e-5
early_stop_metric = "qini"
ema = True
ema_alpha = 0.15
patience = 15
shared_dropout = 0
outcome_dropout = 0
shared_hidden = 200
outcome_hidden = 100
early_stop_start = 30
activation = torch.nn.ReLU
print (f" epochs = {epochs}")
print (f" learning rate = {lr}")
print (f" weight decay = {wd}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" shared hidden = {shared_hidden}")
print (f" outcome hidden = {outcome_hidden}")
print (f" early stop start = {early_stop_start}")
print (f" activation = {activation}")

 epochs = 70
 learning rate = 0.0005
 weight decay = 1e-05
 early stop = qini
 use ema = True
 ema alpha = 0.15
 patience = 15
 shared hidden = 200
 outcome hidden = 100
 early stop start = 30
 activation = <class 'torch.nn.modules.activation.ReLU'>

In [27]:
import pandas as pd
import numpy as np
import torch
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 5e-5, 5e-4, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-4, log=True)
    val_scores = []
    for SEED in seeds:
        seed_everything(SEED)

        tarnet = Tarnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=shared_hidden,
            outcome_hidden=outcome_hidden,
            outcome_droupout=outcome_dropout,
            shared_dropout=shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
            activation=activation
        )

        # Silence CFRNet epoch logs
        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            tarnet.fit(train_loader, val_loader)

        x_val_device = x_men_val_t.to(device)
        y0_val_p, y1_val_p= tarnet.predict(x_val_device)
        uplift_val = (y1_val_p - y0_val_p).detach().cpu().numpy().flatten()
        y_val_true_np = y_men_val_t.detach().cpu().numpy().flatten()
        t_val_true_np = t_men_val_t.detach().cpu().numpy().flatten()

        current_val_auqc = auqc(y_val_true_np, t_val_true_np, uplift_val, bins=100, plot=False)
        val_scores.append(current_val_auqc)

    mean_val_auqc = float(np.mean(val_scores))
    std_val_auqc = float(np.std(val_scores, ddof=1)) if len(val_scores) > 1 else 0.0
    trial.set_user_attr("std_Val_AUQC", std_val_auqc)
    return mean_val_auqc

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True)

# 2. Persist search results in notebook variables
trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": t.params["lr"],
        "weight_decay": t.params["weight_decay"],
        "mean_Val_AUQC": float(t.value),
        "std_Val_AUQC": float(t.user_attrs.get("std_Val_AUQC", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_Val_AUQC", ascending=False).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "mean_Val_AUQC": float(study.best_value),
    "std_Val_AUQC": float(study.best_trial.user_attrs.get("std_Val_AUQC", np.nan))
})

  0%|          | 0/50 [00:00<?, ?it/s]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 0. Best value: 0.827207:   2%|▏         | 1/50 [00:50<41:19, 50.61s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 0. Best value: 0.827207:   4%|▍         | 2/50 [01:43<41:43, 52.15s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 0. Best value: 0.827207:   6%|▌         | 3/50 [02:36<41:04, 52.43s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 0. Best value: 0.827207:   8%|▊         | 4/50 [03:34<41:47, 54.52s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 0. Best value: 0.827207:  10%|█         | 5/50 [04:27<40:30, 54.01s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 0. Best value: 0.827207:  12%|█▏        | 6/50 [05:32<42:27, 57.90s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 0. Best value: 0.827207:  14%|█▍        | 7/50 [06:26<40:33, 56.60s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 7. Best value: 0.832265:  16%|█▌        | 8/50 [07:24<39:52, 56.97s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 7. Best value: 0.832265:  18%|█▊        | 9/50 [08:16<37:55, 55.51s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 7. Best value: 0.832265:  20%|██        | 10/50 [09:08<36:17, 54.43s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 10. Best value: 0.844751:  22%|██▏       | 11/50 [10:14<37:33, 57.78s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 11. Best value: 0.846159:  24%|██▍       | 12/50 [11:20<38:14, 60.39s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 12. Best value: 0.84693:  26%|██▌       | 13/50 [12:27<38:23, 62.26s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 12. Best value: 0.84693:  28%|██▊       | 14/50 [13:32<37:52, 63.13s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 12. Best value: 0.84693:  30%|███       | 15/50 [14:30<36:02, 61.78s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 12. Best value: 0.84693:  32%|███▏      | 16/50 [15:30<34:37, 61.10s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 12. Best value: 0.84693:  34%|███▍      | 17/50 [16:26<32:50, 59.71s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 17. Best value: 0.847138:  36%|███▌      | 18/50 [17:33<32:58, 61.83s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 17. Best value: 0.847138:  38%|███▊      | 19/50 [18:34<31:45, 61.47s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 17. Best value: 0.847138:  40%|████      | 20/50 [19:30<29:54, 59.82s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 17. Best value: 0.847138:  42%|████▏     | 21/50 [20:31<29:10, 60.37s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 17. Best value: 0.847138:  44%|████▍     | 22/50 [21:38<29:00, 62.16s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 17. Best value: 0.847138:  46%|████▌     | 23/50 [22:40<27:57, 62.11s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 17. Best value: 0.847138:  48%|████▊     | 24/50 [23:42<26:56, 62.17s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 17. Best value: 0.847138:  50%|█████     | 25/50 [24:38<25:10, 60.43s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  52%|█████▏    | 26/50 [25:41<24:28, 61.19s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  54%|█████▍    | 27/50 [26:45<23:40, 61.77s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  56%|█████▌    | 28/50 [27:41<22:05, 60.23s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  58%|█████▊    | 29/50 [28:40<20:53, 59.70s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  60%|██████    | 30/50 [29:42<20:12, 60.60s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  62%|██████▏   | 31/50 [30:35<18:28, 58.35s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  64%|██████▍   | 32/50 [31:43<18:17, 61.00s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  66%|██████▌   | 33/50 [32:49<17:45, 62.70s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  68%|██████▊   | 34/50 [33:52<16:41, 62.61s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  70%|███████   | 35/50 [34:55<15:43, 62.92s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  72%|███████▏  | 36/50 [35:50<14:04, 60.30s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  74%|███████▍  | 37/50 [36:38<12:18, 56.84s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  76%|███████▌  | 38/50 [37:32<11:12, 56.03s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  78%|███████▊  | 39/50 [38:24<10:01, 54.69s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  80%|████████  | 40/50 [39:26<09:27, 56.78s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  82%|████████▏ | 41/50 [40:24<08:35, 57.27s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  84%|████████▍ | 42/50 [41:26<07:49, 58.66s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  86%|████████▌ | 43/50 [42:24<06:49, 58.44s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  88%|████████▊ | 44/50 [43:24<05:53, 58.89s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  90%|█████████ | 45/50 [44:20<04:51, 58.21s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  92%|█████████▏| 46/50 [45:26<04:02, 60.50s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  94%|█████████▍| 47/50 [46:27<03:01, 60.64s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  96%|█████████▌| 48/50 [47:19<01:55, 57.98s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229:  98%|█████████▊| 49/50 [48:18<00:58, 58.26s/it]

Locked random seed: 412312
Locked random seed: 42
Locked random seed: 1874
Locked random seed: 902745
Locked random seed: 1

Best trial: 25. Best value: 0.850229: 100%|██████████| 50/50 [49:18<00:00, 59.18s/it]

In [28]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_AUQC: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 25
Best mean_Val_AUQC: 0.850229
Best params: {'lr': 5.930822934353007e-05, 'weight_decay': 1.9233416715164336e-05}

Best config table:

         lr  weight_decay  mean_Val_AUQC  std_Val_AUQC
0  0.000059      0.000019       0.850229      0.190445

Top 10 trials:

   trial        lr  weight_decay  mean_Val_AUQC  std_Val_AUQC
0     25  0.000059      0.000019       0.850229      0.190445
1     32  0.000056      0.000015       0.847856      0.186881
2     17  0.000051      0.000018       0.847138      0.185443
3     12  0.000051      0.000010       0.846930      0.186489
4     34  0.000058      0.000018       0.846845      0.190591
5     49  0.000055      0.000022       0.846814      0.184777
6     31  0.000050      0.000012       0.846501      0.186515
7     11  0.000051      0.000012       0.846159      0.185160
8     29  0.000061      0.000026       0.846092      0.188798
9     41  0.000057      0.000020       0.845528      0.188826

In [31]:
import pandas as pd
import numpy as np
import torch

# 1. Cấu hình
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

print(f"🔄 Đang huấn luyện TARNet trên {len(seeds)} seeds khác nhau... Vui lòng đợi.")

# 2. Vòng lặp chạy
for SEED in seeds:
    seed_everything(SEED)
    
    # Khởi tạo lại mô hình
    tarnet = Tarnet(
        input_dim=x_men_train_t.shape[1], epochs=epochs, learning_rate=0.000059, 
        weight_decay=0.000019, use_ema=ema, ema_alpha=ema_alpha, patience=patience,
        shared_hidden=shared_hidden, outcome_hidden=outcome_hidden,
        outcome_droupout=outcome_dropout, shared_dropout=shared_dropout,
        early_stop_metric=early_stop_metric, early_stop_start_epoch=early_stop_start,
        activation=activation
    )
    
    tarnet.fit(train_loader, val_loader)
    
    # --- Predict on VALIDATION set ---
    # Giả sử bạn có x_men_val_t, y_men_val_t, t_men_val_t từ val_loader hoặc tương đương
    x_val_device = x_men_val_t.to(device)
    y0_val_p, y1_val_p = tarnet.predict(x_val_device)
    uplift_val = (y1_val_p - y0_val_p).cpu().numpy().flatten()
    y_val_true_np = y_men_val_t.cpu().numpy().flatten()
    t_val_true_np = t_men_val_t.cpu().numpy().flatten()
    
    current_val_auqc = auqc(y_val_true_np, t_val_true_np, uplift_val, bins=100, plot=False)

    # --- Predict on TEST set ---
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = tarnet.predict(x_men_test_t_on_device)
    
    uplift_pred = (y1_pred - y0_pred).cpu().numpy().flatten()
    y_true = y_men_test_t.cpu().numpy().flatten()
    t_true = t_men_test_t.cpu().numpy().flatten()
    
    # Tính toán ATE
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()
    
    all_runs.append({
        'Seed': SEED,
        'Val_AUQC': current_val_auqc, # Thêm Val AUQC vào đây
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  ✔️ Đã xong Seed {SEED} | Val AUQC: {current_val_auqc:.4f}")

# 3. HIỂN THỊ KẾT QUẢ TỔNG HỢP (Print 1 lúc)
df_results = pd.DataFrame(all_runs)

# Đưa cột Val_AUQC lên đầu cho dễ nhìn
cols = ['Seed', 'Val_AUQC', 'AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']
df_results = df_results[cols]

print("\n" + "="*95)
print(f"{'CHI TIẾT TỪNG SEED (VALIDATION & TEST)':^95}")
print("="*95)
print(df_results.to_string(index=False, formatters={
    'Val_AUQC': '{:,.4f}'.format, 'AUUC': '{:,.4f}'.format, 
    'AUQC': '{:,.4f}'.format, 'Lift': '{:,.4f}'.format, 
    'KRCC': '{:,.4f}'.format, 'ATE_Err': '{:,.4f}'.format
}))

# 4. Tính toán Mean và Std
mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("="*95)
print(f"{'KẾT QUẢ TRUNG BÌNH (MEAN ± STD)':^95}")
print("-" * 95)
for metric in ['Val_AUQC', 'AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")

print("="*95)

🔄 Đang huấn luyện TARNet trên 5 seeds khác nhau... Vui lòng đợi.
Locked random seed: 412312
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/70 | Loss: 1.3988 | Val Loss: 1.3974 | Val Qini: 0.2793 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.2793 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/70 | Loss: 1.3951 | Val Loss: 1.3877 | Val Qini: 0.2429 (patience: 1/15)EMA Trend: 0.2739 | (patience: 1/15)
Epoch 3/70 | Loss: 1.3802 | Val Loss: 1.3785 | Val Qini: 0.2407 (patience: 2/15)EMA Trend: 0.2689 | (patience: 2/15)
Epoch 4/70 | Loss: 1.3700 | Val Loss: 1.3697 | Val Qini: 0.2102 (patience: 3/15)EMA Trend: 0.2601 | (patience: 3/15)
Epoch 5/70 | Loss: 1.3607 | Val Loss: 1.3611 | Val Qini: 0.1884 (patience: 4/15)EMA Trend: 0.2493 | (patience: 4/15)
Epoch 6/70 | Loss: 1.3537 | Val Loss: 1.3524 | Val Qini: 0.2729 ✓ above trend but not peak (patience: 5/15)EMA Trend: 0.2529 | ✓ above trend but not peak (patience: 5/15)
Epoch 7/70 | Loss: 1.3447 | Val Loss: 1.3432 | Val Qini: 0.3541 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.2681 | ⭐ NEW BEST (peak ≥ trend)
Epoch 8/70 | Loss: 1.3352 | Val Loss: 1.3330 | Val Qini: 0.4464 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.2948 | ⭐ NEW BEST (peak ≥ trend)
Epoch 9/70 | Loss: 1.3247 | Val Loss: 1.3215 | Val Qini: 0.4871 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.3237 | ⭐ NEW BEST (peak ≥ trend)
Epoch 10/70 | Loss: 1.3096 | Val Loss: 1.3084 | Val Qini: 0.5203 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.3531 | ⭐ NEW BEST (peak ≥ trend)
Epoch 11/70 | Loss: 1.2985 | Val Loss: 1.2935 | Val Qini: 0.5327 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.3801 | ⭐ NEW BEST (peak ≥ trend)
Epoch 12/70 | Loss: 1.2848 | Val Loss: 1.2766 | Val Qini: 0.4083 ✓ above trend but not peak (patience: 1/15)EMA Trend: 0.3843 | ✓ above trend but not peak (patience: 1/15)
Epoch 13/70 | Loss: 1.2574 | Val Loss: 1.2567 | Val Qini: 0.3956 ✓ above trend but not peak (patience: 2/15)EMA Trend: 0.3860 | ✓ above trend but not peak (patience: 2/15)
Epoch 14/70 | Loss: 1.2323 | Val Loss: 1.2325 | Val Qini: 0.4748 ✓ above trend but not peak (patience: 3/15)EMA Trend: 0.3993 | ✓ above trend but not peak (patience: 3/15)
Epoch 15/70 | Loss: 1.1990 | Val Loss: 1.2022 | Val Qini: 0.4779 ✓ above trend but not peak (patience: 4/15)EMA Trend: 0.4111 | ✓ above trend but not peak (patience: 4/15)
Epoch 16/70 | Loss: 1.1571 | Val Loss: 1.1642 | Val Qini: 0.3875 (patience: 5/15)EMA Trend: 0.4076 | (patience: 5/15)
Epoch 17/70 | Loss: 1.1383 | Val Loss: 1.1173 | Val Qini: 0.3948 (patience: 6/15)EMA Trend: 0.4056 | (patience: 6/15)
Epoch 18/70 | Loss: 1.0817 | Val Loss: 1.0619 | Val Qini: 0.3766 (patience: 7/15)EMA Trend: 0.4013 | (patience: 7/15)
Epoch 19/70 | Loss: 1.0318 | Val Loss: 0.9980 | Val Qini: 0.3386 (patience: 8/15)EMA Trend: 0.3919 | (patience: 8/15)
Epoch 20/70 | Loss: 0.9616 | Val Loss: 0.9256 | Val Qini: 0.3245 (patience: 9/15)EMA Trend: 0.3818 | (patience: 9/15)
Epoch 21/70 | Loss: 0.8527 | Val Loss: 0.8457 | Val Qini: 0.3358 (patience: 10/15)EMA Trend: 0.3749 | (patience: 10/15)
Epoch 22/70 | Loss: 0.7604 | Val Loss: 0.7600 | Val Qini: 0.3710 (patience: 11/15)EMA Trend: 0.3743 | (patience: 11/15)
Epoch 23/70 | Loss: 0.6618 | Val Loss: 0.6706 | Val Qini: 0.5014 ✓ above trend but not peak (patience: 12/15)EMA Trend: 0.3934 | ✓ above trend but not peak (patience: 12/15)
Epoch 24/70 | Loss: 0.6013 | Val Loss: 0.5802 | Val Qini: 0.6153 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.4266 | ⭐ NEW BEST (peak ≥ trend)
Epoch 25/70 | Loss: 0.5203 | Val Loss: 0.4918 | Val Qini: 0.6177 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.4553 | ⭐ NEW BEST (peak ≥ trend)
Epoch 26/70 | Loss: 0.4311 | Val Loss: 0.4085 | Val Qini: 0.6246 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.4807 | ⭐ NEW BEST (peak ≥ trend)
Epoch 27/70 | Loss: 0.3027 | Val Loss: 0.3332 | Val Qini: 0.6427 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5050 | ⭐ NEW BEST (peak ≥ trend)
Epoch 28/70 | Loss: 0.2597 | Val Loss: 0.2678 | Val Qini: 0.6539 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5273 | ⭐ NEW BEST (peak ≥ trend)
Epoch 29/70 | Loss: 0.2116 | Val Loss: 0.2135 | Val Qini: 0.6641 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5479 | ⭐ NEW BEST (peak ≥ trend)
Epoch 30/70 | Loss: 0.1079 | Val Loss: 0.1717 | Val Qini: 0.6680 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5659 | ⭐ NEW BEST (peak ≥ trend)
Epoch 31/70 | Loss: 0.1087 | Val Loss: 0.1425 | Val Qini: 0.6782 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5827 | ⭐ NEW BEST (peak ≥ trend)
Epoch 32/70 | Loss: 0.0817 | Val Loss: 0.1234 | Val Qini: 0.6849 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.5980 | ⭐ NEW BEST (peak ≥ trend)
Epoch 33/70 | Loss: 0.0710 | Val Loss: 0.1117 | Val Qini: 0.6869 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6114 | ⭐ NEW BEST (peak ≥ trend)
Epoch 34/70 | Loss: 0.0418 | Val Loss: 0.1048 | Val Qini: 0.6897 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6231 | ⭐ NEW BEST (peak ≥ trend)
Epoch 35/70 | Loss: 0.0416 | Val Loss: 0.1008 | Val Qini: 0.6896 ✓ above trend but not peak (patience: 1/15)EMA Trend: 0.6331 | ✓ above trend but not peak (patience: 1/15)
Epoch 36/70 | Loss: 0.0215 | Val Loss: 0.0986 | Val Qini: 0.6933 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6421 | ⭐ NEW BEST (peak ≥ trend)
Epoch 37/70 | Loss: 0.0243 | Val Loss: 0.0974 | Val Qini: 0.6995 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6507 | ⭐ NEW BEST (peak ≥ trend)
Epoch 38/70 | Loss: 0.0210 | Val Loss: 0.0967 | Val Qini: 0.6996 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6581 | ⭐ NEW BEST (peak ≥ trend)
Epoch 39/70 | Loss: 0.0162 | Val Loss: 0.0962 | Val Qini: 0.7083 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6656 | ⭐ NEW BEST (peak ≥ trend)
Epoch 40/70 | Loss: 0.0228 | Val Loss: 0.0959 | Val Qini: 0.7099 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6723 | ⭐ NEW BEST (peak ≥ trend)
Epoch 41/70 | Loss: 0.0106 | Val Loss: 0.0956 | Val Qini: 0.7148 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6786 | ⭐ NEW BEST (peak ≥ trend)
Epoch 42/70 | Loss: 0.0114 | Val Loss: 0.0954 | Val Qini: 0.7162 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6843 | ⭐ NEW BEST (peak ≥ trend)
Epoch 43/70 | Loss: 0.0232 | Val Loss: 0.0951 | Val Qini: 0.7164 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.6891 | ⭐ NEW BEST (peak ≥ trend)
Epoch 44/70 | Loss: 0.0146 | Val Loss: 0.0949 | Val Qini: 0.6341 (patience: 1/15)EMA Trend: 0.6808 | (patience: 1/15)
Epoch 45/70 | Loss: 0.0131 | Val Loss: 0.0947 | Val Qini: 0.4151 (patience: 2/15)EMA Trend: 0.6410 | (patience: 2/15)
Epoch 46/70 | Loss: 0.0152 | Val Loss: 0.0945 | Val Qini: 0.3212 (patience: 3/15)EMA Trend: 0.5930 | (patience: 3/15)
Epoch 47/70 | Loss: 0.0108 | Val Loss: 0.0944 | Val Qini: 0.3180 (patience: 4/15)EMA Trend: 0.5518 | (patience: 4/15)
Epoch 48/70 | Loss: 0.0126 | Val Loss: 0.0942 | Val Qini: 0.3061 (patience: 5/15)EMA Trend: 0.5149 | (patience: 5/15)
Epoch 49/70 | Loss: 1.0733 | Val Loss: 0.0939 | Val Qini: 0.2989 (patience: 6/15)EMA Trend: 0.4825 | (patience: 6/15)
Epoch 50/70 | Loss: 0.0139 | Val Loss: 0.0934 | Val Qini: 0.2848 (patience: 7/15)EMA Trend: 0.4528 | (patience: 7/15)
Epoch 51/70 | Loss: 0.0140 | Val Loss: 0.0931 | Val Qini: 0.2796 (patience: 8/15)EMA Trend: 0.4269 | (patience: 8/15)
Epoch 52/70 | Loss: 0.0192 | Val Loss: 0.0929 | Val Qini: 0.2807 (patience: 9/15)EMA Trend: 0.4049 | (patience: 9/15)
Epoch 53/70 | Loss: 0.0211 | Val Loss: 0.0928 | Val Qini: 0.2784 (patience: 10/15)EMA Trend: 0.3859 | (patience: 10/15)
Epoch 54/70 | Loss: 0.0180 | Val Loss: 0.0926 | Val Qini: 0.2756 (patience: 11/15)EMA Trend: 0.3694 | (patience: 11/15)
Epoch 55/70 | Loss: 0.0128 | Val Loss: 0.0925 | Val Qini: 0.2752 (patience: 12/15)EMA Trend: 0.3553 | (patience: 12/15)
Epoch 56/70 | Loss: 0.0144 | Val Loss: 0.0924 | Val Qini: 0.2722 (patience: 13/15)EMA Trend: 0.3428 | (patience: 13/15)
Epoch 57/70 | Loss: 0.0131 | Val Loss: 0.0923 | Val Qini: 0.2679 (patience: 14/15)EMA Trend: 0.3316 | (patience: 14/15)
Epoch 58/70 | Loss: 0.0143 | Val Loss: 0.0922 | Val Qini: 0.2667 (patience: 15/15)EMA Trend: 0.3218 | (patience: 15/15)

🛑 Early stopping triggered at epoch 58!
   No valid peak (raw ≥ trend) found in last 15 epochs

✅ Training completed! Restored model to epoch 43
   Best Raw Qini: 0.7164
   Final EMA Trend: 0.3218
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 412312 | Val AUQC: 0.7164
Locked random seed: 42
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/70 | Loss: 1.4276 | Val Loss: 1.4243 | Val Qini: 0.8333 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.8333 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/70 | Loss: 1.4184 | Val Loss: 1.4150 | Val Qini: 0.9400 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.8493 | ⭐ NEW BEST (peak ≥ trend)
Epoch 3/70 | Loss: 1.4082 | Val Loss: 1.4055 | Val Qini: 1.0651 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.8817 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/70 | Loss: 1.3993 | Val Loss: 1.3956 | Val Qini: 1.1096 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.9158 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/70 | Loss: 1.3878 | Val Loss: 1.3849 | Val Qini: 1.1498 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.9509 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/70 | Loss: 1.3793 | Val Loss: 1.3727 | Val Qini: 1.1703 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.9838 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/70 | Loss: 1.3603 | Val Loss: 1.3587 | Val Qini: 1.0888 ✓ above trend but not peak (patience: 1/15)EMA Trend: 0.9996 | ✓ above trend but not peak (patience: 1/15)
Epoch 8/70 | Loss: 1.3404 | Val Loss: 1.3420 | Val Qini: 1.0871 ✓ above trend but not peak (patience: 2/15)EMA Trend: 1.0127 | ✓ above trend but not peak (patience: 2/15)
Epoch 9/70 | Loss: 1.3307 | Val Loss: 1.3222 | Val Qini: 1.0516 ✓ above trend but not peak (patience: 3/15)EMA Trend: 1.0185 | ✓ above trend but not peak (patience: 3/15)
Epoch 10/70 | Loss: 1.3100 | Val Loss: 1.2986 | Val Qini: 1.0287 ✓ above trend but not peak (patience: 4/15)EMA Trend: 1.0201 | ✓ above trend but not peak (patience: 4/15)
Epoch 11/70 | Loss: 1.2835 | Val Loss: 1.2705 | Val Qini: 0.9872 (patience: 5/15)EMA Trend: 1.0151 | (patience: 5/15)
Epoch 12/70 | Loss: 1.2500 | Val Loss: 1.2359 | Val Qini: 0.8907 (patience: 6/15)EMA Trend: 0.9965 | (patience: 6/15)
Epoch 13/70 | Loss: 1.2054 | Val Loss: 1.1930 | Val Qini: 0.8379 (patience: 7/15)EMA Trend: 0.9727 | (patience: 7/15)
Epoch 14/70 | Loss: 1.1389 | Val Loss: 1.1410 | Val Qini: 0.7845 (patience: 8/15)EMA Trend: 0.9445 | (patience: 8/15)
Epoch 15/70 | Loss: 1.0999 | Val Loss: 1.0794 | Val Qini: 0.7738 (patience: 9/15)EMA Trend: 0.9189 | (patience: 9/15)
Epoch 16/70 | Loss: 1.0151 | Val Loss: 1.0087 | Val Qini: 0.7981 (patience: 10/15)EMA Trend: 0.9007 | (patience: 10/15)
Epoch 17/70 | Loss: 0.9549 | Val Loss: 0.9293 | Val Qini: 0.8038 (patience: 11/15)EMA Trend: 0.8862 | (patience: 11/15)
Epoch 18/70 | Loss: 0.8622 | Val Loss: 0.8423 | Val Qini: 0.7961 (patience: 12/15)EMA Trend: 0.8727 | (patience: 12/15)
Epoch 19/70 | Loss: 0.7850 | Val Loss: 0.7501 | Val Qini: 0.7854 (patience: 13/15)EMA Trend: 0.8596 | (patience: 13/15)
Epoch 20/70 | Loss: 0.6729 | Val Loss: 0.6548 | Val Qini: 0.7634 (patience: 14/15)EMA Trend: 0.8452 | (patience: 14/15)
Epoch 21/70 | Loss: 0.5606 | Val Loss: 0.5599 | Val Qini: 0.7045 (patience: 15/15)EMA Trend: 0.8241 | (patience: 15/15)
Epoch 22/70 | Loss: 0.4565 | Val Loss: 0.4685 | Val Qini: 0.4624 (patience: 16/15)EMA Trend: 0.7698 | (patience: 16/15)
Epoch 23/70 | Loss: 0.3819 | Val Loss: 0.3838 | Val Qini: 0.2428 (patience: 17/15)EMA Trend: 0.6908 | (patience: 17/15)
Epoch 24/70 | Loss: 0.2873 | Val Loss: 0.3086 | Val Qini: 0.1178 (patience: 18/15)EMA Trend: 0.6048 | (patience: 18/15)
Epoch 25/70 | Loss: 0.2230 | Val Loss: 0.2449 | Val Qini: 0.1544 (patience: 19/15)EMA Trend: 0.5373 | (patience: 19/15)
Epoch 26/70 | Loss: 0.1774 | Val Loss: 0.1936 | Val Qini: 0.1697 (patience: 20/15)EMA Trend: 0.4821 | (patience: 20/15)
Epoch 27/70 | Loss: 0.1215 | Val Loss: 0.1558 | Val Qini: 0.1798 (patience: 21/15)EMA Trend: 0.4368 | (patience: 21/15)
Epoch 28/70 | Loss: 0.0940 | Val Loss: 0.1305 | Val Qini: 0.1850 (patience: 22/15)EMA Trend: 0.3990 | (patience: 22/15)
Epoch 29/70 | Loss: 1.0428 | Val Loss: 0.1150 | Val Qini: 0.1908 (patience: 23/15)EMA Trend: 0.3678 | (patience: 23/15)
Epoch 30/70 | Loss: 0.0447 | Val Loss: 0.1066 | Val Qini: 0.1881 (patience: 24/15)EMA Trend: 0.3408 | (patience: 24/15)
Epoch 31/70 | Loss: 0.0371 | Val Loss: 0.1012 | Val Qini: 0.1909 (patience: 25/15)EMA Trend: 0.3183 | (patience: 25/15)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 15 epochs

✅ Training completed! Restored model to epoch 6
   Best Raw Qini: 1.1703
   Final EMA Trend: 0.3183
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 42 | Val AUQC: 1.1703
Locked random seed: 1874
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/70 | Loss: 1.3807 | Val Loss: 1.3788 | Val Qini: 0.7402 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.7402 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/70 | Loss: 1.3708 | Val Loss: 1.3683 | Val Qini: 0.7054 (patience: 1/15)EMA Trend: 0.7350 | (patience: 1/15)
Epoch 3/70 | Loss: 1.3627 | Val Loss: 1.3573 | Val Qini: 0.6892 (patience: 2/15)EMA Trend: 0.7281 | (patience: 2/15)
Epoch 4/70 | Loss: 1.3471 | Val Loss: 1.3459 | Val Qini: 0.5676 (patience: 3/15)EMA Trend: 0.7040 | (patience: 3/15)
Epoch 5/70 | Loss: 1.3379 | Val Loss: 1.3334 | Val Qini: 0.3684 (patience: 4/15)EMA Trend: 0.6537 | (patience: 4/15)
Epoch 6/70 | Loss: 1.3255 | Val Loss: 1.3197 | Val Qini: 0.2222 (patience: 5/15)EMA Trend: 0.5890 | (patience: 5/15)
Epoch 7/70 | Loss: 1.3118 | Val Loss: 1.3042 | Val Qini: 0.1558 (patience: 6/15)EMA Trend: 0.5240 | (patience: 6/15)
Epoch 8/70 | Loss: 1.2850 | Val Loss: 1.2860 | Val Qini: 0.2250 (patience: 7/15)EMA Trend: 0.4791 | (patience: 7/15)
Epoch 9/70 | Loss: 1.2686 | Val Loss: 1.2643 | Val Qini: 0.1603 (patience: 8/15)EMA Trend: 0.4313 | (patience: 8/15)
Epoch 10/70 | Loss: 1.2570 | Val Loss: 1.2379 | Val Qini: 0.1130 (patience: 9/15)EMA Trend: 0.3836 | (patience: 9/15)
Epoch 11/70 | Loss: 1.2140 | Val Loss: 1.2059 | Val Qini: 0.1141 (patience: 10/15)EMA Trend: 0.3432 | (patience: 10/15)
Epoch 12/70 | Loss: 1.1646 | Val Loss: 1.1672 | Val Qini: 0.0946 (patience: 11/15)EMA Trend: 0.3059 | (patience: 11/15)
Epoch 13/70 | Loss: 1.1272 | Val Loss: 1.1205 | Val Qini: 0.1157 (patience: 12/15)EMA Trend: 0.2773 | (patience: 12/15)
Epoch 14/70 | Loss: 1.0902 | Val Loss: 1.0653 | Val Qini: 0.1574 (patience: 13/15)EMA Trend: 0.2594 | (patience: 13/15)
Epoch 15/70 | Loss: 0.9884 | Val Loss: 1.0019 | Val Qini: 0.1066 (patience: 14/15)EMA Trend: 0.2364 | (patience: 14/15)
Epoch 16/70 | Loss: 0.9807 | Val Loss: 0.9309 | Val Qini: 0.0877 (patience: 15/15)EMA Trend: 0.2141 | (patience: 15/15)
Epoch 17/70 | Loss: 0.8796 | Val Loss: 0.8532 | Val Qini: 0.1269 (patience: 16/15)EMA Trend: 0.2011 | (patience: 16/15)
Epoch 18/70 | Loss: 0.7577 | Val Loss: 0.7697 | Val Qini: 0.1370 (patience: 17/15)EMA Trend: 0.1915 | (patience: 17/15)
Epoch 19/70 | Loss: 0.6546 | Val Loss: 0.6814 | Val Qini: 0.1714 (patience: 18/15)EMA Trend: 0.1884 | (patience: 18/15)
Epoch 20/70 | Loss: 0.5912 | Val Loss: 0.5912 | Val Qini: 0.1749 (patience: 19/15)EMA Trend: 0.1864 | (patience: 19/15)
Epoch 21/70 | Loss: 0.4822 | Val Loss: 0.5020 | Val Qini: 0.1797 (patience: 20/15)EMA Trend: 0.1854 | (patience: 20/15)
Epoch 22/70 | Loss: 0.3938 | Val Loss: 0.4171 | Val Qini: 0.1740 (patience: 21/15)EMA Trend: 0.1837 | (patience: 21/15)
Epoch 23/70 | Loss: 0.3385 | Val Loss: 0.3395 | Val Qini: 0.1595 (patience: 22/15)EMA Trend: 0.1801 | (patience: 22/15)
Epoch 24/70 | Loss: 0.2283 | Val Loss: 0.2714 | Val Qini: 0.1496 (patience: 23/15)EMA Trend: 0.1755 | (patience: 23/15)
Epoch 25/70 | Loss: 0.1769 | Val Loss: 0.2146 | Val Qini: 0.1482 (patience: 24/15)EMA Trend: 0.1714 | (patience: 24/15)
Epoch 26/70 | Loss: 0.1210 | Val Loss: 0.1709 | Val Qini: 0.1527 (patience: 25/15)EMA Trend: 0.1686 | (patience: 25/15)
Epoch 27/70 | Loss: 0.1101 | Val Loss: 0.1406 | Val Qini: 0.1537 (patience: 26/15)EMA Trend: 0.1664 | (patience: 26/15)
Epoch 28/70 | Loss: 0.0807 | Val Loss: 0.1209 | Val Qini: 0.1549 (patience: 27/15)EMA Trend: 0.1646 | (patience: 27/15)
Epoch 29/70 | Loss: 0.0558 | Val Loss: 0.1090 | Val Qini: 0.1581 (patience: 28/15)EMA Trend: 0.1637 | (patience: 28/15)
Epoch 30/70 | Loss: 0.0406 | Val Loss: 0.1021 | Val Qini: 0.1608 (patience: 29/15)EMA Trend: 0.1632 | (patience: 29/15)
Epoch 31/70 | Loss: 0.5116 | Val Loss: 0.0983 | Val Qini: 0.1562 (patience: 30/15)EMA Trend: 0.1622 | (patience: 30/15)

🛑 Early stopping triggered at epoch 31!
   No valid peak (raw ≥ trend) found in last 15 epochs

✅ Training completed! Restored model to epoch 1
   Best Raw Qini: 0.7402
   Final EMA Trend: 0.1622
   Strategy: Selected highest peak that stayed above EMA trend
  ✔️ Đã xong Seed 1874 | Val AUQC: 0.7402
Locked random seed: 902745
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Two-Stage EMA Filter (alpha=0.15)
   EMA filters noise spikes, Raw Qini determines peak height
   Select checkpoint: raw_qini is highest AND raw_qini >= ema_qini
Epoch 1/70 | Loss: 1.4093 | Val Loss: 1.4075 | Val Qini: 0.1208 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1208 | ⭐ NEW BEST (peak ≥ trend)
Epoch 2/70 | Loss: 1.3998 | Val Loss: 1.3949 | Val Qini: 0.1150 (patience: 1/15)EMA Trend: 0.1199 | (patience: 1/15)
Epoch 3/70 | Loss: 1.3851 | Val Loss: 1.3818 | Val Qini: 0.1214 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1202 | ⭐ NEW BEST (peak ≥ trend)
Epoch 4/70 | Loss: 1.3720 | Val Loss: 1.3679 | Val Qini: 0.1257 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1210 | ⭐ NEW BEST (peak ≥ trend)
Epoch 5/70 | Loss: 1.3566 | Val Loss: 1.3529 | Val Qini: 0.1589 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1267 | ⭐ NEW BEST (peak ≥ trend)
Epoch 6/70 | Loss: 1.3372 | Val Loss: 1.3362 | Val Qini: 0.2021 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1380 | ⭐ NEW BEST (peak ≥ trend)
Epoch 7/70 | Loss: 1.3201 | Val Loss: 1.3169 | Val Qini: 0.1839 ✓ above trend but not peak (patience: 1/15)EMA Trend: 0.1449 | ✓ above trend but not peak (patience: 1/15)
Epoch 8/70 | Loss: 1.2901 | Val Loss: 1.2940 | Val Qini: 0.1556 ✓ above trend but not peak (patience: 2/15)EMA Trend: 0.1465 | ✓ above trend but not peak (patience: 2/15)
Epoch 9/70 | Loss: 1.2741 | Val Loss: 1.2666 | Val Qini: 0.1447 (patience: 3/15)EMA Trend: 0.1462 | (patience: 3/15)
Epoch 10/70 | Loss: 1.2419 | Val Loss: 1.2341 | Val Qini: 0.1405 (patience: 4/15)EMA Trend: 0.1454 | (patience: 4/15)
Epoch 11/70 | Loss: 1.2314 | Val Loss: 1.1961 | Val Qini: 0.1678 ✓ above trend but not peak (patience: 5/15)EMA Trend: 0.1487 | ✓ above trend but not peak (patience: 5/15)
Epoch 12/70 | Loss: 1.1688 | Val Loss: 1.1525 | Val Qini: 0.1858 ✓ above trend but not peak (patience: 6/15)EMA Trend: 0.1543 | ✓ above trend but not peak (patience: 6/15)
Epoch 13/70 | Loss: 1.1032 | Val Loss: 1.1023 | Val Qini: 0.1984 ✓ above trend but not peak (patience: 7/15)EMA Trend: 0.1609 | ✓ above trend but not peak (patience: 7/15)
Epoch 14/70 | Loss: 1.1186 | Val Loss: 1.0443 | Val Qini: 0.2286 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1711 | ⭐ NEW BEST (peak ≥ trend)
Epoch 15/70 | Loss: 0.9956 | Val Loss: 0.9778 | Val Qini: 0.2631 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1849 | ⭐ NEW BEST (peak ≥ trend)
Epoch 16/70 | Loss: 0.9261 | Val Loss: 0.9024 | Val Qini: 0.2750 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.1984 | ⭐ NEW BEST (peak ≥ trend)
Epoch 17/70 | Loss: 0.8386 | Val Loss: 0.8191 | Val Qini: 0.2919 ⭐ NEW BEST (peak ≥ trend)EMA Trend: 0.2124 | ⭐ NEW BEST (peak ≥ trend)